### ISSUE TITLE
 Plugin's get_option_as_list() method doesn't work when using "," as the list separator

### ISSUE THREAD

**Issue by rmetrich** [sosreport/sos#1023]
I found that when using the "-k <plugin>.<option>=<value>" command line option, and trying to specify a comma-separated list of values in the <value> field, the resulting value of a call to get_option_as_list(<option>) was only the first item of the list.

This is due to the list splitting automatically occurring during option parsing (OptionParserExtended class and "extend" keyword).
This "extend" feature is used for "-k".
Due to the splitting, only the first value of the list gets returned.

**Comment by rmetrich** [comment]
Reproducer.

Install reproducer in /usr/lib/python2.7/site-packages/sos/plugins/
2. Run:
    sosreport -o dummy --no-report --batch -k dummy.mylist="item1,item2" | grep dummy

Actual results:

# sosreport -o dummy --no-report --batch -k dummy.mylist="item1,item2" | grep dummy
unable to set option for disabled or non-existing plugin (item2)
[plugin:dummy] Item: item1
  Running 1/1: dummy...   

Expected results:

1. no error ("unable to set option ...")
2. 2 items displayed ("item1" and "item2")

[dummy.txt](https://github.com/sosreport/sos/files/1041373/dummy.txt)

**Comment by pmoravec** [comment]
The problem technically lies in `-k` option with `action="extend"` that is overwritten in `OptionParserExtended` / `SosOption` class to split the values of `-k` argument

    dummy.mylist='item1,item2'

to:

    ['dummy.mylist=item1', 'item2']

due to https://github.com/sosreport/sos/blob/master/sos/sosreport.py#L135

**Comment by pmoravec** [comment]
I have no good idea how to fix this. The sosreport.py#L135 is required for arguments like:

    sosreport -o general,logs,memory

where ',' is interpreted as an item separator in the argument list. The same can be used for:

    sosreport -k plug1.opt1=val1,plug2.opt2=val2

 But in the example in this Issue, ',' is to be interpreted as a character without a semantics meaning.

We can dirty-patch it by interpreting ',' as separator only for `-k` option only if it is in `\S+\.\S+=\S+[,\S+\.\S+=\S+]*`format/pattern (I hope my regexp is correct), but deal with ',' as a regular character when inside the `\S+` ?

**Comment by bmr-cymru** [comment]
The comma still has semantic meaning (just not at the level of expression we are parsing it at, at that moment).

Really, to fix this properly we should parse these options "properly"; not necessarily by introducing a formal grammar, but at least by imposing a syntactic structure and well-defined semantics (i.e. token `val1` is assigned to `opt1` of `plug1` in the example above).

The point is that none of this was ever intended to be used this way (which is why the title of this issue doesn't make any sense - it's like saying "unlink(2) fails when given a directory" - well sure it does. It was never designed or intended to deal with a directory).

Similarly, the current `sos` plugin option model does not support plugin option **values** that are a comma-separated list (only comma separated lists of **plugin options**).

It's fine to want the former, and we'd be happy to extend `sos` to allow that, but nothing is broken here: it's just a known limitation of current option parsing.

**Comment by TurboTurtle** [comment]
I am closing this out per the previous discussion around this - the issue reported is a known limitation of the design of sos option handling. Plugin options that may accept a list of values should use a non-comma delimiter for splitting - such as a colon which has recently been the defacto delimiter.

I have updated the "How to write a Plugin" wiki page to reflect this.
