### ISSUE TITLE
Limit size of systemd journal collection

### ISSUE THREAD

**Issue by jbainbri** [sosreport/sos#1029]
When the systemd journal is configured to a very large max size like 4 GiB, the `logs` plugin collects the entire journal twice, once in verbose mode. This can result in very large sosreports:

    $ du -s -BM sos_commands/logs/*
    1256M   sos_commands/logs/journalctl_--all_--this-boot_--no-pager
    4090M   sos_commands/logs/journalctl_--all_--this-boot_--no-pager_-o_verbose

Suggest apply a size limitation to this command, like the existing `messages` file is limited to 15 MiB.

**Comment by TurboTurtle** [comment]
Ran into an issue with this today where journal sizes were outrageous. Looking into this, I don't believe there is any way within journalctl to only read X number of bytes. The only size-related functions are related to vacuuming the journal to a specific size, which we don't want to do here since that is data-destructive.

I think the only way sos could do this is via `bufsize` here within `sos_get_command_output` in `utilities.py` which is what is actually running any given journalctl command:

```
    p = Popen(expanded_args, shell=False, stdout=PIPE,
              stderr=STDOUT if stderr else PIPE,
              bufsize=-1, env=cmd_env, close_fds=True,
              preexec_fn=_child_prep_fn)
    stdout, stderr = p.communicate()
```

However, the `-1` is set to use the OS's default of buffered or unbuffered for the output, which is usually fully buffered. I *think* this could reasonably be changed to (optionally) reflect a given `--log-size`.

Thoughts? @bmr-cymru

**Comment by bmr-cymru** [comment]
Afaik it is not so simple as that when using `Pipe.communicate()`, since regardless of buffer settings this will accumulate all the output into a Python `string` object in one go. To actually convert this to a *streaming* style of IO is more complex; we have to deal with the underlying process interface and implement two-way pipe IO (I never managed to make this work without deadlocking on input to the child, but that was a few years back).

**Comment by TurboTurtle** [comment]
If it is a standard `str` object and not unicode, isn't byte length the same as character length here? So we could just crop the returned string to a fixed length before converting it to unicode?

E.G.
```
    return {
        'status': p.returncode,
        'output': stdout[-131072:].decode('utf-8', 'ignore')
    }
```

To return the last, for example, 128k (or whatever we want)? I did a quick test of this and it seems to work:

```
jake@cadia sos]$ sudo ./sosreport -o logs --batch

sosreport (version 3.2)

This command will collect system configuration and diagnostic
information from this Fedora system. An archive containing the collected
information will be generated in /var/tmp/sos.66LTJh.

For more information on the Fedora Project visit:

  https://fedoraproject.org/

The generated archive may contain data considered sensitive and its
content should be reviewed by the originating organization before being
passed to any third party.

No changes will be made to system configuration.


 Setting up archive ...
 Setting up plugins ...
 Running plugins. Please wait ...

  Running 1/1: logs...        

Creating compressed archive...

Your sosreport has been generated and saved in:
  /var/tmp/sosreport-cadia-20170713135138.tar.xz

The checksum is: 8eb5023649a4f00b3dfb87334ec61391

Please send this file to your support representative.

[...]
[jake@cadia sosreport-cadia-20170713135138]$ ll -h sos_commands/logs/
total 388K
-rw-r--r--. 1 jake jake   53 Jul 13 13:51 journalctl_--disk-usage
-rw-r--r--. 1 jake jake 128K Jul 13 13:51 journalctl_--no-pager_--all_--boot_--output_verbose
-rw-r--r--. 1 jake jake 128K Jul 13 13:51 journalctl_--no-pager_--boot
-rw-r--r--. 1 jake jake 128K Jul 13 13:51 journalctl_--no-pager_--since_-3days
[jake@cadia sosreport-cadia-20170713135138]$ 
```

I realize this isn't ideal since we'd still accumulate the entire output, but this seems like an easy way to implement a universal size limit.

**Comment by bmr-cymru** [comment]
It solves one part of the problem (applying limits to the output), but as you note, the entire content is still going to be read into memory: we've already seen a few reports where journal collection blew up with ENOMEM.

I'm not keen on this as an interim solution because of this problem, but at the same time the solution avoiding `communicate()` is pretty complicated (ironically, at least for me, it would be easier to solve in a C extension - just that then creates a whole tonne of other packaging and distribution problems... :-/).

**Comment by TurboTurtle** [comment]
I was playing with this a bit more, and I found a workable solution that involves writing stdout into a `queue` that we then pull from to construct the string object we end up returning. This 'works', but in reverse (output would be limited to the first X bytes, not the last) - this could be solved by using a `deque` instead of a queue, but then we run into the issue that a deque's maximum size is based on list length, not byte size. 

:\

**Comment by TurboTurtle** [comment]
Actually, I took another swing at this using `deque`. I've come up with this:

https://github.com/TurboTurtle/sos/commit/579400c5084a13fd962b72316e4507f00d047039

This successfully limits the output size, with the 'correct' end of the output being captured. 

Anecdotally I've also noticed:

- No real effect on how long sos needs to run
- Seems to limit memory usage fairly effectively. Running `sosreport` normally on my system I see it will quickly get over 500mb of memory usage, with spikes over a GB. With this change, I did not see it consume more than ~300mb at any time. Fairly stock F25 installation. 

The above uses 100mb as a size limit example. If this looks ok to you I can move it forward. My thoughts are that we should just inherit `--log-size` here - with potentially increasing the default value for that since 15mb might be a bit low for a general use case.

**Comment by TurboTurtle** [comment]
@bmr-cymru thoughts on this? I'm happy to either move the above forward or go back to the drawing board on this one.

**Comment by bmr-cymru** [comment]
Hey @TurboTurtle. I was out on PTO this & last week, so I haven't had a chance to look yet, but the numbers you report certainly sound like progress in the right direction.

I have this & the CDA pull at the head of my queue for next week - I'll try and get some meaningful feedback down then.

**Comment by TurboTurtle** [comment]
Between 2fcf5f0 and 40295a3 this is now handled. By default journals are now limited to 100MB, unless the user specifies a higher `--log-size` or uses `--all-logs` which will disable size limiting entirely.
