### ISSUE TITLE
[Cinder]openstack cinder plugin should exclude '/etc/cinder/volumes' directory

### ISSUE THREAD

**Issue by chaitshastri** [sosreport/sos#1056]
Openstack cinder plugin captures the 'volumes' directory in '/etc/cinder'.
We have seen a scenario where the sosreport got hung while archiving a cinder volume of 1 TB present in volumes directory.

**Comment by bmr-cymru** [comment]
What on earth is it storing "volumes" in `/etc` for? That sounds like a pretty gross violation of the FHS: `/etc` is for configuration files:

```
"The /etc/ directory is reserved for configuration files that are local to the machine. No binaries are to be put in /etc/. Any binaries that were once located in /etc/ should be placed into /sbin/ or /bin/."
```

Could you paste the output of `ls -l /etc/cinder` and `ls -l /etc/cinder/volumes` here so that we can see what we are looking at? (e.g. if this is actually a symlink to some other location).

Excluding these paths for affected Cinder releases is not a problem but we'd like to understand the situation properly before making any changes.

**Comment by psachin** [comment]
@bmr-cymru 

```
[plugin:openstack_cinder] regex substitution failed for '/etc/cinder/volumes/cinder-volumes' with: ''
[plugin:openstack_cinder] regex substitution failed for '/etc/cinder/cinder-scheduler.conf' with: '[Errno 2] No such file or directory: '/var/tmp/sos.gFkweh/sosreport-NAME-CHANGED/etc/cinder/cinder-scheduler.conf''
[plugin:openstack_cinder] regex substitution failed for '/etc/cinder/cinder-volume.conf' with: '[Errno 2] No such file or directory: '/var/tmp/sos.gFkweh/sosreport-NAME-CHANGED/etc/cinder/cinder-volume.conf''
Traceback (most recent call last):
  File "/sbin/sosreport", line 25, in <module>
    main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/sos/sosreport.py", line 1593, in main
    sos.execute()
  File "/usr/lib/python2.7/site-packages/sos/sosreport.py", line 1570, in execute
    self.version()
  File "/usr/lib/python2.7/site-packages/sos/sosreport.py", line 1231, in version
    dest='version.txt')
  File "/usr/lib/python2.7/site-packages/sos/archive.py", line 184, in add_string
    f.write(content)
  File "/usr/lib64/python2.7/codecs.py", line 691, in write
    return self.writer.write(data)
  File "/usr/lib64/python2.7/codecs.py", line 352, in write
    self.stream.write(data)
IOError: [Errno 28] No space left on device
```

**Comment by psachin** [comment]
@bmr-cymru 

`/etc/cinder/volumes/cinder-volumes` is loop-back device

**Comment by bmr-cymru** [comment]
That's not so helpful to the problem (it's obvious we're going to end up with ENOSPC copying TiBs of data around...)

Please post the directory listings (with `-l`) so that we can see what is here.

**Comment by psachin** [comment]
@bmr-cymru 

I have asked customer for directory listing. It may take a while for him to return with output. BTW the error occurred on RHOSP-8(sosreport v3.2). I have scanned my RHOSP-8 setup and I see
```
volume_driver=cinder.volume.drivers.lvm.LVMVolumeDriver
volumes_dir=/var/lib/cinder/volumes
volume_group=cinder-volumes
```

Customer must have `volumes_dir` set to `/etc/cinder/volumes`.  In any case if "/volumes" as meant for cinder volume, sosreport should exclude that.  We may have no encountered this issue because LVM driver as not supported in production environments.

**Comment by bmr-cymru** [comment]
Is this an error or a valid configuration?

It is impossible for us to harden `sos` against any possible customer misconfiguration; if they place files into locations that are collected without explicit file limits then the error seen here will occur (to avoid this we would need to implement a global maximum file size somewhere; that introduces its own set of problems both API wise and in terms of behaviour so we have not to date considered it).

**Comment by psachin** [comment]
@bmr-cymru 

```
$ ls -l /etc/cinder
total 48
-rw-r----- 1 root   cinder 1865 Dec 22  2015 api-paste.ini
-rw-r----- 1 cinder cinder  630 Jul 13 20:39 cinder-api.conf
-rw-r----- 1 cinder cinder 2314 Jul 13 20:39 cinder.conf
-rw-r----- 1 cinder cinder  654 Jul 13 20:39 cinder-scheduler.conf
-rw-r----- 1 cinder cinder 1089 Jul 13 20:39 cinder-volume.conf
-rw-r----- 1 cinder cinder 1375 Jul 13 20:40 logging.conf
drwxr-xr-x 2 cinder cinder 4096 Jul 13 20:39 nfs
-rw-r----- 1 cinder cinder 4687 Jul 13 20:40 policy.json
-rw-r----- 1 root   cinder  942 Dec 12  2016 rootwrap.conf
drwxr-xr-x 2 root   root   4096 Jul 13 20:39 rootwrap.d
drwxr-xr-x 2 cinder root   4096 Jul 17 13:34 volumes

$ ls -l /etc/cinder/volumes
total 8
-rw-r--r-- 1 root root 1099511627776 Jul 17 13:34 cinder-volumes
```
