### ISSUE TITLE
Support PostgreSQL 9.5 from SoftwareCollections in postgresql plugin

### ISSUE THREAD

**Issue by sandrobonazzola** [sosreport/sos#1090]
Once Issue #900 will be available, sos postgresql plugin should be adapted for allowing to collect data from PosgreSQL 9.5 (or possibly generic version in software collections) in addition to the system postgresql setup.

**Comment by sandrobonazzola** [comment]
oVirt project will consume the plugin when available, tracking it on https://bugzilla.redhat.com/show_bug.cgi?id=1427827

**Comment by pmoravec** [comment]
Issue #900 needs some re-work while the author is not further involved / interested. If it is prerequisite of this issue, could you pls. improve that PR?

What in particular is required to be changed? In general: in what new situation (triggered by some package or file presence) we should collect what files or what command outputs?

More technically: shall we enable `postgresql` plugin also when a different package (or file) is present? What particular configs or logs shall we collect? What command outputs? Something secret to scrub?

I.e. technical specification behind this issue is completely missing..

**Comment by sandrobonazzola** [comment]
In practice what's needed is to get the same amount of information within the sos report comparing an install running with a posgresql from EL7 base and an install running postresql95 from software collections.

current result running sosreport on a postgresql base system is that postgresql sos plugin is enabled and collect database data, logs, config, etc... while running on a posgresql95 scl system the postgresql sos plugin is disabled and even forcing it enabled it doesn't collect anything.

expected result is that running sos on a  posgresql95 scl system either the postgresql plugin or a brand new plugin is enabled and collect as much information as the ones collected by postgresql plugin on the base version.

I would expect that if both postgresql base and posgresql95 scl are running on the same host, data from both instances are collected (not an hard requirement on my side).

**Comment by pmoravec** [comment]
OK, so:

- how can `sos` detect `postgresql` is installed from `scl`? (it can detect a package installed or a file present, so what package or file exists (only) on such system?)
- where the logs and configs and commands to execute are placed? (if the locations are similar to current ones, we can extend the current plugin, otherwise we might need to add a new plugin)

Optionally, please provide me e.g. via mail an access to such a system to let me check/guess by myself.

**Comment by sandrobonazzola** [comment]
> how can sos detect postgresql is installed from scl? (it can detect a package installed or a file present, so what package or file exists (only) on such system?)

rh-postgresql95-postgresql-server is installed on systems providing postgresql95 from SCL.

> where the logs and configs and commands to execute are placed? (if the locations are similar to current ones, we can extend the current plugin, otherwise we might need to add a new plugin)

I don't think you can just reuse existing locations. briefly looking I see data dir under:
/var/opt/rh/rh-postgresql95
and config files under /etc/opt/rh/rh-postgresql95/postgresql-setup

Also, in order to run commands like pgsql you need to enable scl; see https://www.softwarecollections.org/en/scls/rhscl/rh-postgresql95/

> Optionally, please provide me e.g. via mail an access to such a system to let me check/guess by myself.

Sent you by email.
