### ISSUE TITLE
Add ability for independent plugin location

### ISSUE THREAD

**Issue by jgrund** [sosreport/sos#1097]
It would be useful if `sos` could support plugins in paths other than `sos.plugins`.

Seems like this could be something configurable via `/etc/sos.conf`.

**Comment by bmr-cymru** [comment]
No: although we call the components "plugins" they are today tied very closely to the interface defined by the `Plugin` class shipped in each release. Substantial porting work may be required to move plugins from one release to another and ensure they remain functional.

After numerous bad experiences with downstream packaging taking "creative" approaches to shipping out-of-tree plugins we have taken the position that this is strongly discouraged: plugins should be submitted upstream, pass through code review by the team that maintains `sos`, and then be maintained so that when changes are made to the core interfaces the plugins can be updated accordingly.

It might help us to understand your use case better, and whether there is another way to achieve what you want, if you actually explain the result you want to achieve - why would this be useful to you, and how would you want to use it?

**Comment by jgrund** [comment]
Ok, so really the term `Plugin` is a misnomer here, as the expectation is that all functionality should be shipping with `sos`.

My use case is to have an external plugin that I can iterate on quickly and possibly submit back upstream once I feel it's stable in terms of functionality.

**Comment by bmr-cymru** [comment]
> Ok, so really the term Plugin is a misnomer here, as the expectation is that all functionality should be shipping 
> with sos.

Correct - it's been this way since 2006 though, and there seems little point in changing a lot of names for that reason alone - the plugins in sos are more like the ones you might find in the NSS (namespace switch), or the modules Apache provides. They are very closely integrated with the main package. At one point we considered switching to calling them modules, however in Python this just leads into even more confusion.

> My use case is to have an external plugin that I can iterate on quickly and possibly submit back upstream once I feel it's stable in terms of functionality.

OK. I guess what I'm missing here is how that actually helps develop your plugin? Most if not all `sos` developers work the way that you describe (but dropping plugins into `/usr/lib/python*/.../site-packages/sos/plugins`). You can either work in-tree and build your own packages, or out of tree and drop the result into that path. If you need to package your plugin before it goes upstream you can do that - just place it at the same location. Obviously in this scenario you need to take care to avoid API version conflicts - depend on a specific version of `sos` from your extra plugins package, for example.

**Comment by bmr-cymru** [comment]
It's also a *really* good idea, if you're planning some plugin development work that might take a while, i.e. it's a non-trivial piece of work, to discuss that upstream first - file an issue, or start a thread on the mailing list and we can use it as a place to discuss and coordinate with you.

The plugins that have the hardest time of all getting upstream are the large, complex ones that saw significant work before they were ever discussed with the `sos` team.

**Comment by jgrund** [comment]
> OK. I guess what I'm missing here is how that actually helps develop your plugin? Most if not all sos developers work the way that you describe (but dropping plugins into /usr/lib/python*/.../site-packages/sos/plugins). You can either work in-tree and build your own packages, or out of tree and drop the result into that path. If you need to package your plugin before it goes upstream you can do that - just place it at the same location. Obviously in this scenario you need to take care to avoid API version conflicts - depend on a specific version of sos from your extra plugins package, for example.

Right, and that's what I'm planning to do, just felt like it was breaking module boundaries to place my code into another package during install time.

**Comment by bmr-cymru** [comment]
If you have to package something out-of-tree, that's the right way to do it.

**Comment by brianjmurrell** [comment]
One other use-case for externally packaging a plugin is that the maintainer/developer of such a plugin wants to iterate on releases more quickly than the `sosreport` provider (i.e. RedHat) is willing to iterate.

I think this is particularly true at initial plugin development time, as it becomes clear that one's existing release of their plugin is not collecting all of the desired information.  But it's also an ongoing need as the nature of users' problems evolve and differ and support people find they need more/different information.

In such cases, being able to just publish a new RPM with a newer plugin and then ask the user to just `yum update` to get that newer release is a lot smoother than having to direct them on how to download and override your `.py` file and everything that is associated with that.

**Comment by bmr-cymru** [comment]
> One other use-case for externally packaging a plugin is that the maintainer/developer of such a plugin wants to iterate on releases more quickly than the sosreport provider (i.e. RedHat) is willing to iterate.

But how does an extra directory help with this? There is no problem with multiple packages installing files to the same directory for any known Linux package manager, much less the ones `sos` supports (otherwise `etc`, `/lib` and `/usr/lib` would be a bit of a trainwreck...)

> In such cases, being able to just publish a new RPM with a newer plugin and then ask the user to just yum update 

With my downstream (Red) hat on, we have done this many times at Red Hat - initial plugins for Gluster, RHEV, and numerous other products were developed and shipped in exactly this fashion. Once they matured to a point they could be submitted upstream these packages become obsolete.

There's absolutely nothing stopping anybody from doing this with the Red Hat and Fedora packages today, or from doing the same with the Debian and Ubuntu builds.

I still don't understand why a whole new plugin directory is needed for this.

**Comment by brianjmurrell** [comment]
> But how does an extra directory help with this?

I think it's just more philosophical than anything.  Of course there is no package manager that has a problem with it.  OP's issue was simply:

> felt like it was breaking module boundaries to place my code into another package during install time

So purely organisational and probably mostly just because _sos_ is a python module.  I can understand how it seems like a violation of the _sos_ module to populate it's hierarchy with things it didn't supply.

> I still don't understand why a whole new plugin directory is needed for this.

It's not, technically.  This can probably be closed.

**Comment by jgrund** [comment]
> I think it's just more philosophical than anything.

It certainly was philosophical. That said, I'm packaging and shipping a plugin by placing it in the correct dir at runtime, so I'll close this.

**Comment by bmr-cymru** [comment]
I see the point wrt Python packaging conventions, but `sos` has been organising these files this way for a long time - if anything, it may make sense to move to the type of approach used by `dnf` (and also `yum` and others - it seems to be a common idiom). This involves creating a virtual Python package on-the-fly and populating it with plugins (submodules) loaded from arbitrary file system locations.

This would be a non-trivial amount of work, and although I think it likely makes sense long term it is not something we could put an immediate priority on due to the amount of other work we have pending (it doesn't really deliver a big enough bang for the buck it would cost right now). As there is a fairly small team of core developers (working on code outside `sos/plugins` we have to focus on the things that give an immediate benefit to users or people analysing `sos` data - contributions are welcome however and I would be very happy to review a new classloader that implemented some of these capabilities. The current one has served us well but it certainly has its hokey aspects.
