### ISSUE TITLE
[sosreport] Run plugin collection in parallel

### ISSUE THREAD

**Issue by iranzo** [sosreport/sos#1176]
If I'm not wrong as per https://github.com/sosreport/sos/blob/master/sos/sosreport.py#L1281

We're running plugin collection sequentially which can be nice for enumerating but performance wise takes a lot of time.

In citellus, using:

~~~
import subprocess
from multiprocessing import Pool, cpu_count
~~~

We moved to using a function that runs each plugin and we collect all results at the same time:

https://github.com/zerodayz/citellus/blob/master/citellusclient/shell.py#L355  and https://github.com/zerodayz/citellus/blob/master/citellusclient/shell.py#L358

In this way we get the result output from each plugin at once, running one process per CPU in the system we're using.

At the end sosreport will still need to tar the output of all plugins, but we could save time there.

Was there a reason this was discarded before?

**Comment by TurboTurtle** [comment]
I believe this is being discussed in #737 

I have a working patch that uses the `concurrent.futures` library to bring plugin concurrency (back?) to sos, however there is one caveat. The concurrent.futures library is in the standard library as of python-3.2, however for 2.7 it came about via the `futures` pip module in 2.7.6. I went with concurrent.futures because of a `multiprocessing` bug that was only resolved in that library and not backported to the main multiprocessing library (which concurrent.futures wraps).

In #737 I believe this is the same conundrum that is being seen with other concurrency libraries - the python3 libraries are not available/not readily available in python2 - and there are a couple distro's where that is the installed python version (for example RHEL 7).

For reference for @pmoravec and @bmr-cymru my concurrent branch - https://github.com/TurboTurtle/sos/commit/3679cc06d4136b92353a881595d84f12ffacffc6 - has this working and implements a whole-plugin timeout. I'm just not sure of the viability of it given the python-2.7 restrictions noted above.

**Comment by TurboTurtle** [comment]
Closing per 04df944

**Comment by xueweiz** [comment]
Hi Jake, I wonder have anyone considered to let sosreport fall back to single-thread if there is no concurrent.futures library?

Today, if we follow the instruction at https://github.com/sosreport/sos#manual-installation on a python2 based distro, sosreport will abort with error "ImportError: No module named concurrent.futures".

Installing the library would solve the problem. But do you think it make sense to let the code fall back to single thread mode if it cannot find the library, instead of quitting? Thanks!

**Comment by iranzo** [comment]
I would say that fallback to single could work!

**Comment by TurboTurtle** [comment]
Initially I have two thoughts:

1) It'd be best overall to simply correct the README to indicate you need python2-futures if you're running on python2.

2) python2 is EOL in a little over a year and `concurrent.futures` is in the python3 standard library. If you're using sos on a python2 distribution then it should be installed via that distribution's packaging which should include python2-futures as a runtime requirement (e.g. sos.spec was updated to reflect this).

Are there any distributions shipping sos for python2 today that either do not ship `python2-futures` or don't have that dependency properly defined?

**Comment by xueweiz** [comment]
Oh right, I forgot that python2 only has 1.5 years lifetime. Yeah now I agree that probably indicating python2-futures dependency on README would be the way to go.

And to answer your question, I'm working on [Container-Optimized OS](https://cloud.google.com/container-optimized-os/docs/concepts/features-and-benefits), and we only ship a minimum Python2 in the base image. The thing is we are a locked-down OS like Redhat Atom or CoreOS, so there is no package manager either.
But we can choose to include the library in our OS :)

Also I believe for most distros, python2-futures is not included in the base image by default. User will have to install them via pip. I tested this on Redhat, Debian 9 and Ubuntu 16, and they all requires user to install the library first.

**Comment by TurboTurtle** [comment]
I can't speak for other distros, but it's in the base repo for Fedora and if you check out the RHEL 7.6 Beta you'll see it's available now as well, as python-futures.

If there are other py2-only distros though that don't have python(2)-futures at all, that's a bit different and we should definitely provide some kind of fallback. @bmr-cymru thoughts? @battlemidget what's the situation for Ubuntu?

**Comment by bmr-cymru** [comment]
I wouldn't mind reviewing a patch to implement this, however it's not going to be a priority for the main sos team for the reasons that Jake explained - all modern distributions that still include Python 2 by default are shipping the `concurrent-futures` package for their Python 2 environments - this means that it should just be a case of packaging dependencies to pull in the requirement, unless you need to work with a very old distribution (e.g. in Red Hat terms that means RHEL6 or earlier - an eight year old platform at this point).

> Also I believe for most distros, python2-futures is not included in the base image by default. 

Well, sure, but that's the case for a great many packages in all distributions. We even include the necessary `Requires: python-futures` dependency declaration in the example SPEC file in the source tree. You may need to modify the names to suit a particular distro (depending on whether Python 2 or Python 3 has the `pythonX` / `pythonX-foo` suffixing), but this shouldn't be a great difficulty for even an experienced system administrator.

Otherwise, you can just use the distribution provided `sos` packages - these should be available on all the distros you mention and insulate you from the complexity of handling changed requirements in the upstream sources.

> But we can choose to include the library in our OS :)

Surely your images are built with a package manager framework? Otherwise how are you ensuring any depdendencies are satisfied? So long as you declare the deps in the `sos` package build everything is automatic and required leaf packages will be pulled in as needed.

**Comment by bmr-cymru** [comment]
> If there are other py2-only distros though that don't have python(2)-futures at all, that's a bit different and we should definitely provide some kind of fallback.

Names, versions & dates please ;)

I would be very surprised if there are existing non-commercial distros that are still in support and that lack this package. RHEL6 is one example, but we have not supported it (without patching) for a long time - first for `six` and now several other later deps (which are increasingly difficult to patch out - hence our RHEL maintainer's decision to no longer rebase the sos version in that release).

For commercial platforms it's best to contact the vendor since even if you do find a way around the deps, it is possible that this will violate support terms.

**Comment by bmr-cymru** [comment]
> I would say that fallback to single could work!

Anything "could work", but this is non-trivial. You need to catch the failing imports, and then either mock or shim every object/interface that we call from the affected module. Considering we still have some open problems with the concurrency support I don't think this is a high priority area of focus.

**Comment by xueweiz** [comment]
> I wouldn't mind reviewing a patch to implement this, however it's not going to be a priority for the main sos team for the reasons that Jake explained
I agree, and I think it make sense to have the python-futures requirement, and ask each user/distro to have it as dependency. Implementing the falling-back patch may not be trivial, and seems not justify the cost.

Thanks for the suggestion all!
