### ISSUE TITLE
[rpm] Sos report list of installed packages and sorts it with -f

### ISSUE THREAD

**Issue by iranzo** [sosreport/sos#1184]
Example:

~~~
$ grep ^kernel- installed-rpms
kernel-3.10.0-514.16.1.el7.x86_64                           Thu May  4 17:11:30 2017
kernel-3.10.0-693.11.6.el7.x86_64                           Tue Jan  9 12:26:12 2018
kernel-3.10.0-693.2.2.el7.x86_64                            Wed Sep 20 17:32:23 2017
kernel-devel-3.10.0-514.16.1.el7.x86_64                     Thu May  4 18:10:42 2017
kernel-devel-3.10.0-693.11.6.el7.x86_64                     Tue Jan  9 12:26:29 2018
kernel-devel-3.10.0-693.2.2.el7.x86_64                      Wed Sep 20 17:31:22 2017
kernel-headers-3.10.0-693.11.6.el7.x86_64                   Tue Jan  9 12:26:15 2018
kernel-tools-3.10.0-693.11.6.el7.x86_64                     Tue Jan  9 12:26:06 2018
kernel-tools-libs-3.10.0-693.11.6.el7.x86_64                Tue Jan  9 12:26:05 2018
~~~

If I do search for kernel it fails to report latest version at latest number (rpm seems to use sort -f as per https://github.com/sosreport/sos/blob/master/sos/plugins/rpm.py#L48)

It should allow to quickly search for latest version by just tailing on the last item (ideally version installed vs date)

**Comment by pmoravec** [comment]
Nice catch, very easy to over-look mis-sorted list.

So `s/sort -f/sort -V/` in rpm.py#L48 would be a fix, am right? (works well on the above "testing data")

**Comment by iranzo** [comment]
Hi Pavel,
In the citellus plugin I did use the sort -V and I get this output:

[piranzo@collab-shell ~]$ echo "kernel-3.9.0-001.1.12.el7.x86_64" >> installed-rpms 


[piranzo@collab-shell ~]$ grep kernel installed-rpms 
erlang-kernel-18.3.4.5-3.el7ost.1.x86_64                    Wed Oct  4 10:08:20 2017
kernel-3.10.0-514.16.1.el7.x86_64                           Thu May  4 17:11:30 2017
kernel-3.10.0-693.11.6.el7.x86_64                           Tue Jan  9 12:26:12 2018
kernel-3.10.0-693.2.2.el7.x86_64                            Wed Sep 20 17:32:23 2017
kernel-devel-3.10.0-514.16.1.el7.x86_64                     Thu May  4 18:10:42 2017
kernel-devel-3.10.0-693.11.6.el7.x86_64                     Tue Jan  9 12:26:29 2018
kernel-devel-3.10.0-693.2.2.el7.x86_64                      Wed Sep 20 17:31:22 2017
kernel-headers-3.10.0-693.11.6.el7.x86_64                   Tue Jan  9 12:26:15 2018
kernel-tools-3.10.0-693.11.6.el7.x86_64                     Tue Jan  9 12:26:06 2018
kernel-tools-libs-3.10.0-693.11.6.el7.x86_64                Tue Jan  9 12:26:05 2018
kernel-3.9.0-001.1.12.el7.x86_64

[piranzo@collab-shell ~]$ grep kernel installed-rpms |sort -V
erlang-kernel-18.3.4.5-3.el7ost.1.x86_64                    Wed Oct  4 10:08:20 2017
kernel-3.9.0-001.1.12.el7.x86_64
kernel-3.10.0-514.16.1.el7.x86_64                           Thu May  4 17:11:30 2017
kernel-3.10.0-693.2.2.el7.x86_64                            Wed Sep 20 17:32:23 2017
kernel-3.10.0-693.11.6.el7.x86_64                           Tue Jan  9 12:26:12 2018
kernel-devel-3.10.0-514.16.1.el7.x86_64                     Thu May  4 18:10:42 2017
kernel-devel-3.10.0-693.2.2.el7.x86_64                      Wed Sep 20 17:31:22 2017
kernel-devel-3.10.0-693.11.6.el7.x86_64                     Tue Jan  9 12:26:29 2018
kernel-headers-3.10.0-693.11.6.el7.x86_64                   Tue Jan  9 12:26:15 2018
kernel-tools-3.10.0-693.11.6.el7.x86_64                     Tue Jan  9 12:26:06 2018
kernel-tools-libs-3.10.0-693.11.6.el7.x86_64                Tue Jan  9 12:26:05 2018
[piranzo@collab-shell ~]$ 


So it looks like it solves the issue for me.


Is it ok If I do submit patch for this?

Regards,
Pablo

**Comment by bmr-cymru** [comment]
I'm not _that_ keen to change this, because it is very old: it predates `sos` entirely (it's taken straight out of `sysreport`).

Our normal guidance to users who have particular expectations on the sorting of data found in reports is to carry out the sorting themselves on the archive data. We have been explicitly _not_ sorting new sources of data (unless there is some very good/exceptional reason to do so) for a long time now.

Sorting and filtering is such a trivial task on UNIX like systems (and is also highly dependent on locale and local convention) that we have tended to back away from imposing any particular convention on our users.

**Comment by bmr-cymru** [comment]
(also, bear in mind that even with this change, analysts cannot blindly tail files without previously checking the version of sos that was used to generate the report - the old formats will still persist in the wild for some time).

**Comment by iranzo** [comment]
Right, in our case, we'll be defaulting to sorting it 'again' to get the data we want, but it's the same as many other files that have changed in the past like pacemaker/cluster folders, etc.

As we already sort here, the idea was to use more natural sorting for the future, even if in the meantime we cannot rely on it until everyone is updated.

Just let me know if a patch is finally wanted and I'll try to submit for your review once the relevant discussion has taken place

**Comment by bmr-cymru** [comment]
Like I said: I'm not _that_ keen on it, i.e. I'm not going to go out of my way to make it happen, but there's still room for you to convince me ;-)

Really, what I'd be looking for here is some kind of a check to make sure that nobody is relying on this in any way - since this is all strictly RedHatPlugin work it doesn't need to involve the Debian or Ubuntu folks - even just a headsup mail to sos-devel about your plans, and a (separate!) mail to one of the Red Hat internal support stakeholders lists would be sufficient.

**Comment by iranzo** [comment]
Email sent to sos team, now going for the devel one

**Comment by bmr-cymru** [comment]
👍

**Comment by iranzo** [comment]
PR created: https://github.com/sosreport/sos/pull/1185

**Comment by iranzo** [comment]
Discussion thread on <https://www.redhat.com/archives/sos-devel/2018-January/msg00000.html>

**Comment by pmoravec** [comment]
The list *looks like* already sorted (and technically it is), so a user might easily expect it is NVR-sorted as well. Since that sorting has much more sense here..

Taking into account that:
- the change is relevant to `rpm`-based systems only
- no feedback in the sos-devel mailing list from Red Hat
- no idea how much sosreport is used on Fedora (I guess much less than in RHEL)

I dont expect any objections from users. So +1 for the change.
