### ISSUE TITLE
[bug] "kubernetes.podlogs=on" can't get logs of pods

### ISSUE THREAD

**Issue by alicealvy** [sosreport/sos#1189]
# sosreport -k kubernetes.podlogs=on

the result  can't get logs of pods, please look the link  https://github.com/sosreport/sos/blob/master/sos/plugins/kubernetes.py#L116-L122
something is wrong.

**Comment by pmoravec** [comment]
That code is evidently wrongly block-aligned:

- it is executed under `if self.get_option('all'):` only (is this intentional?)
- it refers to variable `knsp` that is set inside a loop `for n in knsps:` while this wrong code is executed *outside* that loop. So this code gets assigned `knsp` from the latest loop execution (or an exception is raised if loop isnt executed at all)

I dont know when "podlogs" should be collected, under what scope. @TurboTurtle , can you have a look, please?

**Comment by TurboTurtle** [comment]
Ah, been a while but I remember what's going on here. The `kubectl logs` command only works for the current namespace that `kubectl` is executing in unless it is explicitly set like `kubectl --namespace=test logs mypod`, so we have no way to get pod logs without the namespaces explicitly set.

So realistically what we should be doing here is re-arranging the block so that we get the list of namespaces regardless, and then separately check for the `all` or `podlogs` options.

I can work something out shortly for this.

**Comment by TurboTurtle** [comment]
There was another problem with pod logs collection I found, also resolved with the above PR.
