### ISSUE TITLE
[make rpm]make rpm filed on debian 7.11

### ISSUE THREAD

**Issue by lovemrd** [sosreport/sos#1232]
Hi all,
   I clone the sos repository, make && make install on the debian 7.11 successfully. However, there are so many other machine want to install this tool, and I am try to  make rpm. There are two issues:
   1) Failed build dependencies error reported, which has already installed.
 `rpmbuild --define "_topdir %(pwd)/dist-build" --define "_builddir %{_topdir}" --define "_rpmdir %{_topdir}" --define "_srcrpmdir %{_topdir}" --define "_specdir %{_topdir}" --define "_sourcedir %{_topdir}" -tb dist-build/sos-3.3.tar.gz
error: Failed build dependencies:
	python-devel is needed by sos-3.3-1.noarch
	gettext is needed by sos-3.3-1.noarch
	python-six is needed by sos-3.3-1.noarch
make: *** [rpm] Error 1
root@pubbeta2-nova12:/tmp/sos# dpkg -l | grep python-dev
ii  python-dev                                   2.7.3-4+deb7u1                         all          header files and a static library for Python (default)
root@pubbeta2-nova12:/tmp/sos# dpkg -l | grep gettext
ii  autopoint                                    0.18.1.1-9                             all          The autopoint program from GNU gettext
ii  gettext                                      0.18.1.1-9                             amd64        GNU Internationalization utilities
ii  gettext-base                                 0.18.1.1-9                             amd64        GNU Internationalization utilities for the base system
ii  libgettextpo0:amd64                          0.18.1.1-9                             amd64        GNU Internationalization library
ii  liblocale-gettext-perl                       1.05-7+b1                              amd64        module using libc functions for internationalization in Perl
root@pubbeta2-nova12:/tmp/sos# dpkg -l | grep python-six
ii  python-six                                   1.6.1-1                                all          Python 2 and 3 compatibility library (Python 2 interface)
`
2) After comments these three BuildRequires in sos.spec file, it still can't build successful.
`make[2]: Leaving directory `/tmp/sos/dist-build/sos-3.3/docs'
make[1]: Leaving directory `/tmp/sos/dist-build/sos-3.3'
+ /usr/lib/rpm/find-lang.sh /tmp/sos/dist-build/BUILDROOT/sos-3.3-1.x86_64 sos
+ /usr/lib/rpm/brp-compress
+ /usr/lib/rpm/brp-strip /usr/bin/strip
+ /usr/lib/rpm/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/brp-strip-comment-note /usr/bin/strip /usr/bin/objdump
Processing files: sos-3.3-1.noarch
error: File not found by glob: /tmp/sos/dist-build/BUILDROOT/sos-3.3-1.x86_64/usr/lib/python2.7/dist-packages/*
Executing(%doc): /bin/sh -e /var/tmp/rpm-tmp.zz64D6
+ umask 022
+ cd /tmp/sos/dist-build
+ cd sos-3.3
+ DOCDIR=/tmp/sos/dist-build/BUILDROOT/sos-3.3-1.x86_64/usr/share/doc/sos-3.3
+ export DOCDIR
+ /bin/mkdir -p /tmp/sos/dist-build/BUILDROOT/sos-3.3-1.x86_64/usr/share/doc/sos-3.3
+ cp -pr AUTHORS README.md LICENSE /tmp/sos/dist-build/BUILDROOT/sos-3.3-1.x86_64/usr/share/doc/sos-3.3
+ exit 0

RPM build errors:
    File not found by glob: /tmp/sos/dist-build/BUILDROOT/sos-3.3-1.x86_64/usr/lib/python2.7/dist-packages/*
make: *** [rpm] Error 1
`
I has checked this directory, "site-packages" is the only dir in xxx/usr/lib/python2.7/.

Am I miss something?  Can you give me some suggestion. Thanks!

Zhu Yijun

**Comment by bmr-cymru** [comment]
We do not currently support cross-distro builds. To proceed with the current builds you should carry this build out in a chroot, container, or virtualised environment (for example using a tool like 'mock' to prepare and maintain the chroot and to carry out the build actions).

The problem you are hitting is because the RPM .spec file used by `make rpm` is desgined for Red Hat distros: it hard-codes Red Hat paths like `site-packages` (vs. `dist-packages` on Debian) and will not work for a Debian build without modification: even so, you would then generate an RPM package that can only work on Debian, which is not really very useful.

You may also like to try using the Python `distutils` based builds: these provide alternate mechanisms to build source and binary distribution packages and they may work better for your use cases (although cross distro builds with these tools are still untested and not officially supported).

Generally we would be happy to review and accept patches that improve this and that would allow us to offer these build types as a supported feature.

I'm also a bit curious however: since sos is already in Debian, Ubuntu, Fedora, RHEL, CentOS (and possibly others), why not just use those pre-built packages for your systems?

**Comment by lovemrd** [comment]
@bmr-cymru

**Comment by lovemrd** [comment]
@bmr-cymru , thanks for you info. Actually, I can't find pre-built packages for debian 7(debian 8, 9 can be found), can you give me a link? By the way, why the "make deb" not supported?  Or is there a plan to support it,

**Comment by bmr-cymru** [comment]
Debian 7 is probably before sos was included: in that case, you are probably best finding the source .deb for Debian 8 or 9 and attempting to rebuild that for Debian 7. I can't offer much help as I rarely use Debian systems these days, but perhaps the Ubuntu and Debian folks can chime in. @battlemidget @karibou ?

**Comment by BryanQuigley** [comment]
Debian 7 isn't supported anymore, so I couldn't find info on it. 

I'm going to go ahead and close this Issue -  feel free to reopen if you want to work on cross-building.
