### ISSUE TITLE
[plugin] automatic size limiting for add_copy_spec() and add_cmd_output()

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#1325]
If no size limit is specified (`is None` - `0` should still be permitted to disable size limits completely) automatically set both file and command size limits to the current value of `--log-size`.

**Comment by bmr-cymru** [comment]
Part of the command size limiting patch from  @TurboTurtle  (#1120) enables this, but only for commands: I've split that off from the main patch for now, and will keep it on a branch with a similar change for file contents until we've agreed on the approach for this for 3.6.

**Comment by TurboTurtle** [comment]
I (somewhat obviously) completely agree with making this change - while I understand the option is *log*-size, there should be some form of command output limiting default and to me it makes the most sense to tie both log and command size limiting to the same option.

The most obvious use-case for this is `journalctl` output. For the system journal, or for the `docker` journal when containers are printing to stdout, these can be huge in size (several GB), when a support engineer really only needs a small portion of that. What might not be immediately obvious is this also holds true for `docker logs` output which captures everything a container has sent to stdout, which for numerous applications can be as large as the journal. This significantly increases the archive size needlessly, and using `--log-size` as the default provides 1) a nice user experience and 2) means we don't need to comb through the plugins and manually pick out potentially problematic commands and assign `sizelimit`s individually.


I canvas'd the RH support folks a while back on this, and the general consensus was that while they agreed "log-size" implies only log files would be limited, the preferred behavior would be to limit command output as well. Specifically, journals were called out since those *should* be considered log files even if sos has to capture them as command output.

**Comment by bmr-cymru** [comment]
Yeah. I have so far failed to come up with any name that is better than `--log-size`; `--data-size`, `--output-size` etc. are too general: about the only one I could think of is ``--size-limit` (which at least reflects the code side...), but I am not sure it is worth messing with our interface again just to make this more consistent.

One thing we probably ought to do is to go through plugins to see if anything was relying on the default `sizelimit=None` to capture large amounts of data: I can't think of anything right now, but that would break with these changes unless the plugin is changed to pass `sizelimit=0` explicitly.

**Comment by bmr-cymru** [comment]
Yeah, journals just make the whole thing completely schizo :-)

One option would be to add `--size-limit` as a synonym for `--log-size`, deprecate `--log-size` and then drop it in a major version or two's time.

**Comment by TurboTurtle** [comment]
I think `log-size` is still fine, we just need to document it applies to commands as well (the pedantic side of me could argue that any of the files we write could be considered "log" files :wink: ). I think `--size-limit` could be confused to mean "limit the sos archive to this size".

**Comment by bmr-cymru** [comment]
But another pedant could equally assert that they are demonstrably _not_ log files ;) Either one has  drawbacks, and needs to be clearly explained in the documentation. We just need to try to find the least-worst.

**Comment by bmr-cymru** [comment]
(equally a sufficiently creative user could interpret `--log-size` to mean the size of the logs generated by `sos`, i.e. `sos_logs/sos.log` et al. - finding one confusing interpretation doesn't necessarily rule anything out. We cannot eliminate confusion in the UI, we can just try to minimise it as much as we can).
