### ISSUE TITLE
New threads functionaility doesn't work if --config-file unspecified

### ISSUE THREAD

**Issue by BryanQuigley** [sosreport/sos#1333]
If I have a file /etc/sos.conf
$ sudo ./sosreport
....
Traceback (most recent call last):
  File "./sosreport", line 19, in <module>
    main(sys.argv[1:])
  File "/home/bryan/git/sos/sos/sosreport.py", line 1695, in main
    sos.execute()
  File "/home/bryan/git/sos/sos/sosreport.py", line 1670, in execute
    self.collect()
  File "/home/bryan/git/sos/sos/sosreport.py", line 1285, in collect
    self.plugpool = ThreadPoolExecutor(self.opts.threads)
  File "/home/bryan/git/sos/sos/sosreport.py", line 549, in threads
    return self._threads
AttributeError: 'SoSOptions' object has no attribute '_threads'

Whereas if I specify it sudo ./sosreport --config-file /etc/sos.conf
....
It works fine.

**Comment by BryanQuigley** [comment]
I did try just adding
    _threads = 4
to class SoSOptions(object) in sosreport.py

which fixes it, but somehow messes up formatting output (all plugins on single line)...

**Comment by TurboTurtle** [comment]
Huh. So this is a trivial fix:

```
diff --git a/sos/sosreport.py b/sos/sosreport.py
index 75e33e83..71984d32 100644
--- a/sos/sosreport.py
+++ b/sos/sosreport.py
@@ -225,6 +225,7 @@ class SoSOptions(object):
     _sysroot = None
     _chroot = 'auto'
     _compression_type = 'auto'
+    _threads = 4
 
     _options = None
```

But what I'm surprised at is I only see this behavior when I run from master. If I run from the feature branch the PR was made from, sosreport runs normally, even though as far as I can tell no other recent commits touched anything that the threads commit touched.

```
$ git branch
  atomic-info
  atomic-rpm
  block-udev
  buildah
* concurrent
[...]
$ sudo ./sosreport --batch

sosreport (version 3.5)

 Running plugins. Please wait ...

  Starting 1/98 : abrt            [Running: abrt]
  Starting 2/98 : alternatives    [Running: abrt alternatives]
  Starting 3/98 : anaconda        [Running: abrt alternatives anaconda]
  Starting 4/98 : anacron         [Running: abrt alternatives anaconda anacron]
  Starting 5/98 : ansible         [Running: abrt alternatives anaconda ansible]
  Starting 6/98 : apache          [Running: abrt alternatives ansible apache]
[...]
```

Similarly, this behavior wasn't seen in the Travis tests.

**Comment by TurboTurtle** [comment]
@BryanQuigley more odd behavior: if you add `_threads = 4` and run with `--batch` the formatting is correct.

**Comment by BryanQuigley** [comment]
We explicitly call out the local sos.conf file in travis because one doesn't exist in the host.

It actually works totally fine (without any code changes) if you specify --batch, --build, -a, --case-id or -v.  So maybe this only occurs with a bare sosreport run?

**Comment by TurboTurtle** [comment]
Ah. Got it.

```
diff --git a/sos/sosreport.py b/sos/sosreport.py
index 75e33e83..b7871100 100644
--- a/sos/sosreport.py
+++ b/sos/sosreport.py
@@ -229,10 +229,7 @@ class SoSOptions(object):
     _options = None
 
     def __init__(self, args=None):
-        if args:
-            self._options = self._parse_args(args)
-        else:
-            self._options = None
+        self._options = self._parse_args(args)
 
     def _check_options_initialized(self):
         if self._options is not None:
```

Since `threads` should default to 4, we need to pass even an option-less commandline invocation through `parser.parse_args()` in `SoSOptions()`, which would otherwise be `args` being nothing.

This also takes care of the weird formatting behavior if another option isn't set. This change effectively makes ensures that `self._options` will never be False, so this stuff becomes irrelevant:

```python
    @property
    def threads(self):
        if self._options is not None:  <====
            return self._options.threads
        return self._threads
```

But since the work for option presets (#1323) gets rid of all of this anyways, I think the irrelevancy of those bits can be ignored until presets are pulled into master.

**Comment by BryanQuigley** [comment]
Yea, that makes sense if it's planned for 3.6, it's trivial to workaround.. literally any option does it.

**Comment by TurboTurtle** [comment]
Alternative change, that still allows `args` to be `None` while formatting the plugin output correctly:

```
diff --git a/sos/sosreport.py b/sos/sosreport.py
index 75e33e83..a839dacd 100644
--- a/sos/sosreport.py
+++ b/sos/sosreport.py
@@ -211,7 +211,7 @@ class SoSOptions(object):
     _log_size = 10
     _batch = False
     _build = False
-    _verbosity = 0
+    _verbosity = None
     _verify = False
     _quiet = False
     _debug = False
@@ -225,6 +225,7 @@ class SoSOptions(object):
     _sysroot = None
     _chroot = 'auto'
     _compression_type = 'auto'
+    _threads = 4
 
     _options = None
```

**Comment by bmr-cymru** [comment]
Need to look at this in more detail later, but the patch that deletes the optional arg handling isn't right - that's intended so that an `SoSOptions` object can be initialised by an API user.

Anyway, as already noted, this is kinda all moot anyway, although I find the later diff a bit curious - at first glance it seems quite a big change to address this, but I've probably missed something for now.

**Comment by BryanQuigley** [comment]
Output formatting is still compressed on a bare run, but otherwise it runs from fix in 1336

**Comment by TurboTurtle** [comment]
I assume by 'compressed' you mean the output line is refreshed with the latest plugin being started, rather than a newline being printer?

That's how it previously printed assuming you don't increase the verbosity at all. If you're getting newlines with a bare 'sosreport' run, it's because your terminal size is lower than 90 columns - which we use because line lengths can get up to 86 characters with certain plugins running concurrently.

**Comment by BryanQuigley** [comment]
Correct on compressed. My terminal size doesn't change between these two runs:

Bare run: https://pastebin.ubuntu.com/p/FWjRDN6rmw/
Run with --batch, but any option will do.  It's also the default I've seen usually: https://pastebin.ubuntu.com/p/KsFRHsHwHH/

**Comment by TurboTurtle** [comment]
Ah, ok - I see whats going on.

The 'compressed' output is because `verbosity` is set to 0 by default and we aren't changing that at all. So the refreshing output line is what's expected, and is what was the behavior in previous releases[1]

With `--batch`, I'm seeing `verbosity` being `None`, so it prints the newline per:

```python
    def ui_progress(self, status_line):
        if self.opts.verbosity == 0:
            status_line = "\r%s" % status_line.ljust(90)
        else:
            status_line = "%s\n" % status_line
```

The concurrency addition moved this bit to the new `ui_progress()` but the logic has been that way for several releases at least.

That being said - I don't think this should actually be considered an issue. I would think an end-user running a bare `sosreport` command would prefer the refreshed output line rather than newlines, and keeping `--batch` such that does print newlines is something I personally prefer. 

[1] now, the above being as it is, I'm curious as to why you're getting newlines on your bare run. I'm getting what I would say is the expected behavior on F28:

```
Please enter the case id that you are generating this report for []: 

 Setting up archive ...
 Setting up plugins ...
 Running plugins. Please wait ...

  Finishing plugins              [Running: selinux]                                       
  Finished running plugins                                                               
Creating compressed archive...

Your sosreport has been generated and saved in:
  /var/tmp/sosreport-terra-2018-06-18-zsdmyaf.tar.xz

The checksum is: f5b602641ac68fd60da7ae3331726607

```

**Comment by BryanQuigley** [comment]
I'd be sold if it was just --batch, but literally any option I try causes it to print a newline every time.   Try -n kernel for instance.

I don't really have a preference between them, just think it should be consistent.

[1] Re the bare run, I'm guessing the first two plugins can finish running before the others start (I've actually seen it also say Finished then go to the next one, but can't reproduce easily).

Now I get https://pastebin.ubuntu.com/p/MjH7SgnZnR/ on runs..

**Comment by BryanQuigley** [comment]
And please ignore that last pastebin.. I messed up and ran the locally installed sosreport.

Here is my current one - https://pastebin.ubuntu.com/p/s4Hr72SWX8/.  I think acpid just runs really fast..  On Ubuntu it just copys less than 1kb of files.

**Comment by BryanQuigley** [comment]
If you want to see the Finished running plugins message more, try setting threads to 2.

**Comment by TurboTurtle** [comment]
#1354 should resolve the `Finished running plugins` issue, and the newlines when there are no currently running plugins when we start collecting a new plugin (like your acpid example)

For resolving the "any option gives newlines" problem, where `verbosity` gets set to `None`, we can fix this with:

```
diff --git a/sos/sosreport.py b/sos/sosreport.py
index 4ef9abcb..4d5e5258 100644
--- a/sos/sosreport.py
+++ b/sos/sosreport.py
@@ -605,7 +605,7 @@ class SoSOptions(object):
                             dest="build", default=False,
                             help="preserve the temporary directory and do not "
                                  "package results")
-        parser.add_argument("-v", "--verbose", action="count",
+        parser.add_argument("-v", "--verbose", action="count", default=0,
                             dest="verbosity", help="increase verbosity")
         parser.add_argument("--verify", action="store_true",
                             dest="verify", default=False,
```

If we want `--batch` to still use newlines rather than refreshing (which I also like and think we should keep), the fix theoretically should be as simple as:

```
@@ -1358,7 +1358,7 @@ class SoSReport(object):
             self.handle_exception(plugname, "collect")
 
     def ui_progress(self, status_line):
-        if self.opts.verbosity == 0:
+        if self.opts.verbosity == 0 and not self.opts.batch:
             status_line = "\r%s" % status_line.ljust(90)
         else:
             status_line = "%s\n" % status_line
```

The above, together with #1354 should fix both of the odd newline vs refreshed line issues you're seeing - mind confirming on your end before I open another PR for the verbosity/batch change?

**Comment by BryanQuigley** [comment]
All looks good from me.  Thanks!

**Comment by BryanQuigley** [comment]
All looks good to me now, thanks!
