### ISSUE TITLE
[rpm] "rpm -Va" to run with bigger timeout

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#1369]
`rpm -Va` is run only conditionally under `rpm.rpmva` option marked as slow, with 180 seconds timeout. That might not be sufficient for some/many systems.

If the command does really require more time on a usual system (or usual system when sosreport is requested to collect it, i.e. when we suspect some relevant issues), it is worth increasing the timeout.

Some stats from 4 my systems:

- 2m7s for a system with 551 packages
- 0m40s for a system with 643 packages
- 4m28s for a system with 1071 packages
- 11m25s for a system with 831 packages (some older RHEL6, might not be much relevant)

**Comment by bmr-cymru** [comment]
I'm tempted to think that as the user has to ask for it (and should know what to expect), that we run this command without timeout, or with something huge. It would still be helpful in the case of a genuinely stuck `rpm` process, but the problem is that "huge" is a relative term when the time is a function of both system performance and the installed package workload.

**Comment by jcastill** [comment]
The max timeout we have in sos is in the foreman plugin, with two commands having 600s  timeout. It may not be enough still, so perhaps a 12 minute timeout may cover this?
