### ISSUE TITLE
[Openshift] Collect output of oc describe node

### ISSUE THREAD

**Issue by crackcodecamp** [sosreport/sos#1466]
Red Hat insights AIR tool is used to detect any issue exists with checking the content of sosreport. For the OpenShift part, it is necessary to check the description of all nodes. That's why need to collect a description of all nodes including master.

**Comment by TurboTurtle** [comment]
This would probably go into the `kubernetes` plugin rather than origin, since `nodes` is a shared resource.

That being said, currently `describe <resource>` output is gated behind the `kubernetes.describe` option. We'd have to do this in a separate loop (since nodes are not namespaced, and the resources we collect descriptions for are namespaced) anyways, but I'm wondering if it should be a default collection or if it should also be gated behind that option?
