### ISSUE TITLE
apt source credential should be filter out.

### ISSUE THREAD

**Issue by ycheng** [sosreport/sos#1514]
1. need to filter out /etc/apt/auth.conf
2. need to filter out user:password in /etc/apt/sources.list and /etc/apt/sources.list.d/*

**Comment by TurboTurtle** [comment]
The first point should be a non-issue as we add that as a forbidden path.

As for the second - @slashdd @arif-ali @BryanQuigley would you be able to take a look?

**Comment by arif-ali** [comment]
On top of `/etc/apt/auth.conf`, we may also want to filter out `/etc/apt/auth.conf.d/*`

A lot o the repositories in private PPAs instruct users to add lines in `/etc/apt/sources.list` or in `/etc/apt/sources.list.d/*`, similar to the line below

```
deb https://<username>:<password>@private-ppa.launchpad.net/some-folder/sub-folder/ubuntu bionic main
```

Typically, the syntax for the auth.conf is as below, but it seem based on the [man page](https://manpages.ubuntu.com/manpages/bionic/man5/apt_auth.conf.5.html), it can have other forms too

```
machine private-ppa.launchpad.net/some-folder/sub-folder/ubuntu
login <username>
password <password>
```

* Now, it depends for the auth.conf files, if we just want to obfuscate the files, or remove them completely. If I was supporting a customer, I would prefer to obfuscate the file, so that I know that some credentials are being used for a specific repository.
* From the sources.list, it would make sense to obfuscate both the username and the password
