### ISSUE TITLE
[plugins] add_cmd_output can not collect "java -version"

### ISSUE THREAD

**Issue by NaNi-Z** [sosreport/sos#1542]
add_cmd_output can not collect "java -version". stderr=True is not work. But "python -V" is fine.

java's version is openjdk1.8

need help,thanks.

**Comment by bmr-cymru** [comment]
What does the command (`jave -version`) print when run in the terminal?

On Fedora with `java-1.8.0-openjdk-headless-1.8.0.171-3.b10` I see:

```
$ java -version
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-b10)
OpenJDK 64-Bit Server VM (build 25.171-b10, mixed mode)
```

It is also helpful to include the `sos` version, distribution name, and distribution version when reporting this kind of problem to the project.

**Comment by bmr-cymru** [comment]
> stderr=True is not work

What do you mean by this? Please show an example.

**Comment by NaNi-Z** [comment]
@bmr-cymru thanks.
I can't get any output by sos, the output file is empty. In the terminal the output is same as yours.  
The "java -version"'s output is stderr stream, the function's arrgument stderr=True is not work. But "python -V" is work.
Is it relate to $PATH? add_cmd_output does not find java command. I found that it can not get $PATH by sos too.

**Comment by bmr-cymru** [comment]
Where is the `java` binary installed on your system, and from where did it come? (i.e. a distribution RPM or DEB package, a tarball/zipfile, or some other installation method).

**Comment by NaNi-Z** [comment]
# which java
/usr/local/java/bin/java

Java installed by our own scripts, I don't know the detail.

**Comment by bmr-cymru** [comment]
We don't currently execute commands that are outside the system-defined `PATH` for the distribution. This includes paths in the `/usr/local` tree, since often executables here shadow the system-provided version, leading to confusing information - since `sos` is a *support* tool, this is the behaviour that most of our users currently want.

Note that even without the `PATH` issue, the standard `java` plugin will not collect much useful data for you - it is designed to collect information from the system-provided Java instance(s), using data from `/etc`. Note that it also does not collect the `"java -version"` command that you are interested in anyway.

You could do that in your own plugin, but it would be quite hacky - you would need to modify the `PATH` and then re-set it afterwards. Alternately you could write or modify a `Policy` class to set this for you, but that is a larger set of changes.

Anyway, it's not really clear to me what you are trying to achieve, or the relation to the plugins that `sos` provides - the tool has a plugin model, and that is driven by the active distribution policy, and the set of packages installed on the system. If you are not installing Java from a package then you will need to add your own plugins to cope with that configuration.

**Comment by NaNi-Z** [comment]
All right, thanks for help.
