### ISSUE TITLE
Discuss collecting binary journal files instead of journalctl output commands

### ISSUE THREAD

**Issue by BryanQuigley** [sosreport/sos#1547]
This would be much faster to collect - just copying files (and less duplicated effort between output).  But we need to determine how we would want to pick the files in question.

**Comment by bmr-cymru** [comment]
Instinctive NACK from me - we can't filter them, we can't strip secrets from them, when a report is unpacked on a web server etc. they cannot be browsed - I am sure there are even more reasons not to do this, but I am definitely not in favour.

**Comment by pmoravec** [comment]
Another reason against: if binary files structure depends on journald version, one has to have installed same/equivalent journald version to explore the binary data locally.

Like collecting raw `sa*` data instead of `sar*` files, where the structure of binary files changed in some `sysstat` version so older format cant be opened on newer package version and vice versa.

(also I am not sure if binary data collection allows the same filtering we have now, but I can be wrong)

**Comment by bmr-cymru** [comment]
> Another reason against: if binary files structure depends on journald version, one has to have installed same/equivalent journald version to explore the binary data locally.

I believe it's intended to be stable and uses versioning and compatibility flags in the on-disk headers. There is also the Journal JSON Format, and JEF (Journal Export Format) that we could consider if there were a good reason to collect the data in a lower-level format.
