### ISSUE TITLE
Manual installation on Amazon Linux 2

### ISSUE THREAD

**Issue by thimslugga** [sosreport/sos#1563]
I've attempted to install sosreport via manual installation on Amazon Linux 2. After installing the app is unable to find any of the plugins. Is there anything else that needs to be done or configured to allow it to use the plugins that come with the source?

**Comment by TurboTurtle** [comment]
Could you clarify what you mean by 'manual installation' Did you run `make install` or are you doing something else?

In any case, usually these types are problems are plugins not being _enabled_, not being unfindable.

Most of the plugins today are enabled by the presence of certain packages and the discovery of those packages is controlled via the sos `policy` which maps to distributions and thus package managers. Currently we do not have a policy for Amazon Linux, so that's likely at least related to the problem.

If you run `sosreport -e <some list of plugins>` are they able to run?

**Comment by thimslugga** [comment]
I've tried via make install, make rpm and installing rpm and via pip install sosreport. Running sosreport -e with various plugins name from /usr/lib/python2.7/site-packages/sos/plugins results in the error "a non-existing plugin ($plugin_name) was specified in the command line"

**Comment by TurboTurtle** [comment]
Ok, yeah that is almost guaranteed to be because we don't have an Amazon Linux policy.

In short, a policy identifies the system as a specific distribution, specifies a package manager to use, and is then also used to "tag" which plugins are suitable to run on such a distro.

The policy itself is easy enough to write, but that would still leave us with the task of tagging applicable plugins for the distro. E.G. which plugins can run on the distro, and which can run but need some modification in order to collect useful information based on the distro-specific configuration/deployment of the component the plugin collects data for (for example, most of our plugins have separate classes for Red Hat and Debian/Ubuntu distros, since the same component has different log/config files, package names, etc... between them).

We ideally would need to have someone committed to identifying the relevant plugins, and updating them for Amazon Linux as needed as well as maintaining the policy.

**Comment by thimslugga** [comment]
I had a feeling it was related to the policies. Thanks for the shedding some light on the "tagging" as it helped me to wrap my head around how sosreport works.

**Comment by bmr-cymru** [comment]
We'd be open to a supported port to Amazon Linux, but there's no work on that to date that I'm aware of.

**Comment by bmr-cymru** [comment]
(since Amazon Linux is based on RHEL this shouldn't be a massive effort - chances are it can re-use the `RedHatPlugin` tag, unless they have made incompatible changes in core components).

**Comment by TurboTurtle** [comment]
@thimslugga I've created a policy for Amazon Linux. It seems to work, but I'd appreciate it if you (or anyone else) would try it out and verify it grabs what you're looking for.

https://github.com/TurboTurtle/sos/tree/amazon-linux

Since Amazon Linux is a RHEL clone, I've left it as accepting the base `RedHatPlugin` tagging class so any plugin that runs for RHEL _should_ run for it as well.

If that branch above looks good to you, I'll open a PR to bring it in.

**Comment by thimslugga** [comment]
@TurboTurtle nice, just tested with the new policy on both AL1 and AL2 and it worked fine.
