### ISSUE TITLE
[sosreport] [rfe] grab logs since date

### ISSUE THREAD

**Issue by valleedelisle** [sosreport/sos#1673]
That would be great to have a `--since` switch when using --all-logs. When using `--all-logs`, we often see very large sosreport archive when we only need the recent events.

`--since` switch should only prevent archived (.gz) files from being added, otherwise we would be missing files that aren't updated often.

`--since` should also be passed to `journalctl`

**Comment by TurboTurtle** [comment]
I like the idea, would require #1586 to get merged.

We'd need to talk about how we'd expect end users to use `--since` though. Do they supply a date? If so, what date format? Should we instead just specify a number of days back to collect from? E.G `--since 7`  (or maybe `--since-days 7` to make it a little more obvious?)

**Comment by valleedelisle** [comment]
@TurboTurtle and I discussed this issue offline and he proposed that `--since` should also work without `--all-logs`. I think it's a very legit recommendation and will certainly implement/test this in a near future but I would like to see `--since` added as soon as possible. Some customers are making pressure for something like this.

**Comment by valleedelisle** [comment]
And here's the merge request https://github.com/sosreport/sos/pull/1677/

**Comment by bmr-cymru** [comment]
Let's keep all the discussion on this change in one place: #1677
