### ISSUE TITLE
[general] sosreport collects some logs three times

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#1714]
The same log entry can be collected by:

- collecting `/var/log/messages*`
- calling `self.add_journal(boot="this", catalog=True)`
- calling `add_journal` by some particular plugin

That means sosreport archive can have the same data stored up to three times.

I was thinking if we can limit this in some way, but:
- we need to copy `messages*` files for legacy reasons
- collecting whole journal is meaningful and imho we shall not skip collecting journal entries we collect in different plugins separately - we would lose chronological ordering of all events
- collecting separate journal units is welcomed

The only way we can improve is collecting `/var/log/messages*` only when not collecting journal logs?

**Comment by TurboTurtle** [comment]
I don't think we can skip collecting `/var/log/messages` if we collect the journal because a number of components still log to that file and don't log to the journal. Granted, a good percentage of those are probably things that sos doesn't have plugins for, but having the messages log can help point support engineers to the fact that there is an issue in, for example, a third party/in-house application rather than with the OS or one of the components that OS ships/supports.

With our size limiting in place, I don't think this is too much of an issue any more with duplicate logs. If a component is spamming a certain log file (such as messages) to the point of making it basically useless, we have the other collection points (i.e. the whole journal and unit journals with larger default sizes) to fall back on without needing user intervention. I think the place this is really an issue is when `--all-logs` is used, but at that point the user is literally telling us "give me everything and size-limiting protections be damned" - so we're giving users exactly what they're asking for; everything on the system, which includes duplicated info that lives on the host anyways.

**Comment by TurboTurtle** [comment]
Closing this as I believe it is handled by recent changes to the `logs` plugin and how we collect the journal and/or `/var/log/messages`
