### ISSUE TITLE
[plugins] Iterator over add_cmd_output

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#1720]
Background: plugins have frequent constructions like:

    items = self.get_cmd_output("command items list")
    if items['status'] = 0:
       # iterate over the output, fetch IDs of items and get_cmd_output for each of them

Those constructions appear repetitively in the plugins. And they often bring issues to plugin timeouts when some such plugin iterates over a huge list of items. Particular examples I am aware of:

https://github.com/sosreport/sos/blob/master/sos/plugins/docker.py#L81
https://github.com/sosreport/sos/blob/master/sos/plugins/docker.py#L90
https://github.com/sosreport/sos/blob/master/sos/plugins/docker.py#L93
https://github.com/sosreport/sos/blob/master/sos/plugins/networking.py#L202
https://github.com/sosreport/sos/blob/master/sos/plugins/networking.py#L224

(other candidates not yet seen as timeouting: podman, networkmanager, kubernetes, composer or block)

I think there is no need to collect **all** such details for **all** hundreds or thousands of entries, esp. if collecting so prevents to collect some other unique data due to timeout. It is reasonable to have some limit here, in general.

It could be beneficial to have that construction in `plugins` class directly, with benefits:
- simplified code in a plugin
- ability to (even by default) limit number of items we iterate over. Either by items or maybe by time ("start collecting items details with timeout of 60 seconds", e.g.).

Negs of the limit: we can skip collecting some important item details that is over the limit - maybe to support a whitelist to preferably collect first?

Your thoughts?

**Comment by TurboTurtle** [comment]
My only concern with something like this is the inability to provide a generic-enough way to limit the collection without being clunky in terms of user experience.

For example with the container-centric plugins there is simply no way to know by default which of, let's say 1000, images are important to get `$runtime inspect` output for. Our only choice then is to provide a plugin option - however making users craft regexes to match image names isn't something I want to do here, much less request a customer to do in a support case.

We can't limit to an arbitrary number of images (E.G. "collect the first 500 of these images") either since the images are returned non-deterministically.

I like the idea of a baked-in iterator for `add_cmd_output`, but the practicality of using it with a whitelist is fairly low in my opinion.

**Comment by pmoravec** [comment]
Applying the limitations to "first X" or potential white lists will be optional, I understand it might not fit all use cases.

(anyway, can't collecting too many images details from container-centric plugins make them timeout? what should be the best default sosreport behaviour, then? It's a dilema..)

**Comment by pmoravec** [comment]
Sounds good to me. I will prepare a PR for this for the above plugins that can utilize the API change.
