### ISSUE TITLE
[sar] when to collect "sar -A" and "sadf -x"?

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#1741]
Since b3d9fdf, sosreport collects whole sar log dir but runs `sar -A` and `sadf -x` only on `sa[0-9][0-9]` files. That is some kind of inconsistency as files like `sa20190730` - even with the current date for that there is no human readable `sar` file present yet - are ignored for the `sar -A` / `sadf -x` commands.

A natural idea is "we should call the commands to each and every `sa*` file other than `sar*` (or an archive?). And at least for the most recent file without `sar` equivalent, it makes a lot of sense.

It has no sense for e.g. year old `sa` data, and it makes no sense to compressed archives.

Orthogonal to this, there is a question if sosreport should call `sar`/`sadf` commands at all. On one side those commands just reformat already collected binary data to some human readable format(s). That slows down each and every sosreport execution while being used sometimes only. Any user can call the same on his/her system as well when needed. On the other side, such a need slows down the user much more, esp. since one needs equivalent version of `sysstat` on the system.

Esp. due to the `sysstat` different formats of binary data, I would vote here to call the `sar`/`sadf` commands. I dont have strong preferences if we should call the commands on all collected `sa` files or just e.g. newest 30 ones or all. (maybe call on latest 31 what would be a new plugin option?)

Your thoughts?

**Comment by ins-pirat-ion** [comment]
> Orthogonal to this, there is a question if sosreport should call `sar`/`sadf` commands at all.

Imho should, given the binary data are not portable.

Introduce new option (all / last x days) + sane default (31) sounds good to me.

**Comment by jcastill** [comment]
31 days as default sounds good, but if it is too much data, 7 days could be another default - I have never seen a case where the issue happened more than a week before the data was collected, and if that happens, we can use a new option as proposed by Filip, so we can get what we need. 

> Orthogonal to this, there is a question if sosreport should call sar/sadf commands at all. On one side those commands just reformat already collected binary data to some human readable format(s). That slows down each and every sosreport execution while being used sometimes only. Any user can call the same on his/her system as well when needed. On the other side, such a need slows down the user much more, esp. since one needs equivalent version of sysstat on the system.

What about calling sar/sadf for 'today', 'yesterday' from the time the sosreport is being created, and collect X days of raw data (31 or 7, whatever the default). And then, have a new option as well where if you explicitly call for Y days instead of the default, the sosreport will call sar/sadf on them, because we are asking explicitly for these files, so surely we need the binary output as well.
