### ISSUE TITLE
Incorporate black for defining the styleguide

### ISSUE THREAD

**Issue by adam-stokes** [sosreport/sos#1835]
I've had a lot of success using https://pypi.org/project/black/ it works great out of the box and could reduce one more thing to worry about when reviewing PR's.  Just a thought, open for discussion on possibly incorporating this into travis with (`black --check`) and requiring code submitters to run this as part of their PR submission guidelines.

**Comment by bmr-cymru** [comment]
I'd not played with Black before - I installed it yesterday and started taking a look at how it behaved for some of my projects. Generally I like what it does, although there are cases where I'm not so keen on the result - e.g. method/function declarations with lengthy arg lists where Black will place one argument per line.

I feel a bit like using black is an all-or-nothing thing: either you standardise your style to conform with what Black does, or it's tricky to use the tool without layering on hacks to selectively apply the formatting changes it comes up with.

E.g. I have some tables in a project I maintain that have been hand-formatted for readability - although I like what Black does to the style of most of the project source, I'm a bit concerned that the handling of these tables leads to code that's harder to read and change correctly:

Original:

```python
#: Report object type table for ``boom.command`` reports.
_report_obj_types = [
    BoomReportObjType(
        BR_ENTRY, "Boot loader entries", "entry_", lambda o: o.be),
    BoomReportObjType(
        BR_PROFILE, "OS profiles", "profile_", lambda o: o.osp),
    BoomReportObjType(
        BR_PARAMS, "Boot parameters", "param_", lambda o: o.be.bp),
    BoomReportObjType(
        BR_HOST, "Host profiles", "host_", lambda o: o.hp)
]
```

Gets blackened to:

```python
#: Report object type table for ``boom.command`` reports.
_report_obj_types = [
    BoomReportObjType(
        BR_ENTRY, "Boot loader entries", "entry_", lambda o: o.be
    ),
    BoomReportObjType(BR_PROFILE, "OS profiles", "profile_", lambda o: o.osp),
    BoomReportObjType(
        BR_PARAMS, "Boot parameters", "param_", lambda o: o.be.bp
    ),
    BoomReportObjType(BR_HOST, "Host profiles", "host_", lambda o: o.hp),
]
```

So the elements are in a different place visually on each line, where the original placed them in a way that was less consistent rule wise but in a way that's arguably more visually consistent and easier to read.

The worst example of this kind of change I've noticed while playing with Black and sos so far is the command line arguments table (OK, it's not really a table, but it's a sequence of method calls which previously looked and acted a lot like a table when it comes to making changes).

Before:
```python
    parser = ArgumentParser(usage=usage_string)
    parser.register('action', 'extend', SosListOption)
    parser.add_argument("-a", "--alloptions", action="store_true",
                        dest="alloptions", default=False,
                        help="enable all options for loaded plugins")
    parser.add_argument("--all-logs", action="store_true",
                        dest="all_logs", default=False,
                        help="collect all available logs regardless "
                             "of size")
    parser.add_argument("--since", action="store",
                        dest="since", default=None,
                        type=_format_since,
                        help="Escapes archived files older than date. "
                             "This will also affect --all-logs. "
                             "Format: YYYYMMDD[HHMMSS]")
```

After:
```python
    parser = ArgumentParser(usage=usage_string)
    parser.register("action", "extend", SosListOption)
    parser.add_argument(
        "-a",
        "--alloptions",
        action="store_true",
        dest="alloptions",
        default=False,
        help="enable all options for loaded plugins",
    )
    parser.add_argument(
        "--all-logs",
        action="store_true",
        dest="all_logs",
        default=False,
        help="collect all available logs regardless " "of size",
    )
    parser.add_argument(
        "--since",
        action="store",
        dest="since",
        default=None,
        type=_format_since,
        help="Escapes archived files older than date. "
        "This will also affect --all-logs. "
        "Format: YYYYMMDD[HHMMSS]",
    )
```

Its definitely not awful, and maybe I only look at it as a negative because I'm used to how this has been done for so long (tbh most of my other projects that use `ArgumentParser` look very similar to the original sos formatting so I'm definitely biased).

I think we should get some opinions from the other regular contributors and distro maintainers before we make a final decision here - I'm currently trying black out on a few other projects and I'm kinda on the fence about it.

**Comment by TurboTurtle** [comment]
I'm on the fence as well, but leaning towards 'no'. It makes a few opinionated choices that I like. However, the ones I don't like I absolutely hate.

In Bryn's example, I see something that is particularly harmful to readability:

```python
    parser.add_argument(
        "--since",
        action="store",
        dest="since",
        default=None,
        type=_format_since,
        help="Escapes archived files older than date. "
        "This will also affect --all-logs. "
        "Format: YYYYMMDD[HHMMSS]",
    )
```

With this style, I would assume the last two strings in that `add_argument()` call would be separate arguments, rather than continuations of the `help` definition. The no-longer-indented continuation style really throws me off, but this is compounded by the fact that python does not allow for non-kwargs to follow kwargs - so I'd constantly be catching myself on this while glancing over any bit of code that gets changed to this.

**Comment by bmr-cymru** [comment]
That's what bugs me... Fwiw, for the most part, I absolutely agree with its opinionated opinions :-)

E.g.:

```
    some_lengthy_list = [
        "with some very very very very very very very long",
        "members"
    ]
```

Is just how I've been encouraging people to write things for years.

But this:

```
    some_lengthy_list_of_tuples = [
       (
            "with some very very very very very very very long",
            "members"
       )
    ]
```

Not so much... and what it does to the `ArgumentParser` block is definitely unhelpful as @TurboTurtle explained. It's a pity as for the most part I really do like it - just for making string quoting consistent, for e.g., but it seems like taking the good and leaving the bad would involve a lot of manual futzing about right now.

It might help if it supported the kind of pragmas we used to use with `pylint` to disable specific style changes (although maintaining that was a bit of a rabbit hole itself).

**Comment by TurboTurtle** [comment]
As there has been no further movement on this, or anything that overcomes the problems noted above where this is actually hindering readability, I'm going to close this out.

If this changes in the future, feel free to re-open this issue.
