### ISSUE TITLE
vendor_url for ubuntu/canonical

### ISSUE THREAD

**Issue by slashdd** [sosreport/sos#1869]
Most distros are either entreprise (redhat) or community driven (centos/fedora), making the difference distinct. In Ubuntu world, community/entreprise is the same 'ubuntu'.

I was thinking to add a `community_url` in `policies/__init__.py` to separate both identities.

so that we could use in `policies/ubuntu.py` something like this:

```
    distro = "Ubuntu"
    vendor = "Canonical"
    community_url = "http://www.ubuntu.com/"
    vendor_url = "http://www.canonical.com/"
```

so that the initial msg would be something like this and represent both the community and the  entreprise side of Ubuntu:
```
This command will collect system configuration and diagnostic
information from this Ubuntu system. An archive containing the collected
information will be generated in /tmp/sos.01_7rtwc.

For more information on Canonical visit:

  http://www.ubuntu.com/ ==> community_url
  http://www.canonical.com/ ==> vendor_url

The generated archive may contain data considered sensitive and its
content should be reviewed by the originating organization before being
passed to any third party.

No changes will be made to system configuration.

Press ENTER to continue, or CTRL-C to quit.
```

**Comment by slashdd** [comment]
@cjohnston1158 @BryanQuigley

**Comment by TurboTurtle** [comment]
Is there no difference in a deployed host between community Ubuntu and commercial? Like some sort of release string or packaging difference that the `Ubuntu` policy could check and then set `vendor_url` appropriately?

**Comment by slashdd** [comment]
There is no significant difference that would be accurate enough to be triggered. It's essentially the same thing, there is no "Entreprise" Ubuntu. Ubuntu is ubuntu regardless if you pay or not for support.

**Comment by slashdd** [comment]
Just to be clear, I don't want this to become a sale pitch "if you want to buy support go here" kind of like, but just to make sure that our customer or potential future customer knows that there is a Canonical presence maintaining/approving sosreport.

**Comment by TurboTurtle** [comment]
Yeah, that's totally understandable.

It has been quite a few years since I played around with Ubuntu in any fashion so I wasn't sure if there was anything users needed to do to "transition" their systems from community to commercial support (e.g. like subscribing a system as RH does).

I think it would be a better approach to make `vendor_url` a tuple, rather than adding more `*_url` class attrs so that we have a standard way to list an arbitrary number of URLs a Policy wants to display. Then in `Policy.get_msg()` we'd just need to do something like this (not tested, just spitballing):

```python
        _msg = self.msg % {'distro': self.distro, 'vendor': self.vendor,
                           'vendor_url': "%s\n".join(u for u in self.vendor_url),
                           'vendor_text': self.vendor_text,
                           'tmpdir': self.commons['tmpdir']}
```

**Comment by bmr-cymru** [comment]
I guess my main reservation about adding this would what to set it to for other distributions - it's kinda hard to map:

  * SuSE has SLES and OpenSuSE
  * Red Hat has RHEL, Fedora, CentOS
  * Debian has multiple commercial support offerings, but none that it would be fair to call out
  * Things like PowerKVM and ZKVM as well as Amazon don't have an obvious split here

I can think of two options that might work as a compromise here: we could define separate `vendor_url` (a link to who made this thing), and `support_url` (a link to where you can get support - whether commercial or not), although I'm not sure that would be broad enough for what Ubuntu wants - community users presumably would want to find a link to the community support forums rather than Canonical's commercial offerings.

Failing that then extending the suggestion from @TurboTurtle we could replace `vendor_url` with `vendor_urls`, and have it be something like a list of 2-tuples with a description and a link:

```
[('For commercial support please visit:',
  'https://www.canonical.com'),
 ('For information on community support resources please visit:',
  'https://ubuntu.com/support/community-support')]
```

Then policies can define as many URLs as they need to, along with the description (and with `mailto:` or other less common URI types if they need to - e.g. this could include dropbox/upload information for the distros that offer those kinds of services).

**Comment by bmr-cymru** [comment]
So e.g. the `rhel` policy could link to https://www.redhat.com as a generic "For more information..." with a second link to https://access.redhat.com (the commercial support portal).
