### ISSUE TITLE
Implement xsos in sos natively?

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#1985]
In recent past, I got few requests / ideas to implement xsos natively in sos(report). xsos is a "light-weighted sosreport" to print system status or summary to terminal (only). Source code available at https://github.com/ryran/xsos, package to download at https://people.redhat.com/rsawhill/rpms/latest-xsos.rpm .

On one side, there is a bigger overlap between the two tools and as `sos` is more spread, users requiring `xsos` could get on systems with `sos` without the need to install "3rd party tool" `xsos`.

On the other side, implementation in `sos` (as e.g. `status` sub-command, or inside `report`?) might be tricky but doable:
- having it as a separate sub-command allows more flexibility (even to bundle `xsos` as is, e.g., though it is `bash` and not `python` script?)
- having it as an option of `sos report` can utilize the implemented framework, where we would "just" need to:
  - identify what plugins cover the "general info" commands from `xsos`
  - in those plugins, have the ability to collect just the specific commands
  - have a preset(?) that enables just those plugins and restrict to the selected commands (via plugin options?)
  - implement printing output info
  - optionally, remove the tarball or generated directory (`--build` option set by default?) to hosekeep after the run (but it can be valuable to store the collected data, too)

I think it would be doable, would need reasonable small amending current code, and it can be welcomed by users. Just not sure 1) who or when could implement it, and 2) does this feature belong under the `sos` umbrella or isnt it a step aside?

Cc @ryran @ptalbert and @superjamie as `xsos` main contributors.

**Comment by bmr-cymru** [comment]
I don't think `xsos` is a "lightweight sosreport" as you describe - rather, it's a summariser that formats data from reports for display on the terminal. I think it's the kind of thing we might want to consider in the new `sos <command>` design, either as a separate command or some extension to `sos report` (to display the results of a previously generated report).

**Comment by TurboTurtle** [comment]
This was the goal of the `examine` subcommand detailed in the 4.0 RFC. Summarize the data in an sos report. The idea would be to run against an existing sos report on the filesystem, but it could also certainly be used at the end of a successful `report` run - we just need to chain the subcommands.

**Comment by bmr-cymru** [comment]
Ah that's right, we even defined a verb for it already ...

**Comment by pmoravec** [comment]
Right, the "lightweight sos" was not good shortcut, it does not store any data.

I think the main benefit of `xsos` is its very short running time - within 5 seconds. That is why I elaborated on the topic "how to implement a lightweighted run of sosreport to collect just limited data like `xsos` needs". Are we interested in having *this*? To provide some limited summary data within seconds?

**Comment by TurboTurtle** [comment]
The problem xsos has is in _large_ datasets that it reads in for processing. This has more to do with it being bash than anything else - and it's something python excels at. In one of the very early versions of pysos, what would take xsos 30 seconds to crunch, pysos only needed a few seconds at most.


So this is definitely doable and I don't think it's all that difficult. If we implement as a truly separate subcommand (IE not just adding a `summarize()` method to plugins and calling that instead of our existing collection mechanisms), I think we gain some nice chaining ability. For example we could run `sos report --clean --summarize` which would then, in turn:

* Generate a report
* Run it through `soscleaner` sanitization
* Generate some summary output
* Add that summary to the archive


As for a "lightweight" run, I'm not sure that's really something we should focus on. Users can already make sosreports "lightweight" via `--disable-plugins`, `--log-size`, etc....

**Comment by pmoravec** [comment]
But how much sense it has to sosreport to collect e.g. journal logs or `ip netns` for all namespaces, if an user wants just a summary? Shall not we have at least e.g. preset that would disable automatically collecting unwanted data? Users wont recall what plugins for a summary are needed and what are redundant..

From my experience, `sosreport` runs usually from 1 to 10 minutes. `xsos` runs few seconds.

**Comment by pmoravec** [comment]
I think there is some misunderstanding in capabilities of `xsos`. In past, I *think*, it was able to *summary* only data from a given sosreport. Now the tested latest upstream bits show it can run the commands and store data for runtime, in case no sosreport archive provided. So running plain `xsos` on a system provides a summary of its current status, really.

**Comment by bmr-cymru** [comment]
So I think the question then becomes: "Is xsos a sufficiently widely used/ubiquitous tool for sos users that we should copy the interface/functionality, or do we just set out on our own track and do our own thing wrt summarisation/presentation?"

**Comment by TurboTurtle** [comment]
OH, you're talking about _local_ runs of xsos, I understand now.


I'll just say that I don't think sos needs to implement that style of functionality. The overwhelming majority of xsos users, to my knowledge, are support engineers that are looking at an open case for some technical support organization. Local runs aren't particularly useful for them, as they'll always be groking through some collection of sosreport(s) of end user/customer systems.


I think we should make our 4.0+ work for examine focus on archive summarization. If we get a bunch of requests for local, live summary data then we can extend it at that time, and everyone can take great joy in quoting this comment to me as a big "told you so" ;-)


> or do we just set out on our own track and do our own thing wrt summarisation/presentation?

I think it's more on this side of things, while taking cues from the stance xsos takes on some things as guidelines for what does/does not work.

**Comment by mikelolasagasti** [comment]
For me `sos` is the tool to collect data and another tool ([`xsos`](https://github.com/ryran/xsos/), [`Insights`](https://github.com/RedHatInsights/insights-core), [`sos_analyze`](https://github.com/waldirio/sos_analyze), [`Citellus`](https://github.com/citellusorg/citellus), ...) should be the one that has to work on top of the collected data. Having a cleaner function like `soscleaner` integrated would have more value as it is related to data capturing. 

Also, having xsos has no dependency on a system and it easier to remember `xsos sosreport/` than `sosreport examine sosreport/`.

**Comment by superjamie** [comment]
I also see all these tools as having different scope.

sosreport is the data collector, it runs the time-expensive commands which provide output and it stores that output. Other tools mentioned above then operate on that collected output.

The reason xsos provides fast output is that it's running on the data already collected by sosreport. xsos is a bunch of bash and awk doing text processing. That 1-10 minutes of data collection work still needs to be done somewhere. Currently it's done by sos. 

Whilst xsos *can* run live commands, that's not the primary use. As far as I know, xsos is used almost entirely within Red Hat and Canonical for retrospective analysis of already-collected sosreports. I'm not even sure live xsos is that useful.

If one relied on live analysis to "pretty print" the output of running commands every time, then that output would take as long as the commands take. So the suggested `sosreport display` functionality might take 10 minutes anyway.

So yes, the question is the scope of sos. Does sos want to just be a data collector? Or does sos also want to be a data displayer? If so, which data will it display, or will sos implement a kitchen sink across all of them? Will sos operate only on already-collected sosreport, or will it also/only provide live display?

I am not overly attached to the xsos output format. It's definitely not to any standard and we could change it anytime if someone comes up with something better. I am interested in making the output easily human-readable, however that is done best.

**Comment by BryanQuigley** [comment]
Just to add, Canonical has some requirements to examine data provided to us with some level of protection.  That's why we run some of our analysis in lxd containers (ScoutPlane automated the extracting of sosreports, running of xsos, and getting it in a good state for further analysis).  

Any thoughts on what container tech is long term supported by both RH and Canonical?  K8S seems like overkill for this, containerd?   Once we go down the route of parsing data in sosreport like this, I feel like we need be very security concious.

**Comment by TurboTurtle** [comment]
I think that the security of data and its availability (or lack thereof) is on end users, rather than `sos` directly. I.E., sos having the _ability_ to read and present data in a specific fashion is, in my mind, completely divorced from the control and access to that data.

> Any thoughts on what container tech is long term supported by both RH and Canonical? K8S seems like overkill for this, containerd?

For RH, it's podman for standalone and Openshift Container Platform for multi-node/orchestration, and that's it. We stopped shipping/supporting docker on RHEL 8 - it can obviously still be installed and run, but we don't provide support for it and actively encourage users to migrate to podman.

> Once we go down the route of parsing data in sosreport like this, I feel like we need be very security concious.

I think our security focus starts and ends with obfuscation of sensitive data during collection. That can be simply scrubbing passwords, keys, etc via plugins like we do today - or extended to network obfuscation via the proposed integration of `soscleaner`. Anything beyond that would be an organizational decision for the orgs that use `sos` for customer support.

For `examine`, we would only be presenting data already in a particular archive - so if one is able to parse the data via `sos`, then you also already have all the required access to see the data we're presenting. Our concern with `sos` should be on making sure that source is scrubbed of sensitive data where needed at collection time.

**Comment by BryanQuigley** [comment]
Sos examine will be reading and parsing a lot of data from an unverified source. Both RH and Canonical allow anyone to buy support.   We want to make sure new customer X can't craft a malicious  sosreport that can compromise a machine.

**Comment by TurboTurtle** [comment]
I'm going to close this out now, reasoning in the comment previous to this one.

If anyone would like to revisit this, or alternatively kickstart a new repo under the `sosreport` GH org for this kind of project, please feel free to reach out to me or the rest of the team on IRC, by direct email, or the mailing list (sos-devel@redhat.com).
