### ISSUE TITLE
We should add System Event Log (SEL)  collection method into sos

### ISSUE THREAD

**Issue by SamLeeXinhua** [sosreport/sos#2015]
Normally, System Event Log (SEL) which addressed by IPMI spec can provide more detail for a platform.
I would suggest that we should also add System Event Log (SEL)  collection method into sos.
For example, we can add "ipmitool sel list" and "ipmitool sel list -vv" into sos. So, when we collect sos logs, we can also collect SEL logs if the platform has BMC which implements IPMI spec. This SEL can provide great help when debuging reboot/shutdown issues.

Regards,
Sam

**Comment by TurboTurtle** [comment]
We already grab `ipmitool sel list` via the `ipmitool` plugin.

https://github.com/sosreport/sos/blob/master/sos/report/plugins/ipmitool.py#L34


Are you saying this output includes something we should parse to grab other log files on the system?

**Comment by jmcvaughn** [comment]
I do wonder if it makes sense to use `ipmitool sel elist` as opposed to `ipmitool sel list`, as this generates more human readable and detailed output in the same format:

```
% ipmitool sel elist
...
  30 | 11/15/2019 | 18:50:40 | Power Unit Pwr Unit Status | Power off/down | Asserted
  31 | 11/15/2019 | 18:50:44 | Power Unit Pwr Unit Status | Power off/down | Deasserted
  32 | 11/15/2019 | 18:50:59 | Management Subsys Health AutoCfg Status | State Asserted | Asserted
  33 | 11/15/2019 | 18:52:23 | Fan Processor 1 Fan | Lower Non-critical going low  | Asserted | Reading 392 < Threshold 392 RPM
  34 | 11/15/2019 | 18:52:24 | Fan System Fan 1 | Lower Non-critical going low  | Asserted | Reading 196 < Threshold 392 RPM
  35 | 11/15/2019 | 18:52:24 | Fan System Fan 1 | Lower Critical going low  | Asserted | Reading 196 < Threshold 294 RPM
  36 | 11/15/2019 | 18:52:24 | Fan Processor 1 Fan | Lower Critical going low  | Asserted | Reading 98 < Threshold 294 RPM
  37 | 11/15/2019 | 18:52:24 | Fan Processor 2 Fan | Lower Non-critical going low  | Asserted | Reading 196 < Threshold 392 RPM
  38 | 11/15/2019 | 18:52:24 | Fan Processor 2 Fan | Lower Critical going low  | Asserted | Reading 196 < Threshold 294 RPM
...
```

```
% ipmitool sel list
...
  30 | 11/15/2019 | 18:50:40 | Power Unit #0x01 | Power off/down | Asserted
  31 | 11/15/2019 | 18:50:44 | Power Unit #0x01 | Power off/down | Deasserted
  32 | 11/15/2019 | 18:50:59 | Management Subsys Health #0x87 | State Asserted | Asserted
  33 | 11/15/2019 | 18:52:23 | Fan #0x36 | Lower Non-critical going low  | Asserted
  34 | 11/15/2019 | 18:52:24 | Fan #0x30 | Lower Non-critical going low  | Asserted
  35 | 11/15/2019 | 18:52:24 | Fan #0x30 | Lower Critical going low  | Asserted
  36 | 11/15/2019 | 18:52:24 | Fan #0x36 | Lower Critical going low  | Asserted
  37 | 11/15/2019 | 18:52:24 | Fan #0x37 | Lower Non-critical going low  | Asserted
  38 | 11/15/2019 | 18:52:24 | Fan #0x37 | Lower Critical going low  | Asserted
...
```

For systems with multiple PSUs, the output will reference which PSU; for this workstation it's perhaps due to it only having one PSU.

`ipmitool sel list -vv` prints the sensor data, raw event data, etc. for each SEL record. This can be used to determine hardware/firmware issues provided that a "decoder" (be that a utility or a document) exists. For example, for Intel's whitebox systems this document exists (https://www.intel.com/content/dam/support/us/en/documents/server-products/SEL_TroubleshootingGuide.pdf), and they have a utility somewhere too.
