### ISSUE TITLE
Request to be maintainer

### ISSUE THREAD

**Issue by slashdd** [sosreport/sos#2066]
I'd like to request access to be a new maintainer of sosreport.

Note that I'm currently a soscleaner maintainer by the force of nature, as I helped @jduncan-rva in a few bugfix, behavioural changes, and Ubuntu/Debian integration as it was originally really RHEL specifics.

I'm also the official maintainer of the sosreport package for both Debian/Ubuntu.

Currently working for Canonical (the company behind Ubuntu) and directly working with Bryan Quigley (active sosreport contributor and maintainer)

For what it's worth my expertise has been recognized in the Ubuntu community as:

- I'm a Ubuntu Core Developer: 
https://wiki.ubuntu.com/UbuntuDevelopers#Ubuntu_Core_Developers

- I'm also part of the Ubuntu DMB (Developer Membership Board) 
It's my 2nd 2-year term voted by the electorate
https://wiki.ubuntu.com/DeveloperMembershipBoard

This make me aware of how things need to reach quorum/consensus with respect of everyone ideas and so on.

As you can see I have sosreport, Ubuntu/Debian and Canonical support best interests at heart.
And I think I can be a good asset along with Bryan Quigley.

My upstream sosreport contributions as of today (excluding ongoing PR):
```
770ac54c [landscape] simplify and remove deprecated log dir
f7469b2f [lxd] Drop db collection and introduce lxd.buginfo
dfc855f8 [maas] Collect journal logs and services status infos
a1577563 [kdump] Switch lsinitrd in favor of lsinitramfs
4a5409df [gdm] gdm3 configuration is found in /etc/gdm3
3657bcbb [kdump] Show current parameters and the saved kexec from last kdump-config load.
31140bdb [canonical-livepatch] Switch to add_service_status method
5659c5f8 [snappy] Check for presence of the snapd pkg instead of its binary
e10473db [Plugin] Detect copy operations without the adequate access rights
19b75c52 [canonical-livepatch] No longer need to hardcode absolute path
77e4c814 [apport] List var crash recursively
c1d1f459 [lxd] Add detection when lxd is installed as a snap.
2afbe9ae [kubernetes] no longer need to hardcode snap path
cd404fe9 [policies] Add PATH for Ubuntu
43feae56 [snappy] check for connectivity to the snap store
a08196b8 [last] split lastlog per UID ranges
1ec2b7b6 [lxd] adapting the plugin to support lxd 3.0.X series
08e87d17 [apache] Add syntax test and runtime status information
71aaa6ac [kubernetes] Enable Ubuntu kubectl cmd from any k8s nodes
5d08c705 [juju] Add detection when juju is installed as a snap.
14cd023e [landscape] Add copy of Landscape OOPS files
c0961f69 netplan conf files can exist in 3 locations
7aa42642 [lxd] Add check for the presence of lxd package
b600776d [sosreport] Fix debian policy PackageManager misusage.
42b25c75 [networking] Add netplan data collection for Ubuntu.
922ea54b [zfs] Add plugin for Ubuntu/Debian
```

**Comment by BryanQuigley** [comment]
Strong +1 from me.  We've worked together for many years now and every internal Canonical sos discussion involves or is lead by Eric.  He also has experience evolving community processes to attack more developers.

**Comment by battlemidget** [comment]
+1 from me, @BryanQuigley hopefully you meant 'attract' more developers :P

**Comment by ddstreet** [comment]
+1 as coworker of @slashdd he has a strong knowledge of sosreport and is highly focused on maintaining and improving it.  He also does excellent work outside of sosreport.  I think he would make a good addition to sosreport maintainers.

**Comment by cjohnston1158** [comment]
+1 - Eric would make a great addition. With his years of Ubuntu development experience he would bring plenty of knowledge and background with him to continue to improve sos.

**Comment by TurboTurtle** [comment]
I think we need to reflect for a moment on what the term "maintainer" actually means with the sos project.

There's the obvious definition of simply someone who has merge rights against master.

To me however, this means the obvious bits of PR review and merges against master (and legacy-3.9), but additionally wearing a project manager hat that in many ways needs to outshine the developer hat. This means defining solid goals, progress tracking, keeping scope creep in check when adding new functionality, and validating design/usability/practicality of changes and additions, among others. In this definition, commiting code is secondary to project direction.

While sos does have an impressive number of contributors to it, the bulk of commits unsurprisingly comes from a very small subset of that list. I don't believe that presence in that subset is necessarily indicative of (upstream) maintainership; if for no other reason than if the main sources of commits all have merge cabilities, we find ourselves in a "too many chiefs" -like scenario. Downstream maintainership is also in my mind a separate thing entirely (as is the case with Fedora - that maintainer is not an upstream maintainer).

Right now, we have effectively 4 maintainers in the sense of "has commit access to master". That's Bryn, Pavel, Bryan, and myself with all of us being aware that Bryn is taking a less active role in the project than in previous years. That means we have 3 people more actively engaged as maintainers that fit within my definition above, and are more-or-less involved in project direction/vision on a (nearly) daily basis (though, _personally_, just because he is taking a less active role I don't discount Bryn from that definition either).

Given either definition of "maintainer", I don't see there being an actual need for additions at this time.

**Comment by BryanQuigley** [comment]
Whether it needs to be "maintainer" or some other definition - I'd like slashd to get pinged for Ubuntu/Debian specific concerns and have "review" power ideally.  I would like us to have more Ubuntu/Debian redundancy in case for example my role changes - or I go on vacation for 2 weeks - I think it's important for dev to not block.

If you'd prefer a trade I think @battlemidget might be Ok with switching to Member.

**Comment by TurboTurtle** [comment]
> I'd like slashd to get pinged for Ubuntu/Debian specific concerns and have "review" power ideally.

As I understand it, GH permissions are not granular enough to allow review authority without write/push permissions as well. The "triage" role allows for management of PRs/Issues in so far as tagging, re-opening/closing, milestones, etc... but to give a review "weight" in a PR, it requires the "write" role.

If that's incorrect and we can get more granular somehow then perhaps we could look at having a "review/triage" sub team, but from what I've dug into so far it does not seem possible (yet?).


> I would like us to have more Ubuntu/Debian redundancy in case for example my role changes - or I go on vacation for 2 weeks - I think it's important for dev to not block.

If your role changes and takes you away from sos work, then we can revisit organization role assignments. For vacation breaks we have 4 others with commit authority to cover merges, and in the many years that sos has been multi-distro we've never gated distro-specific changes to maintainers from that distro or had a real "block" on development continuing. Unless we all decide to go to Maui at the same time to hold SOSConf we shouldn't be blocked on merges.

**Comment by slashdd** [comment]
All good, let's close this request for now and if a need arise, you can count on me. 
Thanks all for the support.
