### ISSUE TITLE
networking plugin timing out if too much net namespace

### ISSUE THREAD

**Issue by slashdd** [sosreport/sos#2092]
It was observed on Ubuntu with a significant amount of ns that sosreport timed out and generate a lot of collection.

```
ls sos_commands/networking | wc -l
2373

ls sos_commands/networking/ip_netns*ethtool*  | wc -l
521
```

Then noticed a few promising parameters enabled in RedHat policy for their Openstack env:
https://github.com/sosreport/sos/blob/master/sos/report/plugins/networking.py#L22-L32
https://github.com/sosreport/sos/blob/master/sos/policies/redhat.py#L204-L207

Will be interesting to add that inside the Ubuntu policy or make those values globally the default for any vendor, and keep the flexibility to vendor to overwrite if any special needs to change the value.

**Comment by pmoravec** [comment]
I mildly agree on making the OpenStack preset a global default value in the `networking` plugin. The positives (prevent plugin timeouts) are for me bit better than negatives (not collecting some info about 201st or 202nd namespace).

Maybe we shall write a warning message when skipping collection of details of a namespace due to this setting? (or is that "too chatty"?)

**Comment by slashdd** [comment]
@BryanQuigley  thoughts ?

**Comment by BryanQuigley** [comment]
I'm +1 for a warning message when it's gone over the limit.  I was thinking it might be better to be more obvious when looking at sos_commands/networking/  but having 200 files there might make it obvious enough?

**Comment by slashdd** [comment]
I'm also +1 on the warning message, anyway `ip_netns `output will continue to reveal to real total number.

**Comment by cjohnston1158** [comment]
I've seen this in a k8s environment, so global would very possibly be best.
