### ISSUE TITLE
make install is broken

### ISSUE THREAD

**Issue by hegdevasant** [sosreport/sos#2096]
make install
mkdir -p /usr/sbin
mkdir -p /usr/share/man/man1
mkdir -p /usr/share/man/man5
mkdir -p /usr/share/sos/extras
mkdir -p /etc
install -m755 sosreport /usr/sbin/sosreport
install: cannot stat 'sosreport': No such file or directory
make: *** [Makefile:50: install] Error 1

Glancing through Makefile it needs couple of fixes as couple of things got re-organized.

- Need to fix sosreport path (bin/sosreport)
- Also location of report/plugins changes 

Also `make rpm` is failing.

-Vasant

**Comment by pmoravec** [comment]
Good finding - that happened during split of `sosreport` to `sos report`, roughly speaking. That causes both your points.

**Comment by hegdevasant** [comment]
Yes.. source code reorg is causing this issue.

Right now I'm bit busy with other stuff. Can you please fix it @pmoravec ?

-Vasant

**Comment by bmr-cymru** [comment]
I think the `make install` fix should be fairly simple (although perhaps it's time to formally deprecate the Makefile based build - we've discussed it a few times).

The RPM build via spec file may be a bit more work due to the need to adjust `%files` lists etc.

For testing purposes I would consider using the `distutils` based build & install in the meantime.
