### ISSUE TITLE
Can we get the "Merged" tag when closing cases?

### ISSUE THREAD

**Issue by BryanQuigley** [sosreport/sos#2105]
I've got numerous feedback that the way we merge PRs leaves people not sure if it was committed or not.

I'm hoping to figure out how to get the PR to show as Merged, but my search foo has failed.

The other option would be to just allow for "simple" commits to use the GH interface which I've setup to only work with a clean rebase and merge.  We can also set it up to require a specific number of approvals and require CI tests always pass, etc.

The negative is we would not be able to add our own Signoff line to those commits (or edit them in any other ways).

**Comment by TurboTurtle** [comment]
The issue comes in that the commit IDs change when rebasing PRs on current master, which is unavoidable when rebasing. We do this to avoid the literal merge commits associated with pulling out-of-sync-with-master branches from other contributors.

Personally, I think having the multiple DCOs from both the contributor and maintainer(s) is more beneficial than the `merged` tag showing on the now-closed PR. The author's original commit message will still be in the history, and the PR gets closed with the linked commit ID that got merged into master, so it's not like we're missing historical data.

Plus, for the contributors who like to track metrics, the GH interface still credits them with the commit as that attribution is taken from the author of the commit message rather than the person who merges.

The best of both worlds would be if GH allowed a 'Merges: #' line similar to the 'Resolves:' and 'Closes:' tags. It might be worth opening a request with GH for that kind of functionality.

**Comment by bmr-cymru** [comment]
The "simple" cases already close with a "Merged" tag (technically the change between the branch in the PR and master is a *fast forward* merge).

The best way to avoid this as a contributor is to keep your branch rebased to master. If a maintainer has to do it for you then they are much less likely to set up the PR branch as a new git-remote and then force push to update it for you.

**Comment by BryanQuigley** [comment]
To be clear I'm speaking about how it shows up in the Github Web UI.

The only ones considered "Merged" by Github are the ones one of the maintainer authored and eventually pushed ourselves.  
Example: https://github.com/sosreport/sos/pull/2074

The vast majority of the Github PRs are marked as Closed:
Example: https://github.com/sosreport/sos/pull/2095

Assuming we don't have to actually edit something, this is just caused by maintainer signing off.  Git already tracks who committed something.

**Comment by stappersg** [comment]
> I've got numerous feedback that the way we merge PRs leaves people not sure if it was committed or not.

Reads to me as
> Got complains about not providing feedback on GH Pull Request. But I'm too humble and too polite to simply say  _Hey I watch the project and you watch your pull requests_

So I don't understand which extra burden is now on the shoulders of @BryanQuigley 

My (unsollicited) advice to him:  Don't bother about providing a service to those who complain about the progress of their PR, they will complain about the service not being perfect.

**Comment by bmr-cymru** [comment]
No, it's not so much about feedback - it's specifically how we merge branches from PRs when they don't apply to the `master` branch as a *fast-forward* merge: it means you don't get the purple "merged" badge on the PR (although the committer who closes the PR should always add a comment indicating the commit that closes the pull request when this is the case).

if you use the GitHub UI, or `git merge` (without rebasing) then you end up with a *merge commit*: a commit object with two parents that "welds" the two trees together by committing the changes needed to apply the branch commits to `master`. Like a lot of projects we don't allow those in the `master` branch because it makes the version history non-linear and harder to follow. When a committer comes to merge a branch into `master`, if it doesn't already apply as a fast forward they will run `git rebase` to re-write the branch so that it does: this changes the commit IDs and breaks GitHub's detection that the branch has been merged.

I think it's possible now for someone with commit access to a project or organisation to also update the PR branch - if that's the case then it should be possible for the person closing the PR to push their changes with `git push --force` so that GitHub is aware of the merge. This would add a few extra steps to the merge workflow for committers so I can't guarantee people will adopt it but it's probably the best technical solution since GitHub doesn't allow manually setting the status to "merged".

**Comment by bmr-cymru** [comment]
On the other hand, if anyone is super keen to have "merged" on their PR there's an easy solution the contributor can apply: just keep your branches aggressively up-to-date with `master` and then it should always be possible for someone with commit access to make a clean fast-forward merge (this is the way the kernel works for e.g., but they have a well-defined merge window for each release).

**Comment by BryanQuigley** [comment]
It's not possible, because we are modifying their commit with the sign-off (so it won't get the merged tag).  It has nothing to do with them being up-to-date with master.

If we are ok not having our sign off line we can get the Merged tag like I just got with this:
https://github.com/sosreport/sos/pull/2165

I can't find anything else wrong with how I committed the above.

**Comment by TurboTurtle** [comment]
I am still of the opinion that the DCO line in the git history is a much greater benefit than the merged tag appearing in the GH web interface.

**Comment by BryanQuigley** [comment]
Committer Name is recorded in the git repo, see:
git log --pretty=format:"%h %s %cn"
```
7644b6d9 [autofs]: obsfucate password in `automount -m` cmd BryanQuigley
73418232 [build] Remove Makefiles from tree Bryan Quigley
fe8c8001 [build] Update specfile and setuptools Bryan Quigley
5d6c5d5d [hyperv] import from proper class Pavel Moravec
b005fdc5 [haproxy] enable the plugin when puppet-generated subdir exists Jake Hunsaker
```

But if you still prefer the DCO, I'll close this.

**Comment by TurboTurtle** [comment]
I previously sent a request to the GitHub team for adding a 'merge/merges/merged' keyword to commit messages like we currently have for 'resolves/closes'. The feedback was to not expect any feedback on if it gets picked up or not. Perhaps if several requests are made for this, it may be more likely to get traction (like any bug reporting platform that has some kind of +1 or "applies to me too" function).

For the moment, I think the committer-adds-dco approach is preferable. I think from a practical standpoint, maintainers force-pushing to PR branches is bound to create headaches since we tend to do merges in batches.
