### ISSUE TITLE
[sos-collector] discussion to use sos report or sosreport

### ISSUE THREAD

**Issue by arif-ali** [sosreport/sos#2214]
Hi all,

Started testing `sos collecter` from 4.0 branch as per @slashdd work on getting sos into Ubuntu

Using the `--verbose`, I noticed that it was using `sosreport` as a command instead of `sos report` as shown below

```
<snip>
[immense-owl:sosreport] Final sos command set to sosreport --batch -c auto 
[arif-laptop:sosreport] Final sos command set to sosreport --batch -c auto
<snip>
```

The first thing that came into my mind is, why are we using `sosreport` when the new sos 4.0 is `sos report`? maybe it's already been discussed

I guess a things to consider why we might to keep `sosreport` or move to `sos report`

* We may want to use `sos collecter` to collect sosreports from machines that have sos 3.9.1 and older (i.e. current stable operating systems)
* We use sos 4.0 version of `sos collect` just for nodes that have sos 4.0, and hence use `sos report ` command
* I guess the decision may come when the `sosreport` command gets deprecated and removed from sos 4.0?

**Comment by TurboTurtle** [comment]
Yeah, the 4.0 detection is on the list - there are a few "gotcha" points where simply changing the initial sos command to `sos report` won't work (these points are in the per-node command formatting and execution bits), but it should all function normally today since `sosreport` is still shipped with the packaging.

The framework is already there to detect sos 4.x, it's just a matter of testing to work out the "gotcha"s. However, we _absolutely_ want to preserve 3.x compatibility.
