### ISSUE TITLE
presets ignore verbosity level

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2289]
sos report --add-preset sostestpreset -vvv -o host --batch --build

should add a preset that also enables debug logs. But:

    sos report --preset sostestpreset

prints just default logs - both to the terminal and to logfile.

Curiously, generated logfile shows:

    2020-11-01 13:59:47,913 INFO: [sos.report:setup] effective options now: --batch --build --log-size 100 --only-plugins host --plugopts apache.log=on --preset sostestpreset -vvv

that is the same like log from

    sos report --preset sostestpreset -vvv

which *does* print the debug logs, both to the logfile and to the terminal output..

**Comment by pmoravec** [comment]
The reason is here: https://github.com/sosreport/sos/blob/master/sos/component.py#L214 just returns cmdline options but does not apply presets like:

https://github.com/sosreport/sos/blob/master/sos/report/__init__.py#L139-L151

Therefore, https://github.com/sosreport/sos/blob/master/sos/component.py#L277 has default verbosity, not updated from the preset.

Worth to put `__init__.py#L139-L151` code into a component method that is executed from there and also newly from `component.py#L214` ?

**Comment by rhdojun** [comment]
Hi Pavel,

I had a look at this today.

To me it looks like verbosity is set correctly and the reason must be something else.

[Report is a Component](https://github.com/sosreport/sos/blob/master/sos/report/__init__.py#L69). So [first it initializes the Components `__init__()`](https://github.com/sosreport/sos/blob/master/sos/report/__init__.py#L123) then continues with its own. The reason it doesn't load the `preset` in the Component's `__init__()` is because [`preset` only exists in the context of a Report](https://github.com/sosreport/sos/blob/master/sos/report/__init__.py#L106). It [does not exist in the context of a vanilla Component](https://github.com/sosreport/sos/blob/master/sos/component.py#L54-L66).

I verified that verbosity is set to three correctly via a [pdb](https://docs.python.org/3/library/pdb.html) interactive debugging session on today's master:

```
> /path/to/sosrepo/sos/report/__init__.py(1344)execute()
-> self.prework()
(Pdb) self.opts.verbosity
3
(Pdb) next
 Setting up archive ...
> /path/to/sosrepo/sos/report/__init__.py(1345)execute()
-> self.setup()
(Pdb) self.opts.verbosity
3
(Pdb) next
 Setting up plugins ...
> /path/to/sosrepo/sos/report/__init__.py(1346)execute()
-> self.collect()
(Pdb) self.opts.verbosity
3
(Pdb) next
 Running plugins. Please wait ...

  Starting 1/1   host            [Running: host]

  Finished running plugins

> /path/to/sosrepo/sos/report/__init__.py(1347)execute()
-> if not self.opts.no_env_vars:
(Pdb) self.opts.verbosity
3
```

As a next step I would look how Options, Plugins and Profiles interact. It might be that somewhere there the verbosity value is gathered from another place and not through the Report's Options.

**Comment by rhdojun** [comment]
There is a handover from the correctly assigned preset opts to a `preset_args` variable [here](https://github.com/sosreport/sos/blob/master/sos/report/__init__.py#L850) and the result of the `to_args()` function is empty. This looks promising to me. Digging deeper into that area.

**Comment by rhdojun** [comment]
That wasn't it. It was just showing how the current status in different opts variables is.

Since tracing through the code gave me no other hints, next I decided to look where loggers actually take over the verbosity and try to dig from there. I didn't do this at first because usually loggers are set up for every class independently and this can become quite time consuming.

But here I was lucky, [there's only one place where verbosity is added to a logger](https://github.com/sosreport/sos/blob/master/sos/component.py#L277).

I'll add a PR with an experiment next to see if I can fix it coming from there.
