### ISSUE TITLE
duplicate work

### ISSUE THREAD

**Issue by vwalek** [sosreport/sos#2302]
Hello,

as much I appreciate the work being done on the openshift plugin [1], I would need to comment that most of the job is redundant, as for OpenShift there is already solution called must-gather, collecting all sort of openshift objects and logs.

However, there are still data which might be collected as part of the sosreport only from specific host, such kubelet logs, etc.
If we could focus on collecting those information, I would be very happy to help you identify the key components to collect.

[1] [https://docs.openshift.com/container-platform/4.6/support/gathering-cluster-data.html](https://github.com/sosreport/sos/blob/master/sos/report/plugins/openshift.py)
[2] [https://docs.openshift.com/container-platform/4.6/support/gathering-cluster-data.html](https://docs.openshift.com/container-platform/4.6/support/gathering-cluster-data.html)

**Comment by TurboTurtle** [comment]
So the openshift plugin was updated in _direct_ collaboration with the openshift support team, specifically to address the shortfalls of must-gather. In particular, the team noted that must-gather archives were burdensome to work with. On top of that, it was also brought up that in many cases the support team continues to ask for sosreports alongside must-gather archives.

The obvious answer there is/was to extend sos to provide the data gathering requirements needed in one pass.

The design of the plugin today makes it easy to collect the cluster-wide information from a master node (you only need to pass the OCP bearer token to sos, or already have `root` able to run `oc` commands), while still gathering node-specific information from the master node it was run on. Using `sos collect` will allow you to gather per-node information from any remaining nodes in the cluster that you want to collect info from (though, now that I write that I realize you would likely need to manually specify nodes since the OCP cluster profile is for 3.x, and I don't believe it would work on 4.x clusters but also haven't tried that personally).

Right now, aside from the OCP resources the plugin gathers the `kubelet` logs and service status, as well as the contents of `/etc/kubernetes` (excluding `.crt` and `.key` files).

As with all plugins, we're always happy to take enhancement requests - so if there's something missing from the current collection, by all means please let us know or submit a PR :)

**Comment by vwalek** [comment]
Hey Jake, I am so happy that you replied so fast and with this big comment. I did not know about the collaboration with openshift support team. 

I would like to add some thoughts:

https://github.com/sosreport/sos/blob/master/sos/report/plugins/openshift.py#L192
-- no longer a valid option for oc, try to remove any `oc cluster` command.

https://github.com/sosreport/sos/blob/master/sos/report/plugins/openshift.py#L195-L196
-- can be ignored if you are collecting `oc clusterversion` as it will hold both information, and `oc status` really doesn't tell much

https://github.com/sosreport/sos/blob/master/sos/report/plugins/openshift.py#L163-L167
-- I see that kubelet logs are collected - my bad. The cert should be collected as it shows as information about the kubernetes. Certificate do not hold sensitive information, so they can be collected by sosreport. 

Could you please also add option to collect `/var/lib/kubelet/` directory to the sosreport. Also, without keys.

Thank you

**Comment by vwalek** [comment]
Also, are you able to send me the collaboration you had with the Openshift support team? Thank you

**Comment by TurboTurtle** [comment]
> https://github.com/sosreport/sos/blob/master/sos/report/plugins/openshift.py#L192
> -- no longer a valid option for oc, try to remove any `oc cluster` command.
>
Ack. Good to know.
 
> https://github.com/sosreport/sos/blob/master/sos/report/plugins/openshift.py#L195-L196
> -- can be ignored if you are collecting `oc clusterversion` as it will hold both information, and `oc status` really doesn't tell much - and it is bound to the current namespace.
> 
Ack.

> https://github.com/sosreport/sos/blob/master/sos/report/plugins/openshift.py#L163-L167
> -- I see that kubelet logs are collected - my bad. The cert should be collected as it shows as information about the kubernetes. Certificate do not hold sensitive information, so they can be collected by sosreport.
> 
Let's cycle around on this. If I remember correctly, these were explicitly highlighted to be skipped.

> Could you please also add option to collect `/var/lib/kubelet/` directory to the sosreport. Also, without keys.
> 
Keys meaning `.key` files, or do the files within that path contain some text we need to obfuscate?

> Also, are you able to send me the collaboration you had with the Openshift support team? Thank you

Sure, I'll get an email thread going.

**Comment by vwalek** [comment]
> Let's cycle around on this. If I remember correctly, these were explicitly highlighted to be skipped.

Yeah, the certificate itself doesn't hold much sensitive information. Without private key, the cert is harmless. It can be collected. The certificates are provided to the other part for verification, so it can be shared.

> Keys meaning `.key` files, or do the files within that path contain some text we need to obfuscate?

Yes, the directory should be similar as `/etc/kubernetes` so there should be some keys and certs. The same as above, the certs should be collected, the key not. The certs are required to check the expiration.

**Comment by sferich888** [comment]
xref: https://bugzilla.redhat.com/show_bug.cgi?id=1899213

**Comment by TurboTurtle** [comment]
Closing this as we've had ongoing discussions with OCP engineering that has resulted in increasing sos adoption and encouraging developers to begin contributing new collections/plugins to sos.
