### ISSUE TITLE
Use of neutral terminology 

### ISSUE THREAD

**Issue by slashdd** [sosreport/sos#2329]
Many project/companies are now or soon considering replacing 'controversial' terminologies such as "master" "slave", "whitelist" "blacklist".

Is it something that sosreport would consider and be mindful about in the future ? 

https://linux.slashdot.org/story/20/07/11/2037250/the-linux-team-approves-new-neutral-terminology

**Comment by TurboTurtle** [comment]
Generally, yes. Going forward we can be mindful of terminology in code.

By the same token though, I don't see it as a high priority item for us to retroactively change code that's already in the project. If someone wants to work on doing so then that's certainly a welcome contribution, but I think prioritizing bug fixes, testing coverage, and items like `sos info` or `sos examine` is/should be our main focus.

One thing I'll highlight here is `sos collect --master foo.bar.example.com`. Off the top of my head I think this is the only user-exposed point with that terminology - we can definitely add alternatives like `--manager` or `--controller` or what have you, but for backwards compatibility we'll need to carry `--master` for at least a few releases with a deprecation message, rather than just outright yanking it out as an option.

**Comment by TurboTurtle** [comment]
Let's make this first step with 4.2 - i.e. let's add an alias (or a few?) for the `--master` option.

I think perhaps `--primary` or `--manager` (borrowing from RHV parlance) would be my personally preferred alternatives, but let's get some suggestions in this thread.

We can also mark 4.2 as the point to make a `master` -> `main` switch with regards to the repo's active branch.
