### ISSUE TITLE
--log-size=0 is silently ignored

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2334]
Reproducer: have a huge `/var/log/messages` and call:

    sos report -o logs --batch --build --log-size=0 -vvv

Then the zero value is lost during:

    [sos.report:setup] executing 'sos report -o host --batch --build -vvv --log-size=0'
    [sos.report:setup] using 'rhel' preset defaults ()
    [sos.report:setup] effective options now: --batch --build --only-plugins host -vvv

and the default logsize limit is applied.

**Comment by TurboTurtle** [comment]
Oof, that's a rough one. Good find though.

This came about because in `Component.apply_options_from_cmdline()` was checking for `if val`. Well in almost all cases that's right, but for `log-size=0` that (now obviously) won't fly. So we can change that to `if val is not None`, which is what _should_ be the null value for anything coming from argparse.

I've opened #2335 for this, let's get some testing on this to make sure we're copacetic with the change.
