### ISSUE TITLE
Collecting of commands output doesn’t work in iscsi plugin on SuSE systems.

### ISSUE THREAD

**Issue by darina-becker** [sosreport/sos#2340]
When Iscsi plugin runs on SuSE (SLES 15) systems it doesn’t collect info about iscsi sessions and other.
Namely it doesn’t collect output of following commands:
"iscsiadm -m session -P 3",
"iscsiadm -m node -P 1",
"iscsiadm -m iface -P 1",
"iscsiadm -m node --op=show"

Logs
```
2020-12-11 14:41:00,403 INFO: [plugin:iscsi] added cmd output 'iscsiadm -m session -P 3'
2020-12-11 14:41:00,404 INFO: [plugin:iscsi] added cmd output 'iscsiadm -m node -P 1'
2020-12-11 14:41:00,404 INFO: [plugin:iscsi] added cmd output 'iscsiadm -m iface -P 1'
2020-12-11 14:41:00,405 INFO: [plugin:iscsi] added cmd output 'iscsiadm -m node --op=show'
2020-12-11 14:41:00,408 INFO: [plugin:iscsi] collecting path '/etc/iscsi/iscsid.conf'
2020-12-11 14:41:00,409 INFO: [plugin:iscsi] collecting path '/etc/iscsi/initiatorname.iscsi'
2020-12-11 14:41:00,410 INFO: [plugin:iscsi] collecting output of 'iscsiadm -m session -P 3'
2020-12-11 14:41:00,428 INFO: [plugin:iscsi] collecting output of 'iscsiadm -m node -P 1'
2020-12-11 14:41:00,446 INFO: [plugin:iscsi] collecting output of 'iscsiadm -m iface -P 1'
2020-12-11 14:41:00,464 INFO: [plugin:iscsi] collecting output of 'iscsiadm -m node --op=show'
```
But `iscsi` folder is missing in sos_commands folder.
When I try to execute these all commands manually they work, print info and exit code is 0.

**What is the reason and how can I fix it?**

I see there are `Iscsi`, `RedHatIscsi` and `DebianIscsi` classes in iscsi.py.
I guessed that base class should collect full info without packages checks in SuSE case, but it doesn’t.

I’ve tried to create additional class which inherits from Iscsi and SuSEPlugin classes. `Setup` method calls `setup` of super class, but it doesn’t work too.

**Comment by TurboTurtle** [comment]
The plugin should be enabled on SUSE systems by use of the `RedHatPlugin` tagging class, since the SUSE policy includes that tagging class (in addition to `SuSEPlugin`.

From your log output we _are_ running the command, so I'm curious as to what is causing the collection to fail.

Is this against current master, or some earlier version of sos as packaged by SuSE?

**Comment by pmoravec** [comment]
Indeed, the commands should been triggered to their execution. Didnt they fail by either way (there were scenarios where python invoking a command without terminal failed, while all other ways of running the cmd succeeded)? What does `sos_reports/manifest.json` report about the commands, esp. `return_code` there?

**Comment by darina-becker** [comment]
@TurboTurtle I install sos via pip using commit hash 3fddddf8ea14436afdffadfb679411e03bf1ec61
@pmoravec I see that all commands have 127 exit code and filepath is null. Iscsiadm placed in /sbin, this path included to PATH env and I run sos by root.

**Comment by pmoravec** [comment]
`sosreport` restricts `PATH`, e.g. for SuSE: https://github.com/sosreport/sos/blob/master/sos/policies/suse.py#L42-L44 . If you temporarily add there also `/sbin`, will `sos` collect the command outputs?

**Comment by darina-becker** [comment]
@pmoravec Yes, now it works. But what is the next? Can I extend this `PATH` for SuSE in another way? Or how to fix it in a legal way?

**Comment by TurboTurtle** [comment]
@darina-becker the policy just needs an update via a PR to the `master` branch that adds `/sbin` to the lines that @pmoravec mentioned. Contributions like that are certainly welcome if you want to open that PR yourself - or we can take care of it.

It's a simple change and since you've already verified it fixes this issue it'd be a quick merge. Then all you'd need to do is rebase your local install to that commit, or wait for SuSE/someone to package it.

**Comment by darina-becker** [comment]
Thanks a lot for your help! Check this out ^
