### ISSUE TITLE
Avoiding stating all files before copying

### ISSUE THREAD

**Issue by BryanQuigley** [sosreport/sos#2342]
I can't figure out a way without big changes to avoid looking in the /proc/sys/fs/binfmt_misc/ - perhaps I'm missing something?

in _expand_copy_spec we iterate through ever file we might consider collecting and add it to copyspecs - this does not count towards plugin execution.  So even for paths we don't want we are accessing that entire path - and this does not count towards plugin execution time.

in collect_copy_specs->do_copy_path we actually do the copy - and we stat everything again. This does count towards plugin time.

From an strace this looks something like:
```
18:31:42.219480 access("/tmp/blah", R_OK) = 0 <0.000013>
18:31:42.219519 stat("/tmp/blah", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0 <0.000009>
18:31:42.219571 lstat("/tmp/blah", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0 <0.000009>
18:31:42.219625 stat("/tmp/blah", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0 <0.000009>
18:31:42.219675 stat("/tmp/blah", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0 <0.000009>
18:31:42.219722 stat("/tmp/blah", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0 <0.000009>
18:31:42.270979 lstat("/var/tmp/sos.kcndzau3/sosreport-desktop-2020-12-13-eesukab/tmp/blah", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0 <0.000010>
18:31:42.271329 stat("/tmp/blah", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0 <0.000009>
18:31:42.271373 openat(AT_FDCWD, "/var/tmp/sos.kcndzau3/sosreport-desktop-2020-12-13-eesukab/tmp/blah", O_RDONLY|O_CLOEXEC) = 9 <0.000010>
18:31:42.277519 unlinkat(9, "blah", 0)  = 0 <0.000026>
```

I see two paths forward - which could make us more efficient:
 * Move all plugin activities to be done as that plugin (need to work out double copying files, or try to ensure that doesn't happen much). 
 * Stop caring about which plugin is copying a file (unless something forces us to). Make all file copying bits basically global.

In either case, I believe implementing with os.walk would help.

And there is always the not-optimized way of the global forbidden list and have that be the only way to block something like this.

**Comment by TurboTurtle** [comment]
I'm not sure this is avoidable, unless I'm seriously misunderstanding what you're saying.

In `setup()` we _have_ to end up `stat`'ing to expand the globs used by plugins. In `collect()` we then again have to stat the files passed to `do_copy_path()` to ensure we adhere to size limiting. Unless we cache the filesize data from the first stat, we can't avoid doing that - and I don't think caching the first result is what you're suggesting?

> In either case, I believe implementing with os.walk would help.

How so? Doesn't `walk` trigger a stat as well?

> Move all plugin activities to be done as that plugin (need to work out double copying files, or try to ensure that doesn't happen much).

I'm a little confused by this. The path expansion and copies are already done on a plugin-by-plugin basis and later copied by those same plugins. We don't have any "global" actions being done in the file copying flow.

> in _expand_copy_spec we iterate through ever file we might consider collecting and add it to copyspecs - this does not count towards plugin execution.

This seems like a separate discussion to me - do we want `setup()` time to count towards `plugin_timeout`? Right now we don't do that, but perhaps we should. 

> And there is always the not-optimized way of the global forbidden list 

Yeah, we really need to get on doing that. It's been on the issue tracker for a long time and has a bunch of usefulness. One thing we could do to cut down on the _initial_ `stat`'ing would be to effectively double-filter with any forbidden lists. I.E. filter each `add_copy_spec()` through those lists to get rid of the "higher level" forbids, and then pass it through again for any forbidden paths that are nested within otherwise ok-to-collect paths. It doesn't completely solve the issue, but it at least reduces the amount of `stat`ing we're doing.

**Comment by BryanQuigley** [comment]
I didn't find a way forward on this, I believe you are correct and it's unavoidable.
