### ISSUE TITLE
Feature request - collect any files in /usr/local/etc

### ISSUE THREAD

**Issue by jpl888** [sosreport/sos#2427]
As for title - users might have manually compiled apps on their systems, and it would be useful to collect any configuration files in /usr/local/etc as an indicator/evidence of same

**Comment by bmr-cymru** [comment]
Nack from me - we can't properly sanitise this data, since we don't know what the user may have installed. There are many configuration files in `/etc` that must be post-processed to remove passwords and other secrets.

This could be added to corresponding "regular" plugins, but they would need a means to detect a local installation. This is something that `sos` has typically used the package manager for, so it would be a considerable undertaking to extend it to local manually compiled packages.

**Comment by TurboTurtle** [comment]
Yeah, I have to echo @bmr-cymru here - we can't do a blind collection of `/usr/local/etc`.

This could be added to existing plugins easily by adding those paths alongside the "normal" `/etc/` collections, however that's a bit arduous and would ideally need to include a way to detect those components are locally installed.

We could also do something akin to the `SCLPlugin`s  with SCL paths, where we automatically add `/usr/local/etc` whenever a plugin requests `/etc/` but I'm weary of doing that out of concern of missing important obfuscation points.

**Comment by jpl888** [comment]
Okay - fair enough. No harm asking, I thought.
