### ISSUE TITLE
[cleaner] Doesn't seems to parse actual filename/directory with hostname in it

### ISSUE THREAD

**Issue by slashdd** [sosreport/sos#2465]
Here's an example from Ubuntu:

```
# find sosreport-host0-2021-03-26-ontochw -name "sostestb41"
sosreport-host0-2021-03-26-ontochw/var/lib/cloud/instances/sostestb41
```
mapping
```
{
    "hostname_map": {
        "sostestb41": "host0"
    }
```

**Comment by TurboTurtle** [comment]
We have 2 approaches to this off the top of my head:

1. Something might be wrong with how `obfuscate_string()` is iterating of each parser's dataset in a way that the hostname dataset isn't returning the obfuscated string. I think this may be due to the fact that the filename in this case is just the shortname (which we still try to obfuscate in the parser), instead of the FQDN.
2. We could also investigate changing `obfuscate_string()` to use the same `parse_line()` method in the parsers, instead of directly iterating over the dataset.

**Comment by TurboTurtle** [comment]
Cycled around on this - we want to use `obfuscate_string()` here so that we bypass regex matching and just directly replace known mappings.

I _did_ find an issue within the `obfuscate_string()` flow, but I think it's not directly the cause of this issue. However, I've also been unable to reproduce this issue myself. The problem I found is that we would stop obfuscation on the first match of a known mapping, rather than iterate through the entire dataset, the fix for which is this:

```
diff --git a/sos/cleaner/parsers/__init__.py b/sos/cleaner/parsers/__init__.py
index dd0451df..c77300aa 100644
--- a/sos/cleaner/parsers/__init__.py
+++ b/sos/cleaner/parsers/__init__.py
@@ -104,7 +104,7 @@ class SoSCleanerParser():
         """
         for key, val in self.mapping.dataset.items():
             if key in string_data:
-                return string_data.replace(key, val)
+                string_data = string_data.replace(key, val)
         return string_data
 
     def get_map_contents(self):
```

With current master, manually dropping several flat files whose name is just my system's short hostname  still results in those files being properly obfuscated.

I'll post this fix up separately, but it appears some more digging is needed here. How reliably can you reproduce this? Is it with particular file paths, or any?

**Comment by TurboTurtle** [comment]
@slashdd have you been able to reproducer this with the current master branch?
