### ISSUE TITLE
Change RedHat legacy FTP upload server to the new Secure FTP server

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2467]
`dropbox.redhat.com` is planned to be replaced by Secure FTP and deprecated. We should use the new `sftp.access.redhat.com` as well.

One particular implementation issue: the SFTP server accepts filenames with support case prefix, while `sosreport` generates the filename with ticket number in the middle. We must amend the remote filename by adding case number prefix.

**Comment by TurboTurtle** [comment]
There's a bigger issue here for implementation. The FTP module in the standard library doesn't support SFTP, and we certainly don't want to use something like `paramiko` for a host of reasons.

Worse yet, we'll lose the automatic failover due to SFTP requiring login credentials just like the RH Customer Portal.

**Comment by TurboTurtle** [comment]
Been investigating this, and basically our only option is to shell out to sftp. This is because:

- We don't want to use `paramiko`
- There's not a well established consistency between downstreams for `libssh` and `libssh2` with the python bindings for either

So, shelling out to the system's `sftp` binary is our path forward, but that presents another issue in that there is no native non-interactive way to supply a password when calling sftp.

This leaves us with 2 options that I see:

1. Use `pexpect` here, much the same as we use it for `sos collect`. This is a bit of a double edge sword here in my opinion. We already have a _soft_ dependency on `python-pexpect`, but that's for the entire `collect` component. Having that extended to specific functionality within `report` makes me a little wary. End users can generally accept a component being unavailable without a particular module that may not be desired for security reasons, but gating a specific use case of `--upload` would be a hard sale in my opinion. @sosreport/team-ubuntu thoughts here on potentially using `pexpect` for sftp uploads?

2. Use `sshpass` in conjunction with `sftp`. I'm not sure if `sshpass` is a default installation on downstreams though, so kind of the same situation with regards to dependencies. This would require an invocation like `sshpass -p $pass sftp $user@$host:$remote_name $archive_name` which isn't all that bad at first glance, as we should be able to pack `$pass` into an env var to avoid leaking the password.

**Comment by BryanQuigley** [comment]
Huh. I thought we had python3-pexpect as a recommends in Debian/Ubuntu packaging - turns out it's a full depends. As it's being needed more, maybe just make it a hard requirement?

For the record:
 * sshpass - is in universe so would need a security review before being included by default
 *  python3-pexpect is in main and included in Desktop install by default by multiple packages.  It's also in Server/cloud but maybe just by sos?
 *  python3-paramiko is in main and included in Desktop install by default.

**Comment by TurboTurtle** [comment]
Ok, so that pretty much makes the decision for us then, I believe. We can't reasonably expect downstreams to change existing security postures for an optional feature.

I was sort of hoping to avoid more reliance on pexpect, but realistically it's the more favorable approach since we _already_ make use of it. I think longer term we should look at the possibility of using available ssh python bindings depending on the host distro. Thinking over it more lately, I'm more ok with it remaining as a recommends rather than a hard dependency since sftp is an option of an already optional feature.

I'm starting to work up an implementation for this, and it should be relatively straightforward, if a little ugly with all the pexpect catches it'll need.

**Comment by slashdd** [comment]
> Huh. I thought we had python3-pexpect as a recommends in Debian/Ubuntu packaging - turns out it's a full depends. As it's being needed more, maybe just make it a hard requirement?
> 
> For the record:
> 
> * sshpass - is in universe so would need a security review before being included by default
> * python3-pexpect is in main and included in Desktop install by default by multiple packages.  It's also in Server/cloud but maybe just by sos?
> * python3-paramiko is in main and included in Desktop install by default.

It's in fact a Depends as follows:

d/control:
Depends: ${python3:Depends}, ${misc:Depends}, python3-pexpect
