### ISSUE TITLE
[sos4.1][sos-collect] Are regexes supported for `--nodes`?

### ISSUE THREAD

**Issue by Gleland** [sosreport/sos#2493]
Hello, are regexes supported when specifying nodes for report collection? The documentation mentions it, but I'm unable to find a method that works:

```
$ sos collect --help

...
  --nodes NODES         Provide a comma delimited list of nodes, or a regex to match against 
  ```
  
I have three remote machines that are reachable via ssh on my current server. I'd like to use the `--nodes` flag to generate and collect a report on each, but I haven't found how to make the regex part of the flag work correctly.

Using a comma-delimited list works without issue:
```
$ sos collect --batch -a --all-logs --clean --nodes machine-1,machine-2,machine-3 --ssh-user $user -vvv --nopasswd-sudo
```

but I'm unable to find the right syntax for utilizing regex. Here are a few that I've tried:

```
$ sos collect --batch -a --all-logs --clean --nodes machine-[1..3] --ssh-user $user -vvv --nopasswd-sudo
$ sos collect --batch -a --all-logs --clean --nodes '/machine-[1..3]/' --ssh-user $user -vvv --nopasswd-sudo
$ sos collect --batch -a --all-logs --clean --nodes /machine-[1..3]/ --ssh-user $user -vvv --nopasswd-sudo
$ sos collect --batch -a --all-logs --clean --nodes machine-[1-3] --ssh-user $user -vvv --nopasswd-sudo
$ sos collect --batch -a --all-logs --clean --nodes 'machine-[1-3]' --ssh-user $user -vvv --nopasswd-sudo
$ sos collect --batch -a --all-logs --clean --nodes machine-\d --ssh-user $user -vvv --nopasswd-sudo
$ sos collect --batch -a --all-logs --clean --nodes [machine-\d] --ssh-user $user -vvv --nopasswd-sudo
$ sos collect --batch -a --all-logs --clean --nodes '[machine-\d]' --ssh-user $user -vvv --nopasswd-sudo
$ sos collect --batch -a --all-logs --clean --nodes 'machine-\d' --ssh-user $user -vvv --nopasswd-sudo
```

In each of these cases, I get the same output from the tool:
```
...
Cluster status could not be determined. Is the cluster running on this node?
[sos_collector:get_nodes_from_cluster] Node list: []
[sos_collector:reduce_node_list] Node list reduced to []

The following is a list of nodes to collect from:
       $localhost

[archive:TarFileArchive] initialised empty FileCacheArchive at '/tmp/sos.ighy040g/sos-collector-2021-04-14-muqmh'

Connecting to nodes...
Collection would only gather from localhost due to failure to either enumerate or connect to cluster nodes. Assuming single collection from localhost is not desired.
Aborting...
```

I'm running version 4.1 (on both the local and remote machines):

```
$ apt-cache policy sosreport
sosreport:
  Installed: 4.1-1ubuntu0.20.04.1
  Candidate: 4.1-1ubuntu0.20.04.1
  Version table:
 *** 4.1-1ubuntu0.20.04.1 500
        500 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     3.9-1ubuntu2 500
        500 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages
```

the machines are running Ubuntu 20.04.2 (from cat `/etc/os-release`)

Thanks for your time!

**Comment by TurboTurtle** [comment]
The regex matching for `nodes` applies to nodes returned from the cluster master/manager/leader node, not those that are statically added from the command line. The verbiage on this could be clearer, I agree.

Basically, when you run `collect`, sos will try to determine a cluster type locally (or on a remote node given by the `--master` option). In your case `collect` is loading the `pacemaker` cluster due to the presence of the `pacemaker` package locally. However, because `pcs status` is not returning any nodes (or is returning an error), collect is reporting an empty node list.

Any regex given to `--nodes`  is then used to trim any non-matching nodes returned by the cluster. Since the node list is empty, we have nothing to trim. 

After this regex matching is applied, any values given to `--nodes` that were either not reported by the cluster in the node list, or were trimmed by any provided regex, (and are not a regex themselves) are re-added statically to the node list.

As an example, suppose `pcs status` returned `node1`, and `nodea` and you used `--nodes=node[1-3],nodeb` in your `collect` command. Your resulting node list to collect from would be `localhost`, `node1`, and `nodeb`.

The reason we don't extrapolate regexes that don't match the node list returned from clusters is that we don't have a reliable or non-hacky way to validate those hostnames actually exist. I could be convinced of changing this, if a relatively clean solution was presented that validated extrapolated hostnames/addresses without causing a host of logged connection errors when `collect` goes to actually attempt a collection from those nodes.

In the meantime, if you don't want to continually pass a long list of names that don't get returned by a cluster, you can use the host group functionality. By using `--save-group $GROUP_NAME`, all the hosts that were collected from will be saved to a group that can then be referenced in future commands using `--group $GROUP_NAME`.
