### ISSUE TITLE
upload options do not support local SSL urls nor self-signed certificates

### ISSUE THREAD

**Issue by slashdd** [sosreport/sos#2497]
More information ca be found: [LP: #1901786](https://bugs.launchpad.net/ubuntu/+source/sosreport/+bug/1901786)
This has been reported by a member of the Canonical support team @desrod

**Comment by TurboTurtle** [comment]
Reading over the LP it seems we have 2 distinct issues, if I'm reading it right:

1. Either `--upload-url` is broken in that we lose the command line provided url in our url determination, or we need better error handling. I would not expect the "No upload url provided" error here.
2. No way to ignore ssl errors.

The second one is very easy to address. We just need to add an option that toggles the `verify` parameter for `requests`. While we're at it, we should probably allow user-controlled toggling of HTTPS streaming - e.g. do we do a `PUT` or  a `POST`. Right now this is policy controlled independent of the url we're trying to upload to.

@desrod or @slashdd  can you provide a mock nginx config so that we can make sure we're testing against the same configuration?

**Comment by desrod** [comment]
Sure can, I tore down my nginx + DAV reproducer, but I'll build it back up and post the details here.
