### ISSUE TITLE
[ubuntu][openstack_*] Openstack services need to explicitly include logs from /var/log/apache2

### ISSUE THREAD

**Issue by lathiat** [sosreport/sos#2525]
The apache plugin was recently changed to specifically exclude collecting logs for known openstack services, such as /var/log/{httpd,apache2}/nova*.log on any platform in #1950

The relevant paths for RedHat in /var/log/httpd were added to the various OpenStack plugins but they also need Ubuntu paths under /var/log/apache2. Need to confirm which services are affected and add them.

**Comment by arif-ali** [comment]
circling back on this issue

i think the problem here is https://github.com/sosreport/sos/blob/main/sos/report/plugins/apache.py#L60

We are asking it to ignore some folders, but this won't work for ubuntu, as the apachepkg is wrong variable to use. The directory here should be `apache2` and not `apache`. i think this needs a bit of work in the same way RH stuff has been pushed over to the likes of `openstack_nova.py`

I think, quite a bit of work is needed here to bring it on-par imho

whereas RH stuff puts the logs in like `/var/log/http/<openstack_service>/`, ubuntu charming has `/var/log/apache2/<openstack-service>_*`, so could be a bit tricky

**Comment by arif-ali** [comment]
Just realised, it's actually worse, it's not just ignoring folders in `/var/log/apache2` with those names, but files too. Just tested this on a `nova-cloud-controller` unit, and just realised we don't currently collect the following files

* `nova-api-os-compute_access.log`
* `nova-api-os-compute_error.log`
* `nova_api_access.log`
* `nova_api_error.log`
* `nova_meta_access.log`
* `nova_meta_error.log`
