### ISSUE TITLE
Support foreman/pulp plugins on Debian distro?

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2526]
I understood `foreman` / `foreman-proxy` and I think also `pulp` (but not `candlepin`?) can be installed on Debian distributions. Is it worth enhance relevant sos plugins for the distro? What particular plugins are reasonable to cover? `foreman`(*) and `pulp`? What are Debian specifics to enable the plugins, collect data etc.?

(*) I have a plan to split `foreman` plugin to `foreman` and `foreman-proxy` for an external Smart Proxy. But that is an independent topic..

Cc @ekohl and @slashdd .

**Comment by ekohl** [comment]
AFAIK Pulp 3 could run on Debian, but I'm not aware of anyone maintaining packages or doing so. It'd be premature to look for package names that don't exist.

For Foreman, there's already this:
https://github.com/sosreport/sos/blob/e5d7c5dfdfaa2c992af27efbc7d6e1c85404a630/sos/report/plugins/foreman.py#L344-L346

However, the version in Debian itself doesn't ship this (too old) so I'm not sure how well it works. In theory it should since all paths look correct (there's some Debian-specifics in there).

So I think it mainly needs verification, no actual code unless we find bugs.

> (*) I have a plan to split `foreman` plugin to `foreman` and `foreman-proxy` for an external Smart Proxy. But that is an independent topic..

I think it would also make sense to split off Candlepin to its own plugin. It's a standalone system and we're talking about how it could run separate from the main Foreman deployment in advanced scaling setups.

**Comment by pmoravec** [comment]
Yeah, we already have a separate `candlepin` plugin ;-)

**Comment by ekohl** [comment]
Hah, ok. Then I'm surprised that this is here:
https://github.com/sosreport/sos/blob/e5d7c5dfdfaa2c992af27efbc7d6e1c85404a630/sos/report/plugins/foreman.py#L107-L113

That's really only for Candlepin, not Foreman.

**Comment by pmoravec** [comment]
I think we can close this, as:

- we have both `DebianForeman` and `DebianForemanProxy` classes
- distribution of `pulp` and/or `candlepin` on Debian distro is unknown or not well maintained - hence no need to react from our side

Does somebody have a different opinion?

**Comment by ekohl** [comment]
> we have both `DebianForeman` and `DebianForemanProxy` classes

I looked through it and at least opened https://github.com/sosreport/sos/pull/2674.

> distribution of `pulp` and/or `candlepin` on Debian distro is unknown or not well maintained - hence no need to react from our side

:+1: on this. I'm not aware of any packaging efforts for this and I wouldn't target non-packaged efforts (like pip-based installs).

**Comment by pmoravec** [comment]
Interpreting silence from others as an agreement to closure. Thanks @ekohl for the discussion and few issues/PRs raised!
