### ISSUE TITLE
[report] print a warning that --build and --encrypt-* are mutually exclusive?

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2568]
Running:

    python3 bin/sos report -o host --build --encrypt-pass testpass

the GPG encryption is silently ignored. Shall not we warn the user that the GPG encryption won't be applied?

**Comment by TurboTurtle** [comment]
Makes sense, the question is where. `--build` is a report-only option, whereas the encryption options are global, since they can be used by `collect` as well.

We could potentially add `--build` to the existing mutex group, but that's a little bit hacky. But I'm not sure if it's any better or worse then printing a warning at some point, and then having to make an assumption on what the intent was. Did the user want a build directory that wasn't recursively encrypted? Did they want to abort? Did they want to ignore `--build` if an encryption option was given? Etc...

**Comment by TurboTurtle** [comment]
I should clarify - it'd be hacky to add `--build` to the mutex group because we'd need to do it within `SoSReport.add_parser_options()`, not in the top-level parser. Otherwise we'd expose `--build` to `collect` and other components, where that option is not used or useful.

**Comment by pmoravec** [comment]
Yeah, neither option sounds straightforward. *Probably* a option mutex would be the best/ultimate solution (as we do not provide functionality for both options together, indeed), but that is hacky to fix. Adding a warning is sufficient in my eyes, and I think dropping `--encrypt` options like current behaviour is the right choice here. Because `--build` is so "specific" that it probably was used by purpose, while `--encrypt` is a feature applied *later* in the call flow. And it is ignored similarly like in `--build --compress-type=gzip` use case (well, we shall print a warning also here that the compression method is ignored..?).
