### ISSUE TITLE
[report] limit proc/sys/kernel/sched_domain/cpu* and sys/devices/system/cpu/cpu* to a reasonable amount of CPUs only

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2569]
Use case: having a system with >1500 CPUs, `sos report` runs there for >2 hours. The cause is that it collects `proc/sys/kernel/sched_domain/cpu*` (in `system` plugin) and `sys/devices/system/cpu/cpu*` (in `processor` plugin) dirs, one for each CPU. Which is almost 200 files for one CPU.

Collecting 100k files per one plugin and 200k files per another does not scale well. We should have plugins options (for both plugins with similar/same name? or one common option?) to limit the CPUs to examine to e.g. 100 by default.

**Comment by TurboTurtle** [comment]
Looking a bit more at the reported issue, the run time was due to HTML report generation. The user ultimately reported that upgrading to a version that included the enhancements to that from 3.8 helped, and they always have the option of using `--no-report` if there are further issues there or if they for some reason cannot keep the updated version.

So, at this point I think this is actually a non-issue for current versions of sos?

**Comment by pmoravec** [comment]
Right, I tried to reproduce it in upstream and *started* to have not-scaling results which was revealed as a test hiccup only. 500k files can be collected by one plugin within 10 minutes (if we dont use the old imperformant html generation, rewritten from scratch few years ago).

As there is no scalability problem, we can close this.
