### ISSUE TITLE
Release process

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#260]
We probably should have one.

**Comment by bmr-cymru** [comment]
The Red Hat community blog just posted some [guidelines for announcing software releases](http://community.redhat.com/blog/2015/12/guidelines-for-announcing-software-releases/).

Seems a fairly reasonable model?

**Comment by pmoravec** [comment]
Read it and I agree.

**Comment by battlemidget** [comment]
:+1:

**Comment by karibou** [comment]
LGTM +1

**Comment by TurboTurtle** [comment]
Ok, so like other long standing issues some things have changed in the intervening years. Recently, we've held close to a 2-releases-per-year trends, and we've held reasonably close to a 6-month cadence there in most releases. Our releases have been getting bigger too; more features, more bug fixes, more testing, etc...


I see 3 options relevant to this issue:

**Option 1 - Keep on keepin' on.**

Don't really change what we're doing. Use milestones to mark release dates, try to stick as close to those as possible. Most of our planning typically comes at the formal close of one release - e.g. moving milestone tags to future releases, some discussion around big ticket items (_cough_ soshelp _cough_).

**Option 2 - Have a formal RC tag X weeks before a minor version cut**

As in the linked guidelines below, this would need to be decently prior to an actual release so there is a feedback period. Since we're on a 6-month cadence currently we could make this easy and cut an RC 1 month prior to the minor version release date.

**Option 3 - Change up our release cadence**

Not so much directly related to anything discussed thus far, but this is an option given how many projects are going to a weekly update/rolling release style format. I'm not suggesting sos go to such a model, or that that would even be beneficial for a project like sos, but perhaps a more frequent release cadence (maybe quarterly?) has some merit? And if we also make an RC cut before a release, we could be a bit more focused in our release goals (I.E. one release is backlog focused, another is 'implement this new component', the next is primarily bug fix/ edge case testing focused). I'm not sure how the different downstream's would react to having more-frequent-yet-smaller rebases for version updates, though.

**Comment by pmoravec** [comment]
I am in favour of **Option 1**. Until there is some (evident) benefit to change it, I feel the current approach works well.

Maybe some fine-tuning towards **Option 2** makes sense: announce "we plan to release the upstream as 4.Y version in 1 (or two?) weeks, please smoke-test it to report&fix evident gotchas". At least in past I did such tests by myself, usually found (and fixed) few such simple bugs before the release.

**Comment by slashdd** [comment]
Ubuntu releases a new version every 6 months, and the new version may require some plugins changes here and there. See [PR2501](https://github.com/sosreport/sos/pull/2501/commits/b2e1300b2ef89987574faf7bf5f4b11d7f04b151) as an example.

Option 1, meaning staying close to a 6-month cadence is definitely beneficial for me wearing my Canonical/Ubuntu sos maintainer hat. Ubuntu releases every 6 months in April and October, so 2 releases a year cadence.

**Comment by TurboTurtle** [comment]
Ack - looks like option 1 is preferred by downstreams, so no point in making changes just to make changes.

We'll stay with our current 6-month cadence, and take @pmoravec's suggestion of making an announcement prior to a release requesting testing, rather than cutting a formal RC.
