### ISSUE TITLE
Provide a plugin option to set custom PATH

### ISSUE THREAD

**Issue by vikas-goel** [sosreport/sos#2624]
There are software components from different vendors that get installed in /opt/ at various locations. In order to provide an ease of running commands from the those directories and still be able to create output file with the command base name without passing `suggest_filename` option for each invocation, need a way to set the executable path in PATH env.

See https://github.com/sosreport/sos/pull/2610#pullrequestreview-705722726 for use-case

**Comment by TurboTurtle** [comment]
`PATH` is controlled by the loaded policy for any particular run of `sos`. This is due in part because generally speaking `sos` is mostly used in interactions with technical support for a distribution that has a related policy in the project. These policies are defined based on how those support organizations want their diagnostic data collected/handled/executed.

Further, components that place binaries in `/opt/` are, again generally speaking, not shipped by the entities that are providing that technical support for the distributions. If they were, they'd be in the relevant locations in the `PATH` for that distro.

Allowing plugins to override the configurations set by the loaded policy goes against the basic design of sos policies in relation to their control of how plugins are loaded and how they behave.

The `suggest_filename` parameter is provided specifically to allow more end-user friendly naming of command outputs that would otherwise be burdensome to consume by humans - e.g. long binary paths. It is one of the intended use cases for collections like these.

**Comment by vikas-goel** [comment]
Is it okay to update the PATH env in a custom policy?

**Comment by TurboTurtle** [comment]
A policy would be the place to set an updated `PATH`, yes, however I should note that a policy that override an existing distribution policy but only appends the `PATH` would not be merged into upstream. Amending the `PATH` setting for an existing policy would be something that would be handled by a downstream that is in turn packaging `sos`.

**Comment by vikas-goel** [comment]
Thanks. I do not intend to merge the policy upstream.
