### ISSUE TITLE
[tests] Foreman testing suite aborting due to Debian 11 release

### ISSUE THREAD

**Issue by TurboTurtle** [sosreport/sos#2656]
The current Foreman tests will now abort before the test suite actually gets run. This is due to Debian 11 releasing, thus causing this in the prep scripts:

```
Reading package lists...
E: Repository 'http://security.debian.org/debian-security buster/updates InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
E: Repository 'http://deb.debian.org/debian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
E: Repository 'http://deb.debian.org/debian buster-updates InRelease' changed its 'Suite' value from 'stable-updates' to 'oldstable-updates'
```
Which causes `apt-get update` to exit with a status code of 100, thus triggering cirrus to fail the task.

We have a few options here:

1. Add `--allow-releaseinfo-change` to the `apt-get update` step
2. Rebuild the images on Debian 11 (does Foreman 2.4 support Debian 11?)

**Comment by pmoravec** [comment]
>     2\. Rebuild the images on Debian 11 (does Foreman 2.4 support Debian 11?)

Does not seem so: https://theforeman.org/manuals/2.4/index.html#2.Quickstart says Debian 10 is supported. (and foreman 2.5 has the same).

**Comment by ekohl** [comment]
The problem is that in your `/etc/apt/sources.list` you have listed `stable`. If you make that `buster` it shouldn't try to update to the new stable. How do you get the image? I think that the cloud image should have this by default.

As for Debian 11, we don't support it yet, but it's being discussed. The groundwork for that has yet to start so Foreman 3.1 earliest (Foreman 3.0 is at rc1 now).
