### ISSUE TITLE
[openstack_octavia] Stop collecting Octavia Loadbalancer details from Overcloud nodes or where env variables doesn't exist

### ISSUE THREAD

**Issue by pmannidi** [sosreport/sos#2670]
Currently, whenever sosreport is run, it tries to run Octavia loadbalancer commands and fails.

Expectation:
Octavia should collect all the logs and should not run the loadbalancer commands wherever its unnecessary like in overcloud nodes where python-octaviaclient is not installed or when environmental variables are not set from wherever the sosreport command is run.

**Comment by pmoravec** [comment]
> Currently, whenever sosreport is run, it tries to run Octavia loadbalancer commands and fails.
> 
> Expectation:
> Octavia should collect all the logs and should not run the loadbalancer commands wherever its unnecessary like in overcloud nodes where python-octaviaclient is not installed or when environmental variables are not set from wherever the sosreport command is run.

So the code https://github.com/sosreport/sos/blob/main/sos/report/plugins/openstack_octavia.py#L64-L93 should be run conditionally only? All that or just some subset of the commands?

How to detect "in overcloud nodes"? What env.variables must be set to collect the commands?

The test should be like

    if (not (on_overcloud_node)) and \
       self.is_installed("python-octaviaclient") and \
       os.environ[".."] and os.environ[".."]:
            (call the commands only here)

?

**Comment by pmannidi** [comment]
So the code https://github.com/sosreport/sos/blob/main/sos/report/plugins/openstack_octavia.py#L64-L93 should be run conditionally only? All that or just some subset of the commands?
>> All of them should be run conditionally only. 

As you suggested, something like 
if self.is_installed("python-octaviaclient") and \
   os.environ[".."] and os.environ[".."]:

the environmental variables required should be similar to https://github.com/sosreport/sos/blob/e2ca3d02f36c0db4efaacfb2c1b7d502f38e371c/sos/report/plugins/openstack_glance.py#L61-L73

**Comment by pmannidi** [comment]
After thought, i think it's better to remove that part of code. In normal circumstances, it will never be run. In general, for Red Hat deployments, everything is containerized and we don't set environment variables in overcloud nodes and we don't have python-octaviaclient installed in overcloud nodes. For undercloud, we don't use octavia. so this part of code would be running unnecessarily in undercloud and will not run in overcloud nodes. It's better to remove it completely.

**Comment by kajinamit** [comment]
So when a deployment is managed by TripleO, we have two OpenStack clusters in the deployment.
 - undercloud to manage overcloud
 - overcloud to provide actual cloud service
When we make any request to undercloud and overcloud, we usually make all requests from the undercloud node. We load credentials stored in undercloud and run commands there. So if undercloud credentials is loaded all information are captured from undercloud, while if overcloud credentaisl is loaded, then from overcloud. So the credential files loaded before sosreport command would change the source of these information.

In general use case we don't deploy Octavia in undercloud, but only in overcloud.

This are the contexts behind this issue, IIUC.

After giving some thoughts on this, I tend to leave the current implementation and go for the same line as openstack_neutron, because

1)
The congestion between overcloud and undercloud is common for all openstack plugins. if you load overcloud credentials, you'll get information from overcloud captured instead of undercloud, even if sosreport is executed in undercloud node. So I'll defer the dicision here.

2)
There is still a possibility to load credentials in controller nodes and run sosreport, to capture information from overcloud.

3)
The issue is specific to TripleO deployment, especially TripleO multi node deployment. We don't expect this "issue" if the deployment is packstack one or TripleO standalone one.
