### ISSUE TITLE
[tests] increase timeout of some tests?

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2700]
I noticed several times already that a avocado test failed like https://github.com/sosreport/sos/pull/2695/checks?check_run_id=3691145504 :

    (47/59) tests/report_tests/plugin_tests/logs.py:LogsSizeLimitTest.test_journal_size_limit:  ERROR:
    ..
    Creating compressed archive...
    
    ERROR: Timeout exceeded, see output above (405.04 s)
     (48/59) tests/report_tests/plugin_tests/logs.py:LogsSizeLimitTest.test_journal_tailed_and_linked:  ERROR: [Errno 2] No such file or directory: '/var/tmp/avocado_3jr9971usos_tests.py.LogsSizeLimitTest/output' (0.00 s)

The later error is caused by the timeout one. Anyway I can't find (in either `sos` or `avocado`) any such timeout (360 or 400 seconds).

Since we test logs size in these test cases, a different approach in limiting `--log-size` to get faster `sos report` run is not applicable.

**Comment by TurboTurtle** [comment]
Yeah, the issue is two-fold around the fact that GCE vCPU performance is not guaranteed which bites us for both the random string generation _and_ the collection of it from `journalctl`, _and_ then again with compressing the archive since 100MB of random data is not fun to compress.

The easy workaround is to increase the timeout, yes. We can do that for now but I'd really like to see in the future if we can improve design of the log size test as a whole.

**Comment by pmoravec** [comment]
Do we need to generate *random* data, or some pseudo-random or say 1M lines of almost identical 100bytes?

**Comment by TurboTurtle** [comment]
No, it doesn't need to be random, strictly speaking. We do however need to be able to inject enough data into the journal so that the journal size on disk is at least 100MB, so that we can test our size limiting.

IIRC, journald does some compression of its own, which is what throws off repeating smaller sets of data a significant number of times.

If we can do away with the local data generation and in some way fill write more than 100MB to the journal quickly, I'm all for it.
