### ISSUE TITLE
is it intended that `sos report` is always run on the machine it describes?

### ISSUE THREAD

**Issue by ciq-mcarifio** [sosreport/sos#2741]
If so, does `sos report` need to load all the possible `sos.policies.distros.*`? Or is this for `sos collector`? Ty.

**Comment by TurboTurtle** [comment]
On the machine that `sos report` executes on, we iterate across our supported policies until we hit one whose `check()` class method returns `True`. At that point we load/instantiate _just_ that policy and stop iteration. Since we're running the `check()` method, the previous policies are not actually instantiated.

For `sos collect` we effectively end up doing this twice - once on the machine running `sos collect` so that we can properly locally leverage the node according to that policy, and then again when `sos report` gets executed on that node. However, that second time the execution is entirely remote and the local `sos collect` process has no introspection of the policy loaded for the remote `report` process.

Does that answer your question, or am I missing what you're getting at?
