### ISSUE TITLE
Add an option to encrypt or passphrase protect binary files

### ISSUE THREAD

**Issue by vikas-goel** [sosreport/sos#2838]
Requesting for a feature to keep binary files encrypted or passphrase protected when running with --keep-bin option.

The use case is that the zip/.gz files at times have IP address etc. These zip files are time sensitive to the collection such as hardware fault event and needed for troubleshooting.

In order to troubleshoot, the zip files need be retained. In order to protect sensitive information, the zip files can be passphrase protected. The vendor/Support can request for key to decrypt the zip files only with customer consent.

Each collection can use unique random key for passphrase protection.

**Comment by TurboTurtle** [comment]
I'm not sure I understand the request here. `--keep-binary-files` just means we don't remove binary files (which we can't obfuscate) when cleaning a report. Whether or not those binary files are encrypted isn't up to us.

Users can encrypt an entire archive with either `--encrypt-key` or `--encrypt-pass`, which would result in an obfuscated and encrypted archive - including binary files kept from `--keep-binary-files` - but we don't encrypt on a per-file basis.

**Comment by vikas-goel** [comment]
When a hardware fault event occurs, the system collects data point in time and transmit to vendor server for troubleshooting purpose to meet SLA. The data collection happens with PII masked. The zip files from third-party are retained in the collection. 

These zip files, that may contain IP address/hostname, may or may not required for troubleshooting purpose depending on the hardware fault. In the scenario where Support can work without zip files, there is no back and forth interaction needed from customers. But when needed, customers can provide their consent and work with Support to extract the zip files.

So, the ask is when PII masking is enabled and binary files are retained, then provide an option to encrypt the zip files to allow access with customer consent when needed.

**Comment by TurboTurtle** [comment]
This use case is already covered via the existing encryption options. End users in this case should do something like `sos report --clean --keep-binary-files --encrypt-pass mypassword123`.

The result is an encrypted tarball with the binary files intact in an otherwise obfuscated report. The end user then needs to provide the password to whomever is receiving the report in order for that party to be able to do _anything_ with the archive. Providing this password is considered trust/consent for accessing all files within the report.

Individually encrypting binary files introduces non-trivial code complexity, as well as end user complexity insofar as how do you properly invoke `sos report` in such a way as to do this? How do you control encryption passwords/keys for these individual files vs. the archive as a whole? If you want "Each collection can use unique random key for passphrase protection" as stated earlier, then you now have to handle the back-and-forth on somehow retrieving that random key for each file your support representative needs to access. In short, this introduces significant burden on both parties and doesn't provide a significant benefit over the existing functionality of `--encrypt-pass` or `--encrypt-key`.

**Comment by vikas-goel** [comment]
In this case, the entire package will be encrypted and for every single case customer will need to be contacted. We want to avoid that.

**Comment by TurboTurtle** [comment]
First and foremost - yes, the idea behind encryption here is that there is a communication channel open to establish trust with the recipient of the archive.

But furthermore, if we encrypt binary files on a per-file basis you not only end up requiring that communication _anyways_, you also now require it _multiple times_ for each archive and each encrypted file therein.


Per-file encryption is not a viable implementation for sos.

**Comment by vikas-goel** [comment]
The communication will be on-demand basis, not always. Maybe, 20-25%. We don't need each zip file to be encrypted with a different password. The same password can encrypt all the binary files. The usage could look like:
`sos report --clean --encrypt-binary-files --encrypt-pass mypassword123`

**Comment by vikas-goel** [comment]
The purpose here is to differentiate data in two categories. What can be masked and what cannot be. The data that's already masked, no communication needed. The data that cannot be masked and need access for troubleshooting, get customer consent.

**Comment by vikas-goel** [comment]
If we encrypt the package, that will mean even for masked data the key will be needed. And with that, even the clear data will become accessible that customer's won't allow.

**Comment by TurboTurtle** [comment]
If an end user does not want binary data accessible to a recipient, that is what the default behavior is for. If the end user does want that data accessible, then they can use `--keep-binary-files` and if they want to add an extra layer of protection that's where the `--encrypt-*` options come in.

Doing ad-hoc encryption of unencrypted files but leaving the archive unencrypted is a confusing user experience to say the least. It does not fit with the goals of the project or the implied, historical, or stated functionality of sos.

Per-file encryption is not a viable implementation for sos.

**Comment by vikas-goel** [comment]
How does one allow access to masked data and require separate consent for clear data?

**Comment by TurboTurtle** [comment]
As I've been saying, if an end user wants to protect data in an archive then they need to use one of the `--encrypt-*` options. That's what is provided.

Any other considerations on access to the archive is up to the party generating the archive.
