### ISSUE TITLE
[cleaner] Some evidently binary files are attempted to be obfuscated

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2839]
Two issues in fact:

1) `/etc/hostid` is being collected by two plugins `host` and `networking` (https://github.com/sosreport/sos/blob/main/sos/report/plugins/networking.py#L62), the later is redundant.

2) Cleaner attempts to obfuscate the file, despite it has evidently binary content:

```
# hexdump -C /etc/hostid 
00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
07b00000
#
```

and it takes significant amount of time:

    2022-02-01 14:17:40,764 DEBUG: [cleaner:sosreport-pmoravec-rhel8-2022-02-01-sjjppwd] Obfuscating sos_strings/host/etc.hostid.tailed
    2022-02-01 14:18:26,599 DEBUG: [cleaner:sosreport-pmoravec-rhel8-2022-02-01-sjjppwd] Obfuscating sos_strings/jars/jars.json
    2022-02-01 14:18:26,616 DEBUG: [cleaner:sosreport-pmoravec-rhel8-2022-02-01-sjjppwd] Obfuscating sos_strings/networking/etc.hostid.tailed
    2022-02-01 14:19:12,231 DEBUG: [cleaner:sosreport-pmoravec-rhel8-2022-02-01-sjjppwd] Obfuscating sos_strings/logs/var.log.messages-20220130.tailed

**Comment by pmoravec** [comment]
Fix for 1) is trivial, skip collecting the file in `networking` plugin.

For 2) , my concern is that `file_is_binary` method/heuristic simply does not work properly to files with empty content (where very first bytes are '\0`, to be precise).

**Comment by TurboTurtle** [comment]
For point 2, is this a matter of simply reading more than 1 byte in `file_is_binary()`, or do we need to get a bit more complex here?

**Comment by pmoravec** [comment]
Reading any number of `\0` bytes that way, no exception is raised (at least I replaced there 1 by random values up to 10k and got the same results).

Searching for other approaches, I found these two promising:

- https://stackoverflow.com/questions/898669/how-can-i-detect-if-a-file-is-binary-non-text-in-python#comment52258726_7392391
- https://stackoverflow.com/questions/1446549/how-to-identify-binary-and-text-files-using-python/1446870#1446870 (referenced from https://gist.github.com/magnetikonline/7a21ec5f5bcdbf7adb92f9d617e6198f)

Some "but.." arguments:
- the later one has various type errors and also it detects purely text file as a binary one (:-o)
- in general, relying on stackoverflow best answers might be dangerous until one really understands the topic
- some wider tests (e.g. comparing the heuristics against a typical sosreport) shall be done to determine which one fits our purposes the best

**Comment by TurboTurtle** [comment]
Looking into this a bit more.

There is the `mimetypes` module within the standard library, but it is very limited and it depends entirely on file extensions. So we'd still need to add some additional logic ourselves to handle what is likely the majority of files within a given archive.

Then there is `python3-magic`, which are the python bindings for libmagic. It seems to give much more reliable results, and pretty much exactly what we need:

```
>>> magic.detect_from_filename('/var/tmp/sosreport-dhcp-1-183-177-2022-02-07-bvdkmuu.tar.xz')
FileMagic(mime_type='application/x-xz', encoding='binary', name='XZ compressed data')

>>> magic.detect_from_filename('/var/tmp/sosreport-dhcp-1-183-177-2022-02-07-bvdkmuu.tar.xz.sha256')
FileMagic(mime_type='text/plain', encoding='us-ascii', name='ASCII text')

>>> magic.detect_from_filename('/var/lib/rpm/__db.001')
FileMagic(mime_type='application/octet-stream', encoding='binary', name='Applesoft BASIC program data, first line number 18')

>>> magic.detect_from_filename('/etc/os-release')
FileMagic(mime_type='inode/symlink', encoding='binary', name='symbolic link to ..//usr/lib/os-release')

>>> magic.detect_from_filename('/etc/redhat-release')
FileMagic(mime_type='text/plain', encoding='us-ascii', name='ASCII text')
```

However, it would add an external dependency, which we're relatively adverse to in general with `sos`.

Checking on our downstreams, this package is available for Fedora, RHEL 8 (in BaseOS), RHEL 9 (as `python3-file-magic`) and derivatives, Ubuntu since 18.04, and Debian stable. Given that libmagic is what is under the hood for the `file` command which would be present on any modern distro, I don't see a compelling reason to not take this route, except...

It is not however present on Google COS. Perhaps @xueweiz or @samkunz could weigh in on if this is a feasible addition?
