### ISSUE TITLE
Improve sos collect cleanup

### ISSUE THREAD

**Issue by npinaeva** [sosreport/sos#2882]
Problem:
interrupting sos collect on the `prep()` stage causes no cleanup even though cluster prep has already been executed and needs cleanup.

With a lot of different exit points and complex exceptions handling, it is not assured now that all the code pathes have cleanup calls. 
E.g. `collector.exit()` calls `cluster.cleanup()` first then some more actions then `self.cleanup()` https://github.com/sosreport/sos/blob/main/sos/collector/__init__.py#L492-L500.
and cleanup for `collector.execute()` looks different https://github.com/sosreport/sos/blob/main/sos/collector/__init__.py#L1157-L1158
and cleanup in `collector.collect()` is also different https://github.com/sosreport/sos/blob/main/sos/collector/__init__.py#L1215-L1216

Suggestion:
It would be nice to have some common `cleanup()` function that can be called before every exit point. Also adding try/finally block at least here https://github.com/sosreport/sos/blob/main/sos/collector/__init__.py#L1140-L1156 with cleanup being called in `finally`.
Some more changes may be required to be sure there is no code path without a cleanup call.

Unfortunately I am not aware about all resources sos collect uses, so I can't implement it myself

**Comment by TurboTurtle** [comment]
> Problem: interrupting sos collect on the `prep()` stage causes no cleanup even though cluster prep has already been executed and needs cleanup.
> [...]
> Suggestion: It would be nice to have some common `cleanup()` function that can be called before every exit point. Also adding try/finally block at least here https://github.com/sosreport/sos/blob/main/sos/collector/__init__.py#L1140-L1156 with cleanup being called in `finally`. Some more changes may be required to be sure there is no code path without a cleanup call.
> 

Ack, we should handle failures in `prep()` more distinctly. 


> With a lot of different exit points and complex exceptions handling, it is not assured now that all the code pathes have cleanup calls. E.g. `collector.exit()` calls `cluster.cleanup()` first then some more actions then `self.cleanup()` https://github.com/sosreport/sos/blob/main/sos/collector/__init__.py#L492-L500. and cleanup for `collector.execute()` looks different https://github.com/sosreport/sos/blob/main/sos/collector/__init__.py#L1157-L1158 and cleanup in `collector.collect()` is also different https://github.com/sosreport/sos/blob/main/sos/collector/__init__.py#L1215-L1216
> 

Let me break this out a bit.

> E.g. collector.exit() calls cluster.cleanup() first then some more actions then self.cleanup() https://github.com/sosreport/sos/blob/main/sos/collector/__init__.py#L492-L500.

Right. Here, we are exiting with an error encountered during our run, so we call both cleanups before exiting with a non-zero return code. The flow of `execute()` is so that we cleanup and then exit via the standard mechanisms of the python interpreter getting to the end of execution. Note that `self.cleanup()` here comes from `SoSComponent` and is centered around cleanup of the _local_ temp dir/resources. This is separate because:

> and cleanup in collector.collect() is also different https://github.com/sosreport/sos/blob/main/sos/collector/__init__.py#L1215-L1216

in this case we're exiting on a user interrupt. Historically there has been an assumption that a user hitting Ctrl-C to stop a given execution is equivalent to "I see a problem, let me dig into what's been done so far in the temp directory". Perhaps this assumption is no longer relevant, or maybe even just not relevant to `collect` like it is for `report`. But my point here is that in this specific case, this is intentional.

**Comment by npinaeva** [comment]
Thanks for looking into this!
So I think both exiting with an error and exiting "via the standard mechanisms of the python interpreter" can use the same function just with some `error_msg` parameter, since the cleanup probably should be the same?
Also, it's ok to have different exit sequences for different reasons, but I think maybe renaming this exit function with names specifying the reason (or maybe even having the same function, but with different reason flags) and reusing the code in these function to make it clear what steps are the same can help make exit flow more obvious?

So my main point is, I would like to have a single exit function maybe with different parameters that cleans everything up, but in a single place, so that I can be sure that my cleanup action will be executed no matter what is the reason for exiting. Don't know if it's possible though :)
