### ISSUE TITLE
PlugOpts val_type=str disallows numeric values (as strings)

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2922]
Example:

    # python3 bin/sos report -o skydive -k skydive.username=foo -k skydive.password='456' --batch --build
    
    sosreport (version 4.3)
    
    Plugin option 'skydive.password' takes string (no spaces), not int
    # python3 bin/sos report -o skydive -k skydive.username='123' -k skydive.password=foo --batch --build
    
    sosreport (version 4.3)
    
    Plugin option 'skydive.username' takes string (no spaces), not int
    #

It is arguable if numeric-only password is safe, or how meaningful is to have numeric-only username, but we should allow it. '123' is also a string.

**Comment by TurboTurtle** [comment]
Is the right answer to expand the `val_type` list for these options, or to change the type-handling flow when setting these options?

On a one-off basis, adding `int` as a `val_type` here makes no _functional_ difference, because the use of the value will be as a string anyways. I'm leaning towards changing the logic to just accept anything that could possibly be a string when the `val_type` is `str`, but I'm hesitant as I'm not sure if there are other edge cases we could catch then.

**Comment by pmoravec** [comment]
The change of logic "`val_type=str` => accept anything" does make sense to me.

**Comment by jcastill** [comment]
Do you mean modifying the logic inside sos/report/plugins/__init__.py in the class PluginOpt directly?

**Comment by pmoravec** [comment]
Yes.
