### ISSUE TITLE
bpf do not have net cmd on RHEL7

### ISSUE THREAD

**Issue by liuhangbin** [sosreport/sos#2959]
`plugins/ebpf.py` will collect `bpftool net list` info. But `bpftool` do not have net cmd on RHEL7. Which cause the sos report contains the usage message.

I think we should skip this cmd on RHEL7. e.g. bpftool help message on RHEL7

```
# bpftool -h
Usage: bpftool [OPTIONS] OBJECT { COMMAND | help }
       bpftool batch file FILE
       bpftool version

       OBJECT := { prog | map | cgroup }
       OPTIONS := { {-j|--json} [{-p|--pretty}] | {-f|--bpffs} }
```

**Comment by pmoravec** [comment]
We *can* collect such a command conditionally only, e.g. based on version of `bpftool` (am I right `net` subcmd is available since `bpftool-4`, while RHEL7 has `bpftool-3` only? Recall we need a distro-independent answer wrt the version of `bpftool`). But:

- currently, the only harm or inefficiency is that `sos` collects a redundant harmless command in some specific case
- we usually skip such commands *only* if it would be dangerous or unwanted (i.e. if calling such command would alter the system by loading a kernel module or starting a service). So if a user will sometimes miss `bpftool net list` command output, it might be more confusing for him/her *why* the command is missing.
- even if we fix it in upstream, to make it a real effect on RHEL7, it would have to be backported to RHEL7 (until some other distro would benefit from the change in upstream). With respect of RHEL7 lifecycle status, I dont expect such a backport would happen.

**Comment by liuhangbin** [comment]
> even if we fix it in upstream, to make it a real effect on RHEL7, it would have to be backported to RHEL7 (until some other distro would benefit from the change in upstream). With respect of RHEL7 lifecycle status, I dont expect such a backport would happen

Thanks for the explanation. Makes sense to me. I'm OK to close this issue.
