### ISSUE TITLE
sos clean domain mapper maps uppercase to lowercase?

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#3033]
Due to the change https://github.com/sosreport/sos/commit/cafd0f3a52436a3966576e7db21e5dd17c06f0cc , sos cleaner newly obfuscates uppercase domains to lowercase. Like:

    # grep sostest /var/log/messages
    Sep 24 09:39:08 pmoravec-rhel8 root[1416]: sostest: pmoravec-rhel8.mydomain.redhat.com
    Sep 24 09:39:08 pmoravec-rhel8 root[1418]: sostest: pmoravec-rhel8
    Sep 24 09:39:08 pmoravec-rhel8 root[1422]: sostest: PMORAVEC-RHEL8.MYDOMAIN.REDHAT.COM
    Sep 24 09:39:08 pmoravec-rhel8 root[1430]: sostest: PMORAVEC-RHEL8
    #

.. is obfuscated to:

    Sep 24 09:39:08 host0 root[1416]: sostest: host0.obfuscateddomain1.com
    Sep 24 09:39:08 host0 root[1418]: sostest: host0
    Sep 24 09:39:08 host0 root[1422]: sostest: host0.obfuscateddomain1.com
    Sep 24 09:39:08 host0 root[1430]: sostest: host0

Is this expected / right behaviour?

I tend to say so. On one side, cleaner does loose some information about capital letters. On the other side:
1) the unification of `DOMAIN` to `domain` is quite natural / expected
2) it would be quite hard to implement to strictly follow the lower|upper case in obfuscated strings while respecting the mapping is case insensitive

**Comment by TurboTurtle** [comment]
It is expected currently, yes, but is it right....that's up for debate.

I tend to lean toward it's acceptable because we're already changing the content of the file, so it shouldn't surprise users or support engineers that the file they're reading it in may not be exactly the same. I don't think it'd be actually that hard to implement lower/upper matching on the parsers - however it would take a performance hit (unsure how large). What would be fairly difficult to do would be case matching strings that aren't strictly all lowercase or all uppercase. E.G. `MY-hosT.DoMaIN.cOM` would be a bit of a nightmare to case-match, so I'd say we should just lowercase the entire obfuscated match in that case, which in turn makes me think we should just lowercase everything and be done with it.

**Comment by pmoravec** [comment]
Yeah I feel the performance hit (for every cleaner run) would not be sacrifised by the gain of improved obfuscation. So until there is a request raised, I would leave the current behaviour as desired.
