### ISSUE TITLE
[postfix] /etc/postfix/sasl_passwd is collected by sosreport

### ISSUE THREAD

**Issue by miztake** [sosreport/sos#3073]
The postfix plugin collects /etc/postfix/.
However, the following paths are not collected.

https://github.com/sosreport/sos/blob/2556e64b36a1f312e331589dc77146e35c6941e8/sos/report/plugins/postfix.py#L64-L68

On the other hand, smtp_sasl_password_maps in /etc/postfix/main.cf is typically set to /etc/postfix/sasl_passwd.
(refer to https://www.postfix.org/SASL_README.html)
/etc/postfix/sasl_passwd is not specified as a forbidden path, so it is collected by sosreport.

/etc/postfix/sasl_passwd contains the password,
so it should be specified in the forbidden path so that sosreport does not collect it.

**Comment by brozs** [comment]
There are multiple configuration options which may point to a map containing passwords. The following come to mind:

`lmtp_sasl_password_maps`
`smtp_sasl_password_maps`
`postscreen_dnsbl_reply_map`
`smtp_sasl_auth_cache_name`

A custom path is allowed, there are no defaults. It would require parsing of the configuration file.
Also, it would be better to scrub the individual map files rather than adding those to forbidden paths.

**Comment by TurboTurtle** [comment]
I believe this is resolved by #3077, which is now merged, so I'm closing this.

if there is still some part of this unaddressed, please feel free to re-open.
