### ISSUE TITLE
Describe the correct copyright notice in contributor guidelines

### ISSUE THREAD

**Issue by TrevorBenson** [sosreport/sos#3088]
I'm unsure if when I create a new file what the copyright line should be formatted as. I didnt find it searching the wiki for copyright, license, etc..

I can see it going two ways.  Red Hat, Current Year, and whoevers email address I see in any example copyright (meaning a maintainer like \@\TurboTurtle etc.)  OR Red Hat, Current Year and my email address as the author of the code.

1. Using someone elses name & email in the comments for the code/copyright seems odd.
2. Using my own name and email following a copyright notice from Red Hat seems somewhat odd as well.

Both of these could be considered normal and "bad form", it really depends on the preferences of the maintainer or organization. Explicitly describing the preferred copyright should improve accuracy of submitted PRs from outside contributors.

**Comment by pmoravec** [comment]
I stand for clarifying this. Since the `sos` project is distributed under [GPL 2.0](https://github.com/sosreport/sos/blob/main/LICENSE), I see the "copyright" rather as an authorship reference / kudos to the main contributor(s) of the plugin.

My proposal:
- have this written in Contributor Guideline that the main author (or very few authors) of a plugin should be written in initial comment in the form `Authorship: YYYY, FirstName Surname, [Organization,] [email]` (I am open to other format proposals)
- update the plugins accordingly (esp. the `s/Copyright/Authorship/g`

**Comment by TurboTurtle** [comment]
Even though we're an open source project and distributed under the GPL, the copyright line is still a necessity from a legal standpoint.

As far as the format goes - that is up to the contributor. You'll see a lot of copyright assignment to Red Hat since a lot of the project contributors do so while employed by Red Hat and do so on company time while working with other teams internal to Red Hat. To a lesser amount, you can find similar organization assignments for other companies such as IBM, Canonical, Rackspace, etc... But there is no project requirement to make the assignment to any particular org - those assignments come primarily from employer requirements on those making the contributions.

So, if you're not making the code contributions for an employer, then it's perfectly fine to keep the copyright assignment to yourself, e.g. `Copyright (C) 2022 John Doe <john@jdoemail.com>`. 

The determination of what "for an employer" is, is up to the individual and any contractual agreements they have. 


I can get this added to the contribution guidelines.

**Comment by TrevorBenson** [comment]
Thanks!

**Comment by TurboTurtle** [comment]
The [contribution guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines) article has been updated.
