### ISSUE TITLE
Questions and possible additions to contributions

### ISSUE THREAD

**Issue by TrevorBenson** [sosreport/sos#3113]
1. What is the target for the minimum Python version for sos 4.x?
2. Is a consistent style preferred over optimizations for contributions, like new transports for instance?
3. How to provide _An sos report archive generated using the changed code_ for submitted Pull Requests?

- I suspect the answer to the first question might be Python 3.6. 
- I ask the second as I often review other modules when generating a new one. When there isn't much homogeneity within the code I just optimize on the minimum Python version. When style and function code is consistent for most of the other files within a module I try to inherit it presuming the primary contributors might prefer this for maintainability.
- I don't believe files can be attached to the PR comments. I suspect maintainers don't want a file added to the branch from the PR and/or LFS. What would be the preferred method to share sample reports for pull requests?

**Comment by TurboTurtle** [comment]
> 1. What is the target for the minimum Python version for sos 4.x?

python-3.6
> 2. Is a consistent style preferred over optimizations for contributions, like new transports for instance?

Do you have a specific code example? I'm not sure I can answer this generically.
> 3. How to provide _An sos report archive generated using the changed code_ for submitted Pull Requests?

A publicly available file share such as a google drive link or similar is fine. That being said, we aren't very particular about this being provided for PRs (and I've thought about removing it from the guidelines a couple times). The only times I've personally asked for one was during bug investigation, and even then it's rare.

**Comment by TrevorBenson** [comment]
> Do you have a specific code example? I'm not sure I can answer this generically.

For example replacement of string interpolation with f-strings. Pretty much any Python 3.6 refactoring, such as things suggested by sourcery.ai with `python_version: '3.6'` applied.

> A publicly available file share such as a google drive link or similar is fine. That being said, we aren't very particular about this being provided for PRs (and I've thought about removing it from the guidelines a couple times). The only times I've personally asked for one was during bug investigation, and even then it's rare.

Then I'll skip the example collection (for my open PR) and use it if I open an issue on a bug.

Thanks

**Comment by TurboTurtle** [comment]
Ah. Traditionally, we haven't imposed any strict standards there....and that's had the obvious impact of mixed usage. Major reasons for that would be 1) sos is a fairly old project and has spanned a _lot_ of python versions, and 2) we have to support various python versions far longer than upstream python keeps them active (e.g. RHEL distros).

Since sos-4.0 however we've had a minimum python version of 3.6, whereas earlier versions we still had to support older pythons (both python3 and python2).

Personally, I've been using f-strings in any new development, and replacing where I can when making changes to existing code. But we haven't formally said "contributors should use f-strings from here on out" yet.

@pmoravec thoughts on making use of f-strings a formal style guideline? It's the recommended method from the PSF, and at "some point" the older string substitution functionality will be dropped. There are some aspects of f-strings that 3.6 doesn't support (such as the debugging `=` syntax), but I think those are easily worked around and when we stop supporting EL8 as a downstream (to be fair, that is a _long_ ways off) we won't _have_ to make those changes all at once.

**Comment by pmoravec** [comment]
> @pmoravec thoughts on making use of f-strings a formal style guideline? It's the recommended method from the PSF, and at "some point" the older string substitution functionality will be dropped. There are some aspects of f-strings that 3.6 doesn't support (such as the debugging `=` syntax), but I think those are easily worked around and when we stop supporting EL8 as a downstream (to be fair, that is a _long_ ways off) we won't _have_ to make those changes all at once.

I would add it as a recommendation. Contributors will automatically switch over to it once they first use it, I expect - at least for me it was an experience of more straightforward and readable code when I started to use f-strings. So imho a recommendation will suffice (till the older string substitution is supported - then we would have to do a mass replacement either way).

**Comment by TurboTurtle** [comment]
I have updated the [Contribution Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines) wiki page to reflect the recommendation of f-strings, minimum python version, and some other points.

PTAL and let me know if there are any other bullet points that should be there.

**Comment by TurboTurtle** [comment]
Closing this out at this time. If there are further questions, please feel free to either re-open this issue or create a new one.
