### ISSUE TITLE
[man] Update maintainer mail address

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#3290]
With @TurboTurtle leaving Red Hat, we shall update his email address at places like https://github.com/sosreport/sos/blob/main/man/en/sos.1#L168 or https://github.com/sosreport/sos/blob/main/man/en/sos-clean.1#L138 . Since he is **the** project maintainer, his name makes the most sense to me. But I am open to any other option there (more names, sos-devel mailing list, whatever applicable).

**Comment by TurboTurtle** [comment]
I'll get something up for this shortly.

**Comment by TurboTurtle** [comment]
Thinking more about it, perhaps something like this would be better:

```
MAINTAINERS
    Maintained on GitHub at https://github.com/sosreport/sos
```

We could also drop this section, to avoid having to update this again in the future.

**Comment by arif-ali** [comment]
As an example for the sos, I am the publisher, but that I can't change that esily, but the contact is set to `https://github.com/sosreport/sos/issues`, which means that they come here directly for anything related to the `sos` project rather than my email

Also, the AUTHORS file, the last time that was updated was like 6 years ago, does that need to be scrapped or updated :thinking:. I am sure we can get the list of authors by some git command
