### ISSUE TITLE
[libvirt] collect listing of /var/lib/libvirt/qemu

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#493]
/var/lib/libvirt/qemu contains libvit's running qemu configuration as well as crash dumps and state files (e.g. for suspended/migrating guests). This can be potentially large (dumps, state files) and is of limited interest. Collect a directory listing but not the content.

```
$ sudo ls -lR /var/lib/libvirt/qemu
/var/lib/libvirt/qemu:
total 16
srwxr-xr-x. 1 qemu qemu    0 Jan 16 10:37 capabilities.monitor.sock
drwxr-x---. 3 qemu qemu 4096 Nov 16 03:50 channel
drwxr-xr-x. 2 root root 4096 Mar  5  2014 dump
drwxr-xr-x. 2 qemu qemu 4096 Mar  5  2014 save
drwxr-xr-x. 2 qemu qemu 4096 Mar  5  2014 snapshot
```

vs.

```
$ sudo ls -lR /var/tmp/sosreport-localhost.localdomain-20150205132143/var/lib/libvirt/qemu
/var/tmp/sosreport-localhost.localdomain-20150205132143/var/lib/libvirt/qemu:
total 4
srwxr-xr-x. 1 root root    0 Jan 16 10:37 capabilities.monitor.sock
drwx------. 3 root root 4096 Feb  5 13:21 channel

/var/tmp/sosreport-localhost.localdomain-20150205132143/var/lib/libvirt/qemu/channel:
total 4
drwx------. 2 root root 4096 Feb  5 13:21 target

/var/tmp/sosreport-localhost.localdomain-20150205132143/var/lib/libvirt/qemu/channel/target:
total 0
srwxr-xr-x. 1 root root 0 Apr 22  2014 ol7-vm1.org.qemu.guest_agent.0
srwxr-xr-x. 1 root root 0 Aug  5  2014 ol7-vm2.org.qemu.guest_agent.0
```

**Comment by jcastill** [comment]
Bryn, if I'm not mistaken, this has been fixed by you already in the following commit, right?

commit 60373759aaa9f0668f0200e000e6c1949334597b
Author: Bryn M. Reeves <bmr@redhat.com>
Date:   Tue Jun 30 13:10:51 2015 +0100

    [libvirt] add listing of /var/lib/libvirt/qemu
    
    Signed-off-by: Bryn M. Reeves <bmr@redhat.com>

diff --git a/sos/plugins/libvirt.py b/sos/plugins/libvirt.py
index 8d5dcfc0..0b31d311 100644
--- a/sos/plugins/libvirt.py
+++ b/sos/plugins/libvirt.py
@@ -59,6 +59,8 @@ class Libvirt(Plugin, RedHatPlugin, UbuntuPlugin, DebianPlugin):
         if os.path.exists(libvirt_keytab):
             self.add_cmd_output("klist -ket %s" % libvirt_keytab)
 
+        self.add_cmd_output("ls -lR /var/lib/libvirt/qemu")
+
     def postproc(self):
         for loc in ["/etc/", "/var/run/"]:
             for xmlfile in glob.glob(loc + "libvirt/qemu/*.xml"):

So if nothing else needs to be done, can we close this?

**Comment by bmr-cymru** [comment]
Yep, I just came here to close it :-)
