### ISSUE TITLE
[Plugin] sosreport -e option doesnot capture plugin details when used in combination with profiles (-p) option.

### ISSUE THREAD

**Issue by poornimakshirsagar** [sosreport/sos#504]
The "sosreport -e" command-line option should capture plugin-specific information at desired location in sos tar file. It works individually but fails if used in combination of profiles option.
If we use -e with -p option, plugins fails to do capture relative details.
- Steps to Reproduce:

For example enable any inactive plugin with profiles option

```
# sosreport -e abrt -p sysmgmt  
....
 Setting up archive ...
 Setting up plugins ...
 Running plugins. Please wait ...    ==> plugin run is not successful

  Running 1/3: general...        
  Running 2/3: ldap...        
  Running 3/3: yum...  
....
```
- Expected results:

All plugins specific configuration files must be captured at relative location in sosreport tar file.

```
Terminal output must show plugin run successful.
....
 Setting up archive ...
 Setting up plugins ...
 Running plugins. Please wait ...

  Running 1/69: abrt...
....
```

**Comment by poornimakshirsagar** [comment]
Few observations with (-e) and (-p) behaviour:

1. Run sosreport using first (-p)profile and then (-e)plugin ==> plugin fails check uilogs and sos.txt plugin info not captured.
2. using first (-e)plugin and then (-p)profile option ==> plugin fails check uilogs and sos.txt plugin info not captured
3. enable plugin only(-e) ==> works as expected.
4. only plugin (-o)==> works expected.

**Comment by bmr-cymru** [comment]
This is behaving as designed. The `-e/--enable-plugins` options enables plugins that *would otherwise be disabled*. I.e. default-off plugins (we don't have many today). Being outside of a profile is a stronger exclusion - those plugins just don't exist unless listed on the command line with `-o/--only-plugins`. We do need to update the docs to make this more clear and to extend the description of `-o` to mean "only these additional plugins (beyond those specified by the active policy)".

Long term we will probably drop '-e/--enable-plugins` as it's kinda confusing and not very useful with the current plugin set. It's a legacy of the original sos-1.x design that foresaw users manually enabling plugins for particular support cases: turns out that doesn't work very well in practice.

**Comment by poornimakshirsagar** [comment]
Yes --enable-plugin is bit confusing as it was in design many old sos users liked it. Anyway  
@bmr-cymru as mentioned  '-e/--enable-plugins` will be drop any plans by which release? do we have patch or GitHub Issue Tracker for it ?

**Comment by bmr-cymru** [comment]
No plans as yet.. mostly due to the importance placed on it by various testers.

I'm still inclined to consider this as a doc bug - the plugin *is* being enabled, it is just excluded from the set to run unless also given as `-o plugin`.
