### ISSUE TITLE
[RFE] Please include the output of "blockdev --report"

### ISSUE THREAD

**Issue by saintpai** [sosreport/sos#582]
Hello,

We need a way to record the output of "blockdev --report"

We are dealing with performance issues from those who use data analytics software such as SAS. It is noted that SAS specifically suggests that the blockdev command be used to increase readahead on the block devices. But this recommendation is frequently ignored.

The blockdev command is from util-linux-ng on RHEL 6 and util-linux on RHEL 5. We may presume its always available.

I have created a patch and shall attach it here. Please include it if you see fit.

Thanks and regards,
-- Pai

**Comment by bmr-cymru** [comment]
I've added this to the block plugin. Note that when we add full /sys collection for block devices this will be somewhat redundant but at least it provides nicely formatted output for human viewers.

This will likely appear in future RHEL6 and RHEL7 updates however since RHEL5 is now in maintenance phase it is unlikely we will add it there.

Thanks for the report!
