### ISSUE TITLE
Print meaningful error messages

### ISSUE THREAD

**Issue by g0dd4rd** [sosreport/sos#613]
Description:
I edited the /etc/sos.conf and forgot to assign "on" value to apache.log tunable and saved. On next run, I got an exception.
Actual result:
sudo sosreport -l
Traceback (most recent call last):
  File "/sbin/sosreport", line 23, in <module>
    main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/sos/sosreport.py", line 1228, in main
    sos = SoSReport(args)
  File "/usr/lib/python2.7/site-packages/sos/sosreport.py", line 528, in __init__
    self._read_config()
  File "/usr/lib/python2.7/site-packages/sos/sosreport.py", line 627, in _read_config
    self.config.readfp(open(config_file))
  File "/usr/lib64/python2.7/ConfigParser.py", line 324, in readfp
    self._read(fp, filename)
  File "/usr/lib64/python2.7/ConfigParser.py", line 546, in _read
    raise e
ConfigParser.ParsingError: File contains parsing errors: /etc/sos.conf
	[line 17]: 'apache.log\n'

Expected result:
ConfigParser.ParsingError: File contains parsing errors: /etc/sos.conf
	[line 17]: 'apache.log\n' - missing value [on|off]

Steps to reproduce:
1. open /etc/sos.conf
2. add:
[plugins]
enable = apache
[tunables]
apache.log
3. save
4. sudo sosreport -l

**Comment by Akasurde** [comment]
We can close this issue as PR is merged.

**Comment by bmr-cymru** [comment]
It happens because your commit message referenced the pull number (#739) instead of the issue number (#613). You can prevent this by including both numbers in your commit - or, even better - if you have a patch in mind already do not open an issue: just send a pull request. Only open an issue if you don't think you will be able to provide a fix within a few days or weeks.

If you need to clean up and manually close just leave a final message that shows the actual commit ID that was merged to master:

Closed in commit 8ef27fa80589fcda452fc1c27c1fc6a0fb385b4a.

**Comment by Akasurde** [comment]
Sure. Thanks.

**Comment by bmr-cymru** [comment]
:+1:
