### ISSUE TITLE
[conf] allow whitelisting plugins by name

### ISSUE THREAD

**Issue by mrbriancollins** [sosreport/sos#649]
It would be nice to have an "only" option to be able to enable only the listed plugins in the sos.conf like the function of the -o option from the currently existing command line.

**Comment by bmr-cymru** [comment]
Thanks! I'd not spotted the new issue when I replied on the mailing list. This is quite simple to implement (it's the mirror feature of the existing disable list: it just needs to use the -o plugin selection path instead of the -n logic - all the infrastructure is already there).

I'll tag this for 3.3. so it should be in the next release (mid October) - this will start to show up in distributions in roughly 6-12 months depending on their release schedules.

**Comment by TurboTurtle** [comment]
Closing this, as this was resolved a while back by #1530
