### ISSUE TITLE
process: enhance output for ps regarding threads

### ISSUE THREAD

**Issue by alexandrujuncu** [sosreport/sos#668]
The information about threads (Light Weight Processes) is not visible in current process module.
The file ps_auxwwwm does list the threads of a process but not really useful information about the process and thread group and pstree shows threads but information is not ease to grep.

I suggest adding the output for command:
ps -elfL

It treats all processes as threads, so single thread processes have one line and for multi-threaded processes, you just get the individual threads (not separate process entry).

Thanks!

**Comment by bmr-cymru** [comment]
I'm not massively keen on this; not because I don't think the information is useful but because I do not think it is sustainable to just keep adding more `ps` invocations for every speck of information people might want to obtain.

This has implications for both maintenance (it creates another data point where we may need to break compatibility in the future) and runtime costs: running ps is not free and running it three times with slightly different options further compounds that. Running the tool multiple times also introduces a drift problem in the data: short lived processes may only exist in one or the other set leading to confusing results.

Some work has been done towards collecting the entire `/proc/${PID}` tree but this has stalled due to performance problems (~30m to collect the tree on systems with many processes).

Given that `ps` is already an efficient `/proc/${PID}` walker/parser I think it may be worth putting some effort into a design that attempts to collect *all* relevant `ps` fields for all processes in a single pass and storing them in some data structure (probably a dictionary in memory and a JSON object on-disk). From this master capture the information from the various different invocations can then be obtained.

I know this is a lot more work and more difficult than the proposed patch but I do not think we can keep up with the piecemeal approach much longer.

**Comment by alexandrujuncu** [comment]
I understand your concerns and I would say the same thing. The only reason why I am suggesting this is because I had so many cases where I needed this information and it wasn't there.

Having a snapshot of procfs would be awesome. Also for devtmpfs and sysfs would be nice. Having all the date available and then building tools (or using existing ones) to read them would be worth it in the long run.
The only two issues I see is consistency of data (can we get the dump in actual real time, or at least at the speed of ps so the information of the first process is synced with the one of the last one) and privacy (is there anything in procfs that we don't want to get because it can be considered critical information for clients).

Thanks!

**Comment by bmr-cymru** [comment]
We have been working toward more complete sysfs capture for several years: some of this is already present in 3.2 but it is difficult to get right and required a large number of fixes in the archive and file collection code. It's slow going unfortunately & few people want to work on it.
