### ISSUE TITLE
[sosreport] exit status propagation is broken

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#672]
David Kutalek pointed out:

```
# sosreport -o fooble

sosreport (version 3.2)

a non-existing plugin (fooble) was specified in the command line
# echo $?
0
```

The use of `SystemExit` in `SoSReport._exit()` interacts badly with exception catching blocks at the tail end of `SoSReport.execute()`.

**Comment by bhavikbhavsar** [comment]
Following is my thought process behind this issue.

* `sos.execute()` checks for unknown plugin
line 1573 ->  `self._check_for_unknown_plugins()`

* line 1070 -> `_check_for_unknown_plugins()` exits with error code 1

* line 805 -> 
```python
_exit(self, error):
  raise SystemExit()
```
Error code is not being used in SystemExit,  hence it can be changed to raise `SystemExit(error)`

* This exception would be handled at line 1600 -> `except (OSError, SystemExit, KeyboardInterrupt):`

I understand that motive here is to do some clean up task before exiting.
Suggestion here is to catch exception object as to_be_raised, so that it can be used later.
`except (OSError, SystemExit, KeyboardInterrupt) as to_be_raised:`

and raising it at the end once clean up task would be completed.
`raise to_be_raised`

Test Result -
echo $?
1

Diff 
```python
root@bhavik-Dell-System-XPS-L502X:~# git diff b/sos/sos/sosreport.py a/sos/sos/sosreport.py 
diff --git a/b/sos/sos/sosreport.py b/a/sos/sos/sosreport.py
index f61ea4a..23ba420 100644
--- a/b/sos/sos/sosreport.py
+++ b/a/sos/sos/sosreport.py
@@ -803,7 +803,7 @@ class SoSReport(object):
             pdb.pm()
 
     def _exit(self, error=0):
-        raise SystemExit()
+        raise SystemExit(error)
 #        sys.exit(error)
 
     def get_exit_handler(self):
@@ -1597,7 +1597,7 @@ class SoSReport(object):
 
             return self.final_work()
 
-        except (OSError, SystemExit, KeyboardInterrupt):
+        except (OSError, SystemExit, KeyboardInterrupt) as to_be_raised:
             try:
                 # archive and tempfile cleanup may fail due to a fatal
                 # OSError exception (ENOSPC, EROFS etc.).
@@ -1609,7 +1609,7 @@ class SoSReport(object):
                     rmtree(self.tmpdir)
             except:
                 raise
-
+            raise to_be_raised
         return False
```
