### ISSUE TITLE
haproxy should understand the include directive

### ISSUE THREAD

**Issue by mbaldessari** [sosreport/sos#674]
Currently the haproxy plugin only fetches:
        self.add_copy_spec("/etc/haproxy/haproxy.cfg")
        self.add_cmd_output("haproxy -f /etc/haproxy/haproxy.cfg -c")
        self.add_copy_spec("/var/log/haproxy.log")

It makes sense to check haproxy.cfg for any include directive and fetch those files as well.
I found at least one distro that uses "include conf.d/*.cfg"

**Comment by bmr-cymru** [comment]
I'm not a fan of this sort of thing for the general `include` case; if there is a "standard" location (e.g. the `conf.d/*.cfg` that you mention) then I think it's fine to add collection of that location (similar to apache's `conf.d`) however I am much less open to the idea of parsing configuration files in sos in order to find other locations - we do have one example like this (although for logs rather than configuration) where we attempt to parse `{r,}syslog` files for additional log destinations but it's ugly and has been a pain to maintain in the past.

If we're going to go down this route at all then I think it should be done in a general fashion - that really needs something like Augeas to provide an abstraction to access the configuration (note: I'm not even sure Augeas expresses this right now or whether it simply parses all disovered `include`ed files into a single configuration tree).

**Comment by mbaldessari** [comment]
Agreed. Shall we just add /etc/haproxy/conf.d/*.cfg for now and file a more general issue to cater for the include directive interpretation?

**Comment by bmr-cymru** [comment]
Yep I think that's probably the best approach to begin with - we can tag that for 3.3 and leave the more general case for a later time.
