### ISSUE TITLE
Is sosreport available on SUSE?

### ISSUE THREAD

**Issue by plutoid** [sosreport/sos#709]
Hi Authors,

I try to add below suse.py policy file, but it still doesn't work on SUSE yet, is it available to run sos on SUSE system?

https://raw.githubusercontent.com/sosreport/sos/bmr-suse-policy/sos/policies/suse.py

BRs,
Hua

**Comment by plutoid** [comment]
I found there is one veriosn that could support suse generate sosreport logs, is there plan  to support SuSE in future for the master branch?

https://github.com/sosreport/sos/archive/41f3c62d6cde2df904676cb5ee7d6ae2c39b9d28.zip

**Comment by bmr-cymru** [comment]
I created a basic policy a while back but without testing and feedback from the users of the distribution we can't merge it.

I'd be happy to include this in the next release if we can get a reasonable level of testing done.

**Comment by plutoid** [comment]
Thanks for your reply, I'm not sure what mean of 'reasonable level of testing'? Hope it release with SuSE support.

**Comment by bmr-cymru** [comment]
We just need feedback on whether the current set of plugins works well on a SuSE installation. Since we don't have any SuSE-specific plugins today I've enabled the RedHatPlugin set for the SuSE policy. This means the 113 plugins that work on Red Hat will all try to run on SuSE now - some of them may use the wrong package names, file system paths, command names or switches etc. for the distribution so we need to get feedback on any missing or incorrect data.

I've added the SuSE policy to master now so it will be included in the next sos release (3.3). If someone wants to package it for OpenSuSE then we can help with any changes that are needed to build on the distro.

**Comment by bmr-cymru** [comment]
If you clone the repo on a SuSE install you can build an RPM package for it using either Python `distutils` or the legacy Make-based build scripts:

```
$ make rpm
```

```
$ python setup.py bdist_rpm
```

You'll need to have the appropriate rpm build and other packages installed.

**Comment by bmr-cymru** [comment]
sos-3.3 has been released with SuSE policy support: please file a new issue if you see any problems with the release.
