### ISSUE TITLE
[RFE] Add lstopo output to sosreport (or equivalent data providing same information)

### ISSUE THREAD

**Issue by herton** [sosreport/sos#719]
It would be useful for sosreports to contain output or data showing machine topology/numa node information, so one can know which devices or memory are assigned to which node. One utility which outputs such data is the lstopo utility (eg. /usr/bin/lstopo-no-graphics from hwloc package in Fedora).

It's desired some times to know what PCI devices are attached to what numa node (on multi node systems), for example for diagnostic purposes (example: in a virtualized environment, you may want to check if the guest with a device assigned to it is pinned to same physical CPUs on the same numa node as the device, for performance reasons), irq affinity assignment (eg. you may want to check if on certain device irqs are being served on CPUs on the same numa node of device and adjust affinity based on numa information...) etc.

For PCI devices for example, numa information is exported in Linux through /sys/devices/pci*/*/numa_node. As far as I could see, at least this is not provided in sosreports yet (looking at sosreport created on RHEL or Fedora 23).

If you don't want to include lstopo output or require hwloc to be installed, my suggestion is that you run hwloc-gather-topology, see the tarball it creates (with files from /proc and /sys), and include the same files in the sosreports. Thus one can then lstopo -i with directory pointed to a extracted sosreport.

**Comment by herton** [comment]
Note: hwloc-gather-topology must be run with --io option to include all relevant /sys files (without --io numa_node files for pci devices are not included...).

**Comment by pmoravec** [comment]
(I cant find `--io` option, do you mean `--whole-io`?)

What about to:

- create new plugin "lstopo" (since the data to be collected hardly match any plugin - but feel free to suggest one). The plugin will be enabled by presence of `hwloc` package (only).
- collect outputs of 2 commands:

````
lstopo-no-graphics --whole-io
lstopo-no-graphics --whole-io lstopo.xml
````

The second command stores file in `xml` format that can be used as input of `lstopo -i lstopo.xml` to generate graphics locally in whatever output format.

The advantage is that one can generate the graphical output even for systems without graphics, the plugin does not need to decide if `hwloc-gui` is installed or not and plugin output files would be the same all the time.

Comments or suggestions?

**Comment by herton** [comment]
The --io option I mention is the one to be used with /usr/bin/hwloc-gather-topology, if that was the path to be taken. On case of lstopo, indeed the option to be used is --whole-io.

I'm ok with your approach and using lstopo-no-graphics, having a quick way to see the topology etc. on sosreports would be great.
