### ISSUE TITLE
[sosreport] missing help message for list-profiles

### ISSUE THREAD

**Issue by Akasurde** [sosreport/sos#726]
When user do `sosreport --help`, for `--list-profiles` there is no help message.

We can add a short message for `--list-profiles` in help message.

**Comment by bmr-cymru** [comment]
The tag should be `[sosreport]` since this is a change to the sosreport command subsystem (`[help]` isn't a recognised subsystem - the tags are there to help search for related changes so it is important to use the existing project conventions for these).

Please change the tag with `git commit --amend` and then update the PR using `git push --force`.

**Comment by Akasurde** [comment]
OK

**Comment by bmr-cymru** [comment]
Thanks!
