### ISSUE TITLE
[networking] netstat truncates IPv6 addresses

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#734]
`netstat -neopa` truncates IPv6 addresses. Option `-W` / `-T` for `net-tools` version `>=2` / `<2` should be added to fix it.

**Comment by bmr-cymru** [comment]
The real problem here is the need for separate switches for different versions... It's doable but distinctly ugly :-(

**Comment by pmoravec** [comment]
One option is command switches based on `net-tools` version, another is collect both commands outputs and either store them, or keep just the relevant one.

In this option, one gotcha is `netstat -T` on version `>=2` has return value zero, so one would have to check `netstat_output['output'][0]` starting by `netstat: invalid option`.

**Comment by bmr-cymru** [comment]
You seem to think our package manager version checks work :-)

I don't like the idea of treating these as separate commands - to the user they're the same data and it's a quirk of distro history that the switches were once different (we can use `suggest_filename` to force the name to the old name so users will not see any change).

**Comment by bmr-cymru** [comment]
OK so see also issue #763 - we can do this with the current package manager abstraction but it is eye-wateringly ugly :-)

I'll commit a fix for this issue first since the changes to the policy classes are likely to be extensive. That way downstreams that want to fix the `netstat` collection can cherry-pick that change without pulling in the rest.
