### ISSUE TITLE
[sosreport] Change UI in sos html_report

### ISSUE THREAD

**Issue by Amitgb14** [sosreport/sos#749]
Current html report ui is basic, I have plane to add bootstrap ui framework to make beautiful html report.

**Comment by Amitgb14** [comment]
@bmr-cymru and @battlemidget, please share your point.

**Comment by battlemidget** [comment]
Well we want to be able to use SOMA (sos object model archive) which we could build reports off however we see fit. I'm not sure adding more reporting UI in the code is the right way forward

**Comment by bmr-cymru** [comment]
I guess @Amitgb14 means "beautifying" the generated HTML rather than adding any actual "interactive UI" to the reports?

Either way - as Adam states, for anything complex/extensive, we'd really like to see corresponding improvements in the model sos uses to capture and store data. There is a proposal on the table for adding this (although it's lacking a lot of detail right now).

Simple improvements to the look of the reports are welcome however.

**Comment by Amitgb14** [comment]
My point is to change looking style by adding bootstrap css from 
```
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
      <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap-theme.min.css">``` 

[sos_html.zip](https://github.com/sosreport/sos/files/104678/sos_html.zip)

**Comment by bmr-cymru** [comment]
I like the look of the example you provided. I'd be a bit concerned about making sos HTML depend on http resources however - it may be viewed in situations with no network connectivity, or after many years have passed (how long will bootstrapcdn be guaranteed to be around for?).

I think what we need to do is to find a look and feel that works for sos and then implement that in sos somehow - whether by generating the CSS on-the-fly or by including some template file within the package.

**Comment by Amitgb14** [comment]
@bmr-cymru , you're point is correct and it's not good to add css static files in sos report.
I've plan to start another project to provide web UI for sosreports. I'm started working on it but it required sos.json format report. #90
