### ISSUE TITLE
[systemd] collect journalctl --disk-usage

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#750]
Although `sos_commands/logs/journalctl_--all_--this-boot_--no-pager_-o_verbose` can provide rough estimate of the same, it is worth taking the precise disk usage.

**Comment by bmr-cymru** [comment]
> can provide rough estimate of the same, it is worth taking the precise disk usage.

No, it doesn't :)

The *TOTAL* of all logs (all units, all boots) *approximates* the disk usage (strictly speaking it the actual disk usage is an upper bound on the sum of all log data - this must be true since the on-disk data always has additional (metadata + overhead) space use associated with it).

A sum of just `--all --this-boot` is not a rough estimate of anything very helpful.
