### ISSUE TITLE
sosreport doesn't collect grub configurations on uEFI environment

### ISSUE THREAD

**Issue by kiiofkirc** [sosreport/sos#766]
For sos-3.x on RHEL7, sosreport doesn't collect any grub configurations
for x86 uEFI systems. Because grub2 plugin is not enabled on the systems.

The plugin is enabled if the 'grub2' package is installed, however
RHEL7 on uEFI environment installs the 'grub2-efi' package instead of
the 'grub2" package.

So, 'grub2-efi' should be added to 'packages' variable in sos/plugins/grub2.py.

[ sos/plugins/grub2.py ]

```
  class Grub2(Plugin, RedHatPlugin, DebianPlugin, UbuntuPlugin):
      """GRUB2 bootloader
      """

      plugin_name = 'grub2'
      profiles = ('boot',)
      packages = ('grub2', 'grub2-efi')
                           ===========
                               here
```

**Comment by bmr-cymru** [comment]
Thanks for the report. I don't think adding the `grub2` package is the correct fix though: we will probably need to add separate plugins for the different distributions since their packaging of `grub2` is likely to differ.

The real problem here is that in Red Hat packaging the `grub2` RPM is not the main package: both `grub2` (non-EFI boot on x86) and `grub2-efi` are sub-packages of the `grub2` source RPM that ship the required boot executables for the different methods. For `grub2` that is the grub2 32-bit ELF binaries (and MBR/bootstrap code) whereas for `grub2-efi` it is the grub2 PE32+ EFI Application executables.

Rather than depend on either of these arch-specific packages it's better to depend on a common package that they both require. In this case (for Red Hat) that's the `grub2-tools` RPM:

```
# rpm -q --requires grub2
/bin/sh
config(grub2) = 1:2.02-0.34.el7_2
dracut
dracut
file
gettext
grub2-tools = 1:2.02-0.34.el7_2
os-prober
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
which
rpmlib(PayloadIsXz) <= 5.2-1
```

```
# rpm -q --requires grub2-efi
config(grub2-efi) = 1:2.02-0.34.el7_2
grub2-tools = 1:2.02-0.34.el7_2
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
```

(note that `--requires` lists the requirements of the package given, not the packages that require it).

For Red Hat this is fairly simple:

```python
    class RedHatGrub2(Plugin, RedHatPlugin):
        packages = ('grub2-tools',)
```

We'll need input from the other distribution maintainers though to understand the packaging structure on non-Red Hat distributions.

**Comment by kiiofkirc** [comment]
Thank you for your comment and quick response.
I agree with separating plugins for the different distributions and
changing to common package for Red Hat.

**Comment by pmoravec** [comment]
> We'll need input from the other distribution maintainers though to understand the packaging structure on non-Red Hat distributions.

@battlemidget , could you comment for at least Ubuntu?

**Comment by pmoravec** [comment]
Some update @kiiofkirc or @battlemidget ?

**Comment by battlemidget** [comment]
Heres our rdepends:

```
ubuntu@conjure-up-runner:~/spells$ apt-cache rdepends grub2
grub2
Reverse Depends:
  grub-efi-amd64
  grub-coreboot-bin
  grub-coreboot
  grub-pc-bin
  grub-pc
  grub-ieee1275-bin
  grub-ieee1275
  grub-efi-ia32-bin
  grub-efi-ia32
  grub-efi-amd64-bin
  grub-efi-amd64
  grub-coreboot-bin
  grub-coreboot
  grub-pc-bin
  grub-pc
  grub-ieee1275-bin
  grub-ieee1275
  grub-efi-ia32-bin
  grub-efi-ia32
  grub-efi-amd64-bin
  friendly-recovery
ubuntu@conjure-up-runner:~/spells$ apt-cache rdepends grub2-common
grub2-common
Reverse Depends:
  shim-signed
  grub-coreboot
  grub-efi-amd64
  grub-xen
  grub-pc
  grub-ieee1275
  grub-efi-ia32
  grub-efi-amd64
  vmdebootstrap
  grub-coreboot
  shim-signed
  grub-xen
  grub-pc
  grub-ieee1275
  grub-efi-ia32
```

It does look like relying on grub2 is sufficient in deb/ubuntu
