### ISSUE TITLE
[cluster] log error message print before running plugins

### ISSUE THREAD

**Issue by Amitgb14** [sosreport/sos#806]
```
 Setting up archive ...
 Setting up plugins ...
[plugin:cluster] crm_from parameter 'True' is not a valid date: using default
 Running plugins. Please wait ...
```
cluster plugin error message print on wrong position while running ```./sosreport -a``` command.
I check cluster plugin, the error message describe inside setup() method line no.112. I think it should be print when cluster plugin running. Current log not looking good.

**Comment by bmr-cymru** [comment]
It's actually doing exactly what it says it will do when you use that option:

```
       -a, --alloptions
              Set all boolean options to True for all enabled plug-ins.
```

Technically all options are "possibly boolean" since we have no type enforcement system for them. If you use `-a` then all options will be set to `True` and plugins have to filter them. When this filtering was originally added for cluster the developer chose to print a warning message.

So it's debatably a minor bug in the cluter plugin leading to a cosmetic nuisance. Possibly worth fixing but not of great priority.

**Comment by bmr-cymru** [comment]
I don't think there's any major improvement to make here for now - if anything we could just delete this warning message entirely.

I don't think that outputting this warning during collection would be any better than during setup.
