### ISSUE TITLE
unexpected keyword argument 'sysroot'

### ISSUE THREAD

**Issue by houstar** [sosreport/sos#809]
Traceback (most recent call last):
  File "/usr/sbin/sosreport", line 25, in <module>
    main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/sos/sosreport.py", line 1592, in main
    sos = SoSReport(args)
  File "/usr/lib/python2.7/site-packages/sos/sosreport.py", line 676, in __init__
    self.policy = sos.policies.load(sysroot=self.opts.sysroot)
  File "/usr/lib/python2.7/site-packages/sos/policies/__init__.py", line 38, in load
    cache['policy'] = policy(sysroot=sysroot)
TypeError: __init__() got an unexpected keyword argument 'sysroot'

**Comment by bmr-cymru** [comment]
It seems like you have a broken installation or perhaps are using a buggy or untested policy - for any policy related issue it is useful to include the distribution you are running on since that determines the policy that will be loaded.

If you are using sos from current git then you should find that the `Policy` class constructor accepts a `sysroot` keyword argument:

```python
class Policy(object):
[...]
    _in_container = False
    _host_sysroot = '/'

    def __init__(self, sysroot=None):
        """Subclasses that choose to override this initializer should call
        super() to ensure that they get the required platform bits attached.
        super(SubClass, self).__init__(). Policies that require runtime
        tests to construct PATH must call self.set_exec_path() after
        modifying PATH in their own initializer."""
        self._parse_uname()
        self.report_name = self.hostname
```

I'll close this pull request as deleting the `sysroot` argument is certainly not the right fix - this will break all `sos` container use cases since this policy argument is required in order to find the host file system in a super-privileged container configuration.

Please open an issue including the sos version, your distribution and distro version.

Actually, just a guess but are you running SuSE? We only recently merged the policy for this distribution (as we had not received any testing feedback from users) - I have done some limited testing in a VM but not since the policy was first written.

**Comment by bmr-cymru** [comment]
Assuming you're using SuSE please give the patch in the above comment a try - although this does not implement full `sysroot` support for the distro (I'm not sure if/what container model they are using right now) it should prevent the exception during policy load.

**Comment by houstar** [comment]
Thanks Bryn. upstream commit '6a239ddeb5de9a04e7e7081ea6' passes sysroot to policies classess, making container aware of underlying host filesystem. The upcoming policy must be aware this.
