### ISSUE TITLE
[openstack_*] implement --verify checks

### ISSUE THREAD

**Issue by iranzo** [sosreport/sos#871]
Hi,
It's somewhat common for users to do changes and update libraries manually for OSP environments, so the RPM database is out of sync with current real status of the system.

Having the output of rpm -Va would help, but it's disabled by default as it's time consuming, so instead, it would be nice to have it for typical openstack component rpm's (rabbit, _openstack_, etc).

**Comment by bmr-cymru** [comment]
This just needs the OpenStack plugin maintainers to add `--verify` support (see the `rpm`, `autofs`, and `systemd` plugins for examples).

**Comment by iranzo** [comment]
Could then convert this issue into enabling it by default if osp plugin is triggered?

**Comment by bmr-cymru** [comment]
If the OpenStack maintainers wanted to do that it is possible but I can't really speak for them on the specifics of how they'd want this to behave and I wouldn't really encourage that (unless there is something special about OpenStack that means it regularly eats its own binaries on-disk, but then it would seem it has bigger problems..).

The point is that there needs to be some active engagement in the process by the user, or by the person asking the user to run commands.

The `--verify` switch has been there for a long time now, it is well documented, and it should be used whenever there is a suspicion that package contents could have been altered.

The conversation should be a bit like:

```
Customer: "Hi! We have a problem.."
Support: "Please send a sosreport"
Customer: "OK, here it is."
Support "Hmm. Well, everything looks OK configuration-wise, but we can see that programs or libraries on the system aren't behaving as we'd expect. We'd like to get a new sosreport, with verification enabled, that will give a deeper insight into any changes that may be present, you can run the command as ...".
```

I get the impression (from several cases I've watched) that this is not happening; either because people don't know about the options, or because they don't think to use them.

We killed default `rpm -Va` after RHEL5 for very good reason - customers complained about very long run times and the volume of IO load far more frequently than the -Va data actually helped to resolve a case.

**Comment by pmoravec** [comment]
My understanding was:

- osp plugin wont call whole "rpm -Va"
- just "rpm -Va <list-of-OSP-related-packages>" to be called
- that command will be enabled by `--verify` option with default value `true`

So by default, only when osp plugin is enabled, it will "rpm -Va" "just" osp related packages.

What is usual/expected time of execution of "rpm -Va <list-of-OSP-related-packages>"?

**Comment by bmr-cymru** [comment]
*nothing* *ever* calls `rpm -Va` except the `rpm` plugin and then, only if the `rpm.rpmva` option is given!

The `-a` in that command means "for all packages".

See the minimal verify that the `rpm` plugin does for its `verify_list` of packages - really this should be generalised as a `Plugin` class interface, e.g.:

```python
    def add_package_verify(package):
    """ Add a package name to the list of packages to be verified by this plugin.
    """
    self.verify_list.append(package)

    def _verify_packages():
        for package in self.verify_list:
            self.policy().package_manager.verify(package)
```

The `_verify_packages()` function is either hooked into the `Plugin.collect()` path, or we define a new `Plugin.verify()` path that is called following the collection phase.

The verification may be more efficiently carried out by building a space-separated string list of package names and issuing a single verify command: this is how the `rpm` plugin currently handles it (the downside is that everything is jammed together in a single output file).

Deciding which is best may require some experimentation.

The main blocker to implementing this is adding hooks to the `Policy` and `PackageManager` classes and smoothing over any variation in different distributions.

**Comment by bmr-cymru** [comment]
> What is usual/expected time of execution of "rpm -Va "?

It's a meaningless question: it's a function of the number of packages installed, their size, the size and number of files they contain, the relative speed of the file system layout, block device, and storage, the current load and any IO congestion on the system etc. etc. etc.

"finite but potentially large" is about as general as you can get.

**Comment by pmoravec** [comment]
Ah sorry, I meant `s/rpm -Va/rpm -V/` for the package list.

**Comment by bmr-cymru** [comment]
:+1:

**Comment by pmoravec** [comment]
So the intention is, that:

- every(?) openstack_* plugin shall have option `--verify`, disabled(?) by default
- if the option is enabled, `rpm -V <osp-package-list>` will be run
- here `<osp-package-list> will be exactly those packages that `packages = ..` is set to

Am I right?
