### ISSUE TITLE
sos report doesn't minimize the amount of temporary disk space used

### ISSUE THREAD

**Issue by stuart-mclaren-hpe** [sosreport/sos#873]
This is maybe more general feedback than a specific issue / feature request.

Feel free to ignore -- I just wanted to note it, in case it hadn't been mentioned before and someone wanted to look at optimizing things.

On systems with large numbers of services and large amounts of log data, sosreport is pretty hungry in terms of the temporary disk space it uses.

For example, if you have N plugins with an average of X MB of logs each then (as far as I can tell) you need the following space available in /tmp to successfully create a final tar file:

 2 \* N \* X

basically, each /var/log/<service> is copied to /tmp, and after everything has been copied a tar file is created. So at peak (once the tar file has just finished being created), you've two uncompressed copies of every service's data . (The temporary area is then deleted, and the tar file is gzipped.)

The most optimized maximum value would be:

N \* Xc 

where Xc would be the average size of the compressed logs. (eg this is what you would use if you just did tar -czvpf /tmp/x.tar /var/log)

The test system I was working on used around 70 GB of /tmp in the process of creating a much, much smaller gzipped tar file.

That's quite a lot of I/O, and means that for systems with lots of services the chances of filling up /tmp and failing to generate a report can be quite high. (So the tool could potentially be made both more efficient and more robust.)

In particular I was looking at OpenStack services. As a workaround I switched from running sosreport with all the plugins specified on one line:

 sosreport -e plugin1,plugin2,plugin3,...

to running it several times:

 sosreport -o plugin1
 sosreport -o plugin2
 sosreport -o plugin3
 .
 .
 .

and then finally without any plugins specified
 sosreport ...

The same data was gathered but the maximum disk usage was ~10GB. (Obviously this generated several tar.gz files, but they could be reflated to give the same end result.)

The behaviour I wanted for the last sosport run was:
 sosreport -n plugin1,plugin2,plugin3,... --all-files
ie I wanted misc files in /var/log, but to avoid recollecting each plugin's log files. I'd to tweak the code a bit to do this (because --all-files will collect everything in /var/log -- it won't exclude the plugins' files).

The maximum disk space used by this approach (assuming fairly compressible data) would be around:

 2 \* Xm

where Xm is the size of the largest plugin's log size. For my case that meant around an order of magnitude less disk space used.

There are probably other strategies which could be tried to really reduce the amount of scratch space needed.

**Comment by bmr-cymru** [comment]
Yes, we are well aware of this - the problem stems from a poorly designed interface and several conflicting constraints: the need to know the size of something in order to add it to a tar file, the need to apply post-processing to content to elide passwords and other secrets, and the limitations of the tar format and python TarFile interface. There are also complications as the archive interacts with features like `--sysroot` (containers).

The intent is that with default options, reasonable size limiting is applied, and only 'active' (non-rotated) log files are captured: if this isn't happening it's considered a bug (normally in an individual plugin or set of plugins).

An implementation was proposed in 2011 that streams content directly to a TarFile, however it had a number of serious security / privacy problems and was dropped in favour of the current FileCacheArchive.

Although there are some improvements that can be made with the current implementation (e.g. teaching FileCacheArchive to not copy files that will not be post-processed) they are kludgey and not ideal - fixing this robustly would involve re-writing the plugin IO so that in-line post-processing is done wherever possible, and a disk cache is only used for very large files, as well as changing the `add_copy_spec_limit()` interface for one that is not ambiguous when presented with directory trees.

It's something we're hoping to address in sos-4.0 - 3.3 was released a couple of months back and we're currently planning whether to make another point release before starting development on 4.0.

> The test system I was working on used around 70 GB of /tmp in the process of creating a much, much 
> smaller gzipped tar file.

That really doesn't sound right. What version are you running? Some of the OpenStack plugins weren't correctly applying the default size limiting in sos-3.2, but this is fixed in 3.3.

They also check for the `--all-logs` switch (which enables collection of rotated logs using a plugin-specific wildcard) - if you see any rotated logs in the set collected it's likely the plugin is using the wrong pattern.

**Comment by bmr-cymru** [comment]
More background in issue #86 (I'd forgotten there were also resource use problems with the original streaming TarFile implementation).

**Comment by TurboTurtle** [comment]
In the intervening years we've fixed a number of bugs related to collection sizes, not least of which 4fe1676 which fixed size limiting on directory specifications. Overall disk space utilization is better than it was in 2016, however it is an accepted fact that for sos, if `--all-logs` is used, space requirements are going to sky rocket.
