### ISSUE TITLE
Python3 Regression regarding file descriptors

### ISSUE THREAD

**Issue by BryanQuigley** [sosreport/sos#938]
This regression just affects python3, running with python2 works fine.  Reverting the below commit does fix the issue for me.

`$ sudo python3 ./sosreport -l | grep python
Traceback (most recent call last):
  File "./sosreport", line 25, in <module>
    main(sys.argv[1:])
  File "/mnt/store/git/sos/sos/sosreport.py", line 1633, in main
    sos = SoSReport(args)
  File "/mnt/store/git/sos/sos/sosreport.py", line 725, in __init__
    self._setup_logging()
  File "/mnt/store/git/sos/sos/sosreport.py", line 850, in _setup_logging
    flog = logging.FileHandler(self.sos_log_file.name)
  File "/usr/lib/python3.5/logging/__init__.py", line 999, in __init__
    self.baseFilename = os.path.abspath(filename)
  File "/usr/lib/python3.5/posixpath.py", line 358, in abspath
    if not isabs(path):
  File "/usr/lib/python3.5/posixpath.py", line 64, in isabs
    return s.startswith(sep)
AttributeError: 'int' object has no attribute 'startswith'`

Traced it to this commit:
`commit 795ef7309af7d49f3f547b231a997730ed6ef626
Author: Pavel Moravec <pmoravec@redhat.com>
Date:   Sun Jan 1 19:05:55 2017 +0100

    [general] close unused file descriptors of temp.files
    
    tempfile.mkstemp call opens a new FD that is redundantly left
    intact until sosreport shutdown. Let close it (added minor fix to
    avoid TOCTOU race - bmr).
    
    Signed-off-by: Pavel Moravec <pmoravec@redhat.com>
    Signed-off-by: Bryn M. Reeves <bmr@redhat.com>`

**Comment by BryanQuigley** [comment]
For a better view - http://pastebin.ubuntu.com/24040922/

**Comment by bmr-cymru** [comment]
Confirmed the bug & bisect results - thanks!

Looking into the problem now.

**Comment by bmr-cymru** [comment]
Ughhhhh...  I think I see the problem (and now I feel dirty..).

It looks as though when a Python3 `file_object` is created from `os.fdopen()` (as in the commit), it returns the file descriptor number (as an `int`!) for the file name attribute:

```python
>>> import os
>>> f = os.fdopen(2)
>>> f
<_io.TextIOWrapper name=2 mode='r' encoding='UTF-8'>
>>> f.name
2
```

In Python2, the name is always `'<fdopen>'`:

```python
>>> import os
>>> f = os.fdopen(2)
>>> f
<open file '<fdopen>', mode 'r' at 0x7f914ca42660>
>>> f.name
'<fdopen>'
```

Sadly, someone already thought about us overwriting the name post-hoc, so that's no option, either:

```python
>>> f.name="qux"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: attribute 'name' of '_io.TextIOWrapper' objects is not writable
```
```python
>>> f.name="qux"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: readonly attribute
```

I'll keep digging to see if we can avoid this on the `sos` side, but I am starting to look at this as a possible python bug - it is a clear change of behaviour (never mind the value - the `name` property of the `file_object` went from being a string to an integer!), and I don't see how client code can be expected to "do the right thing" - an integer value is never a valid file name.

**Comment by BryanQuigley** [comment]
Looks like you fixed this in this series of commits on March 27th, 353135789bc2a5056778bfc4f5167e6dc1efca9c

Thanks! and closing

**Comment by bmr-cymru** [comment]
Yes - sorry - I should've gotten back to you on that. It was a bit of a crazy time in the closing moments of a RHEL release - we found some pretty spectacular breakage as a result of my original patch. The fixes for that ended up fixing this too.

I'm not 100% happy with what we have now - it could use another review I think, but it does at least appear to work correctly across all our supported releases.
