### ISSUE TITLE
[RFE] One-pass creation using TarFile

### ISSUE THREAD

**Issue by sandrobonazzola** [sosreport/sos#944]
Moved from: https://bugzilla.redhat.com/show_bug.cgi?id=654233

Problem:
- sosreport currently creates a directory, put everything there THEN compress it
- This is CPU-intensive, involves an awful lot of unnecessary system calls, involves way more storage than necessary
- When a sosreport fails, users willing to provide files to their support team have to create the tarball themselves, when they know how to do that

Solution:
- Use Tarfile http://docs.python.org/library/tarfile.html
- Symlinks and commands outputs can be provided directly through TarFile.add() and TarInfo
- All signals need to be catched when possible, to make sure we have a consistent tarball

Positive effects:
- Less I/O, less operations
- A lot less disk space being used
- Virtually no temporary files

Negative effects:
- Back to gzip/bzip2 as TarFile does NOT expose the xz algorithm
-- or --
- Compression happens afterwards (partially defeats the purpose of this RFE)

Super-cool effect:
- (In the long term?) we can stop using /tmp and use the current directory.
- Users would have to be very explicitely notified about this change.

... Stuff I didn't think about yet, but please discuss in the comments.

**Comment by bmr-cymru** [comment]
> This is CPU-intensive

Doing the compression in-line does not make it less CPU intensive; the rest of the tarball generation is not that CPU-heavy (aside from the final hashing), and as you point out, compression with `TarFile` is not even in-line anyway (because it reduces the effectiveness of "smart" algorithms).

I know we discussed this on IRC some, but I'll add a short summary here for posterity: this was tried a number of years ago and it creates many problems. The original implementation contained gaping security holes since it broke the file substitution (it would add one copy to the `TarFile`, then later substitute it, and add a *second* copy with the passwords removed...).

Doing this properly means we have to do substitution in-line too: doing that is hard because we must know the final file size before we begin writing the tar header, so we have to do two-pass substitution and work out the sizes. That obviously does not help the goal of reducing CPU overhead... 

Worse, this breaks completely for command output - the state a command relies on may change between invocation, so we either have to cache it on disk anyway, or possibly make broken substitutions.

All in all, and given there are no real solutions to some of these problems (that still achieve the goal of "in-line" processing), and the fact that it would involve a wholesale re-write of the plugin IO paths, it's not been something that we have decided to pursue.

**Comment by bmr-cymru** [comment]
> Super-cool effect:
> 
>   (In the long term?) we can stop using /tmp and use the current directory.
>   Users would have to be very explicitely notified about this change.

Maybe I'm missing something, but what's so great about this? It would change behaviour that's been pretty set since about 2002 (aside the `/tmp` -> `/var/tmp` change) and I'm not sure I see why it is 'better'?

We'd need to make a change of this magnitude in a RHEL major release, and even then, I am not sure I see users thanking us for it. (you can always pass `--tmp-dir=.` if you want this behaviour now).

**Comment by TurboTurtle** [comment]
Closing this out, as this still remains untenable with our needs surrounding postprocessing. If at a later date a solution that provides this benefit, while not breaking our ability to reliably postprocess collections is found, feel free to open a new issue or re-open this one.
