### ISSUE TITLE
docker plugin times out when docker isn't running

### ISSUE THREAD

**Issue by sandrobonazzola** [sosreport/sos#990]
Initially reported on https://bugzilla.redhat.com/show_bug.cgi?id=1441207

Description of problem:

Running sosreport while docker isn't running causes the docker plugin to hang until it is timed out:

...
  Running 21/94: docker...        
[plugin:docker] command 'docker stats --no-stream' timed out after 300s
...

That's arguably a bug in 'docker stats --no-stream'.

Version-Release number of selected component (if applicable):
sos-3.4-1.fc25.noarch
docker-1.12.6-6.gitae7d637.fc25.x86_64

How reproducible:
Always

Steps to Reproduce:
1. systemctl stop docker
2. sosreport --batch

Actual results:
The docker plugin hangs until it is timed out.

Expected results:
No hangs or timeouts

**Comment by bmr-cymru** [comment]
This is a bug in `docker stats` - the plugin is behaving as designed here. Rather than twiddling lots of individual `add_cmd_output()` calls I would rather wait until we have a proper solution for pull #971 - the proposed patch in that pull was not up to scratch (it targets a single plugin rather than all plugins), but the basic idea is sound and something we have talked about for a long time - see also issue #337.
